/*
 DO NOT EDIT MANUALLY !!!
 Generated by scripts\trans_gen.py
*/

#ifndef MAKELANGID
#include <windows.h>
#endif

int gTranslationsCount = 8;

const WCHAR * const gTranslations[] = {
  /* Translations for language en */
  L"%s of %s",
  L"Error: Couldn't run SumatraPDF!",
  L"Error: SumatraPDF hasn't been found!",
  L"Error: The document couldn't be downloaded!",
  L"GB",
  L"KB",
  L"MB",
  L"Opening document in SumatraPDF...",

  /* Translations for language sq */
  L"%s nga %s",
  L"Gabim: Nuk mund të hapë SumatraPDF!",
  L"Gabim: Nuk u gjet SumatraPDF!",
  L"Gabim: Nuk mund të shkarkohet dokumenti!",
  NULL,
  NULL,
  NULL,
  L"Hap dokumentin në SumatraPDF...",

  /* Translations for language ar */
  L"%s من %s",
  L"خطأ: لم أتمكن من تشغيل البرنامج",
  L"خطأ: البرنامج غير موجود",
  L"خطأ: لم أتمكن من تحميل الملف",
  L"ج.ب",
  L"ك.ب",
  L"م.ب",
  L"فتح الملف في SumatraPDF...",

  /* Translations for language am */
  L"%s՝ %s-ից",
  L"Սխալ. Հնարավոր չէ բացել SumatraPDF-ը:",
  L"Սխալ. SumatraPDF-ը չի գտնվել:",
  L"Սխալ. Փաստաթուղթը չի կարող բեռնվել:",
  L"ԳԲ",
  L"ԿԲ",
  L"ՄԲ",
  L"Փաստաթուղթը բացվում է SumatraPDF-ով...",

  /* Translations for language az */
  L"%s/%s",
  L"Xəta: SumatraPDF işə salına bilmədi!",
  L"Xəta: SumatraPDF tapılmadı!",
  L"Xəta: Sənədi endirmək mümkün olmadı!",
  NULL,
  NULL,
  NULL,
  L"Sənəd SumatraPDF-də açılır...",

  /* Translations for language eu */
  L"%s -> %s-tik",
  L"Akatsa: Ezinezkoa SumatraPDF abiaraztea!",
  L"Akatsa: SumatraPDF ez da aurkitu!",
  L"Akatsa: Agiria ezin da jeitsi!",
  NULL,
  NULL,
  NULL,
  L"Agiria irekitzen SumatraPDF-an...",

  /* Translations for language bs */
  L"%s od %s",
  L"Greška: Neuspješno pokretanje SumatraPDF-a!",
  L"Greška: SumatraPDF nije pronađen!",
  L"Greška: Dokument ne može biti preuzet!",
  NULL,
  NULL,
  NULL,
  L"Otvaram dokument u SumatraPDF-u...",

  /* Translations for language bg */
  L"%s от %s",
  L"Грешка: Не може да се стартира SumatraPDF!",
  L"Грешка: SumatraPDF не може да бъде открит!",
  L"Грешка: Документът не може да бъде изтеглен!",
  NULL,
  NULL,
  NULL,
  NULL,

  /* Translations for language ca */
  L"%s de %s",
  L"Error: no es pot executar el SumatraPDF!",
  L"S'ha produït un error: no es troba el SumatraPDF!",
  L"Error: no es pot baixar el document!",
  NULL,
  NULL,
  NULL,
  L"S'està obrint el document al SumatraPDF...",

  /* Translations for language ca-xv */
  L"%s de %s",
  L"Error: no es pot executar el SumatraPDF!",
  L"S'ha produït un error: no es troba el SumatraPDF!",
  L"Error: no es pot baixar el document!",
  NULL,
  NULL,
  NULL,
  L"S'està obrint el document al SumatraPDF...",

  /* Translations for language cn */
  NULL,
  L"错误：无法运行SumatraPDF!",
  L"失败: 找不到SumatraPDF",
  L"错误： 文档无法下载!",
  NULL,
  NULL,
  NULL,
  L"正在用SumatraPDF打开文件...",

  /* Translations for language tw */
  L"%s / %s",
  L"錯誤：無法運行 SumatraPDF!",
  L"錯誤：找不到 SumatraPDF",
  L"錯誤：無法下載文件！",
  NULL,
  NULL,
  NULL,
  L"開啟於 SumatraPDF(&S)",

  /* Translations for language hr */
  L"%s od %s",
  L"Greška: Nemoguće pokrenuti SumatraPDF",
  L"Greška: SumatraPDF nije pronađena",
  L"Greška: Dokument nije moguće preuzeti!",
  L"GiB",
  L"KiB",
  L"MiB",
  L"Otvaranje dokumenta u SumatraPDF...",

  /* Translations for language cz */
  L"%s z %s",
  L"Chyba: Nepodařilo se spustit SumatraPDF!",
  L"Chyba: Program SumatraPDF nebyl nalezen!",
  L"Chyba: Stažení dokumentu se nezdařilo!",
  NULL,
  NULL,
  NULL,
  L"Otevírat dokumenty v SumatraPDF...",

  /* Translations for language dk */
  L"%s af %s",
  L"Fejl: Kan ikke køre SumatraPDF !",
  L"Fejl: SumatraPDF ikke fundet !",
  L"Fejl: Dokumentet kunne ikke hentes !",
  L"Gb",
  L"Kb",
  L"Mb",
  L"Åben dokument i SumatraPDF ...",

  /* Translations for language nl */
  L"%s van %s",
  L"Fout: kon SumatraPDF niet uitvoeren!",
  L"Fout: SumatraPDF werd niet gevonden!",
  L"Fout: het document kon niet gedownload worden!",
  NULL,
  NULL,
  NULL,
  L"Document in SumatraPDF aan het openen...",

  /* Translations for language et */
  L"%s, kokku %s",
  L"Viga: Ei suudetud käivitada rakendust SumatraPDF!",
  L"Viga: Ei leitud rakendust SumatraPDF",
  L"Viga: Dokumenti ei suudetud alla laadida!",
  NULL,
  L"kB",
  NULL,
  L"Dokumendi avamine rakenduses SumatraPDF...",

  /* Translations for language fi */
  L"%s / %s",
  L"Virhe: SumatraPDF:n käynnistäminen epäonnistui!",
  L"Virhe: SumatraPDF ei löytynyt!",
  L"Virhe: asiakirjan lataaminen epäonnistui!",
  L"Gt",
  L"Kt",
  L"Mt",
  L"Avataan asiakirjaa SumatraPDF:ssä...",

  /* Translations for language fr */
  L"%s de %s",
  L"Erreur : impossible de lancer SumatraPDF !",
  L"Erreur : SumatraPDF non trouvé !",
  L"Erreur : le document n'a pu être téléchargé !",
  L"Go",
  L"Ko",
  L"Mo",
  L"Ouverture du document dans SumatraPDF…",

  /* Translations for language gl */
  L"%s de %s",
  L"Erro: non se puido executar SumatraPDF!",
  L"Erro: non se atopou SumatraPDF!",
  L"Erro: o documento non se puido descargar!",
  NULL,
  NULL,
  NULL,
  L"Abrindo o documento en SumatraPDF...",

  /* Translations for language de */
  L"%s von %s",
  L"Fehler: Konnte SumatraPDF nicht ausführen!",
  L"Fehler: SumatraPDF ist unaufindbar!",
  L"Fehler: Das Dokument konnte nicht heruntergeladen werden!",
  NULL,
  NULL,
  NULL,
  L"Das Dokument wird in SumatraPDF geöffnet…",

  /* Translations for language el */
  L"%s από %s",
  L"Σφάλμα: Αδυναμία εκτέλεσης SumatraPDF !",
  L"Σφάλμα: Το SumatraPDF δεν βρέθηκε!",
  L"Σφάλμα: Η λήψη του εγγράφου απέτυχε!",
  NULL,
  NULL,
  NULL,
  L"Άνοιγμα εγγράφου στο SumatraPDF",

  /* Translations for language he */
  L"%s מתוך %s",
  L"הפעלת SumatraPDF נכשלה.",
  L"התוכנה SumatraPDF לא נמצאה.",
  L"הורדת המסמך נכשלה.",
  NULL,
  NULL,
  NULL,
  L"פותח קובץ ב- SumatraPDF...",

  /* Translations for language hu */
  L"%s/%s",
  L"Hiba: SumatraPDF futtatása sikertelen!",
  L"Hiba: SumatraPDF nem található!",
  L"Hiba: a dokumentum letöltése sikertelen!",
  L"Gb",
  L"Kb",
  L"Mb",
  L"Dokumentum megnyitása SumatraPDF-ben...",

  /* Translations for language id */
  L"%s dari %s",
  L"Kesalahan: Tidak bisa menjalankan SumatraPDF.",
  L"Kesalahan: SumatraPDF tidak ditemukan.",
  L"Kesalahan: file tidak dapat diunduh.",
  NULL,
  NULL,
  NULL,
  L"Membuka dokumen menggunakan SumatraPDF",

  /* Translations for language it */
  L"%s di %s",
  L"Errore. Impossibile eseguire SumatraPDF!",
  L"Errore. SumatraPDF non trovato!",
  L"Errore. Il documento non può essere scaricato!",
  NULL,
  NULL,
  NULL,
  L"Apri documento in SumatraPDF...",

  /* Translations for language ja */
  L"%s 中 %s",
  L"エラー: SumatraPDF を実行できませんでした！",
  L"エラー: SumatraPDF が見つかりませんでした！",
  L"エラー: ドキュメントをダウンロードできませんでした！",
  NULL,
  NULL,
  NULL,
  L"SumatraPDF でドキュメントを開いています…",

  /* Translations for language kr */
  L"%s / %s",
  L"오류: SumatraPDF를 실행할 수 없습니다!",
  L"오류: SumatraPDF를 찾을 수 없습니다!",
  L"오류: 문서를 다운로드할 수 없습니다!",
  NULL,
  NULL,
  NULL,
  L"SumatraPDF로 문서 여는 중...",

  /* Translations for language ku */
  L"%s لە %s",
  L"!بکرێتەوە SumatraPDF هەڵە: ناتوانرێت",
  L"هەڵە: SumatraPDF نەدۆزرایەوە!",
  L"!هەڵە: بەڵگەنامە ناتوانرێت دابگیرێت",
  L"گێگابایت",
  L"کیلۆبایت",
  L"مێگابایت",
  L"...SumatraPDF کردنەوەی بەڵگەنامەکان بەهۆی",

  /* Translations for language mk */
  L"%s од %s",
  L"Грешка: SumatraPDF не може да се изврши!",
  L"Грешка: SumatraPDF не постои!",
  L"Грешка: Документот не може да се преземе!",
  NULL,
  NULL,
  NULL,
  L"Го отворам документот во SumatraPDF...",

  /* Translations for language my */
  L"%s daripada %s",
  L"Ralat: Tidak dapat menjalankan SumatraPDF!",
  L"Ralat: SumatraPDF tidak dijumpai!",
  L"Ralat: Dokumen ini tidak boleh dimuat turun!",
  NULL,
  NULL,
  NULL,
  L"Membuka dokumen menggunakan SumatraPDF...",

  /* Translations for language fa */
  NULL,
  L"sumatra pdf خطا: عدم توانایی در اجرای",
  L"خطا :sumatra pdf پیدا نشد",
  L"خطا : عدم توانایی در دانلود متن",
  L"گیگابایت",
  L"کیلوبایت",
  L"مگابایت",
  L"sumatra pdf باز کردن متن در",

  /* Translations for language pl */
  L"%s z %s",
  L"Błąd: nie można uruchomić SumatraPDF",
  L"Błąd: nie znaleziono SumatraPDF",
  L"Błąd: nie można pobrać dokumentu!",
  NULL,
  NULL,
  NULL,
  L"Otwieranie dokumentu w SumatraPDF...",

  /* Translations for language br */
  L"%s de %s",
  L"Não foi possível rodar o SumatraPDF!",
  L"O SumatraPDF não foi encontrado!",
  L"Erro: o documento não pôde ser baixado!",
  NULL,
  NULL,
  NULL,
  L"Abrindo documento no SumatraPDF...",

  /* Translations for language pt */
  L"%s de %s",
  L"Erro: não foi possível iniciar o SumatraPDF!",
  L"Erro: o SumatraPDF não foi encontrado!",
  L"Erro: não foi possível transferir o documento!",
  NULL,
  NULL,
  NULL,
  L"Abrir documento no SumatraPDF",

  /* Translations for language ro */
  L"%s din %s",
  L"Eroare: Nu s-a putut porni Sumatra PDF!",
  L"Eroare: SumatraPDF nu a fost gasit!",
  L"Eroare: Documentul nu s-a putut descarca!",
  NULL,
  NULL,
  NULL,
  L"Deschidere document in SumatraPDF...",

  /* Translations for language ru */
  L"%s из %s",
  L"Ошибка: не удалось запустить SumatraPDF!",
  L"Ошибка: SumatraPDF не найдена!",
  L"Ошибка: не удалось загрузить документ!",
  L"Гб",
  L"Кб",
  L"Мб",
  L"Открытие документа в SumatraPDF...",

  /* Translations for language sr-rs */
  L"%s од %s",
  L"Грешка: Немогуће покретање СуматраПДФ",
  L"Грешка: СуматраПДФ није пронађен!",
  L"Граешка: Документ се не може скинути!",
  NULL,
  L"kB",
  NULL,
  L"Отварање документа у СуматраПДФ",

  /* Translations for language sp-rs */
  L"%s od %s",
  L"Greška: Nemoguć start SumatraPDF",
  L"Greška: SumatraPDF nije pronađen!",
  L"Greška: Dokument se ne može preuzeti!",
  NULL,
  L"kB",
  NULL,
  L"Otvaranje dokumenta u SumatraPDF",

  /* Translations for language sk */
  L"%s z %s",
  L"Chyba: Nie je možné spustiť SumatraPDF!",
  L"Chyba: Program SumatraPDF nebol nájdený!",
  L"Chyba: Stiahnutie súboru sa nepodarilo!",
  NULL,
  NULL,
  NULL,
  L"Otvárať dokument v SumatraPDF...",

  /* Translations for language sl */
  L"%s od %s",
  L"Napaka: ni bilo mogoče zagnati SumatraPDF!",
  L"Napaka: ni bilo mogoče najti SumatraPDF!",
  L"Napaka: ni bilo mogoče prenesti dokumenta!",
  NULL,
  NULL,
  NULL,
  L"Odpiranje dokumenta v SumatraPDF …",

  /* Translations for language es */
  L"%s de %s",
  L"Error: no se pudo ejecutar SumatraPDF.",
  L"Error: ¡SumatraPDF no ha sido encontrado!",
  L"Error: no se pudo descargar el documento.",
  NULL,
  NULL,
  NULL,
  L"Abriendo documento en SumatraPDF...",

  /* Translations for language sv */
  L"%s av %s",
  L"Fel: Kunde inte starta SumatraPDF!",
  L"Fel: Hittade inte SumatraPDF!",
  L"Fel: Dokumentet kunde inte laddas ner!",
  NULL,
  NULL,
  NULL,
  L"Öppnar dokumentet med SumatraPDF...",

  /* Translations for language ta */
  L"%s ல் %s",
  L"சுமத்ரா PDFஐ இயங்கவில்லை",
  L"சுமத்ராPDF காணவில்லை",
  L"பிழை: கோப்பை பதிவிறக்கம் செய்ய முடியவில்லை",
  L"ஜிகா பைட்டு",
  NULL,
  NULL,
  L"கோப்பு சுமத்ரா PDFல் திறக்கப்படுகிறது..",

  /* Translations for language tr */
  L"%s ın %s ı",
  L"Hata: SumatraPDF çalıştırılamadı!",
  L"Hata: SumatraPDF bulunamadı!",
  L"Hata: Belge indirilemedi!",
  NULL,
  NULL,
  NULL,
  L"Belge SumatraPDF ile açılıyor...",

  /* Translations for language uk */
  L"%s із %s",
  L"Помилка: не вдалося запустити SumatraPDF",
  L"Помилка: SumatraPDF не було знайдено",
  L"Помилка: Неможливо завантажити документ!",
  NULL,
  NULL,
  NULL,
  L"Триває відкриття документа у SumatraPDF...",

  /* Translations for language uz */
  L"%s %s'dan",
  L"Xato: SumatraPDF ishga tushirib bo'lmadi!",
  L"Xato: SumatraPDF topilmadi!",
  L"Xato: hujjatni yuklab bo'lmadi!",
  NULL,
  NULL,
  NULL,
  L"Hujjat SumatraPDFda ochilmoqda...",

  /* Translations for language vn */
  L"%s trên %s",
  L"Lỗi: Không thể chạy SumatraPDF!",
  L"Lỗi: Không tìm thấy SumatraPDF!",
  L"Lỗi: Không thể tải tài liệu xuống!",
  NULL,
  NULL,
  NULL,
  L"Đang mở tài liệu bằng SumatraPDF...",

  /* Translations for language cy */
  L"%s o %s",
  L"Gwall. Methu rhedeg SumatraPDF",
  L"Gwall: Heb ganfod SumatraPDF!",
  L"Gwall: Nid oedd modd llwytho'r ddogfen i lawr!",
  NULL,
  NULL,
  NULL,
  L"Agor dogfen yn SumatraPDF...",
};

const char * const gLanguages[] = {
    "en", "sq", "ar", "am", "az", "eu", "bs", "bg", "ca", "ca-xv",
    "cn", "tw", "hr", "cz", "dk", "nl", "et", "fi", "fr", "gl",
    "de", "el", "he", "hu", "id", "it", "ja", "kr", "ku", "mk",
    "my", "fa", "pl", "br", "pt", "ro", "ru", "sr-rs", "sp-rs", "sk",
    "sl", "es", "sv", "ta", "tr", "uk", "uz", "vn", "cy", NULL
};

// from http://msdn.microsoft.com/en-us/library/windows/desktop/dd318693(v=vs.85).aspx
// those definition are not present in 7.0A SDK my VS 2010 uses
#ifndef LANG_CENTRAL_KURDISH
#define LANG_CENTRAL_KURDISH 0x92
#endif

#ifndef SUBLANG_CENTRAL_KURDISH_CENTRAL_KURDISH_IRAQ
#define SUBLANG_CENTRAL_KURDISH_CENTRAL_KURDISH_IRAQ 0x01
#endif

// note: this index isn't guaranteed to remain stable over restarts, so
// persist gLanguages[index/gTranslationsCount] instead
int GetLanguageIndex(LANGID id)
{
    switch (id) {
#define _LANGID(lang) MAKELANGID(lang, SUBLANG_NEUTRAL)
    case _LANGID(LANG_ENGLISH): return 0;
    case _LANGID(LANG_ALBANIAN): return 8;
    case _LANGID(LANG_ARABIC): return 16;
    case _LANGID(LANG_ARMENIAN): return 24;
    case _LANGID(LANG_AZERI): return 32;
    case _LANGID(LANG_BASQUE): return 40;
    case MAKELANGID(LANG_BOSNIAN, SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_LATIN): return 48;
    case _LANGID(LANG_BULGARIAN): return 56;
    case _LANGID(LANG_CATALAN): return 64;
    case MAKELANGID(LANG_CHINESE, SUBLANG_CHINESE_SIMPLIFIED): return 80;
    case MAKELANGID(LANG_CHINESE, SUBLANG_CHINESE_TRADITIONAL): return 88;
    case _LANGID(LANG_CROATIAN): return 96;
    case _LANGID(LANG_CZECH): return 104;
    case _LANGID(LANG_DANISH): return 112;
    case _LANGID(LANG_DUTCH): return 120;
    case _LANGID(LANG_ESTONIAN): return 128;
    case _LANGID(LANG_FINNISH): return 136;
    case _LANGID(LANG_FRENCH): return 144;
    case _LANGID(LANG_GALICIAN): return 152;
    case _LANGID(LANG_GERMAN): return 160;
    case _LANGID(LANG_GREEK): return 168;
    case _LANGID(LANG_HEBREW): return 176;
    case _LANGID(LANG_HUNGARIAN): return 184;
    case _LANGID(LANG_INDONESIAN): return 192;
    case _LANGID(LANG_ITALIAN): return 200;
    case _LANGID(LANG_JAPANESE): return 208;
    case _LANGID(LANG_KOREAN): return 216;
    case MAKELANGID(LANG_CENTRAL_KURDISH, SUBLANG_CENTRAL_KURDISH_CENTRAL_KURDISH_IRAQ): return 224;
    case _LANGID(LANG_MACEDONIAN): return 232;
    case _LANGID(LANG_MALAY): return 240;
    case _LANGID(LANG_FARSI): return 248;
    case _LANGID(LANG_POLISH): return 256;
    case MAKELANGID(LANG_PORTUGUESE, SUBLANG_PORTUGUESE_BRAZILIAN): return 264;
    case _LANGID(LANG_PORTUGUESE): return 272;
    case _LANGID(LANG_ROMANIAN): return 280;
    case _LANGID(LANG_RUSSIAN): return 288;
    case MAKELANGID(LANG_SERBIAN, SUBLANG_SERBIAN_CYRILLIC): return 296;
    case MAKELANGID(LANG_SERBIAN, SUBLANG_SERBIAN_LATIN): return 304;
    case _LANGID(LANG_SLOVAK): return 312;
    case _LANGID(LANG_SLOVENIAN): return 320;
    case _LANGID(LANG_SPANISH): return 328;
    case _LANGID(LANG_SWEDISH): return 336;
    case _LANGID(LANG_TAMIL): return 344;
    case _LANGID(LANG_TURKISH): return 352;
    case _LANGID(LANG_UKRAINIAN): return 360;
    case _LANGID(LANG_UZBEK): return 368;
    case _LANGID(LANG_VIETNAMESE): return 376;
    case _LANGID(LANG_WELSH): return 384;
    default: return -1;
#undef _LANGID
    }
}

bool IsLanguageRtL(int index)
{
    return 16 == index || 176 == index || 224 == index || 248 == index;
}
