/* Generated by scripts\update_translations.py
   DO NOT EDIT MANUALLY */

#ifndef MAKELANGID
#include <windows.h>
#endif

// from http://msdn.microsoft.com/en-us/library/windows/desktop/dd318693(v=vs.85).aspx
// those definition are not present in 7.0A SDK my VS 2010 uses
#ifndef LANG_CENTRAL_KURDISH
#define LANG_CENTRAL_KURDISH 0x92
#endif

#ifndef SUBLANG_CENTRAL_KURDISH_CENTRAL_KURDISH_IRAQ
#define SUBLANG_CENTRAL_KURDISH_CENTRAL_KURDISH_IRAQ 0x01
#endif

#define LANGS_COUNT   7
#define STRINGS_COUNT 8

typedef struct {
    const char *code;
    const char *fullName;
    LANGID id;
    BOOL isRTL;
} LangDef;

#define _LANGID(lang) MAKELANGID(lang, SUBLANG_NEUTRAL)

LangDef gLangData[LANGS_COUNT] = {
    { "en", "English", _LANGID(LANG_ENGLISH), 0 },
    { "cn", "Chinese Simplified (\347\256\200\344\275\223\344\270\255\346\226\207)", MAKELANGID(LANG_CHINESE, SUBLANG_CHINESE_SIMPLIFIED), 0 },
    { "fr", "French (Fran\303\247ais)", _LANGID(LANG_FRENCH), 0 },
    { "de", "German (Deutsch)", _LANGID(LANG_GERMAN), 0 },
    { "pt", "Portuguese - Portugal (Portugu\303\252s)", _LANGID(LANG_PORTUGUESE), 0 },
    { "ru", "Russian (\320\240\321\203\321\201\321\201\320\272\320\270\320\271)", _LANGID(LANG_RUSSIAN), 0 },
    { "uk", "Ukrainian (\320\243\320\272\321\200\320\260\321\227\320\275\321\201\321\214\320\272\320\260)", _LANGID(LANG_UKRAINIAN), 0 },
};

#undef _LANGID

const char *gTranslations[LANGS_COUNT * STRINGS_COUNT] = {

  /* Translations for language en */
  "%s of %s",
  "Error: Couldn't run SumatraPDF!",
  "Error: SumatraPDF hasn't been found!",
  "Error: The document couldn't be downloaded!",
  "GB",
  "KB",
  "MB",
  "Opening document in SumatraPDF...",

  /* Translations for language cn */
  NULL,
  "\351\224\231\350\257\257\357\274\232\346\227\240\346\263\225\350\277\220\350\241\214SumatraPDF!",
  "\345\244\261\350\264\245: \346\211\276\344\270\215\345\210\260SumatraPDF",
  "\351\224\231\350\257\257\357\274\232 \346\226\207\346\241\243\346\227\240\346\263\225\344\270\213\350\275\275!",
  NULL,
  NULL,
  NULL,
  "\346\255\243\345\234\250\347\224\250SumatraPDF\346\211\223\345\274\200\346\226\207\344\273\266...",

  /* Translations for language fr */
  "%s de %s",
  "Erreur : impossible de lancer SumatraPDF !",
  "Erreur : SumatraPDF non trouv\303\251 !",
  "Erreur : le document n'a pu \303\252tre t\303\251l\303\251charg\303\251 !",
  "Go",
  "Ko",
  "Mo",
  "Ouverture du document dans SumatraPDF\342\200\246",

  /* Translations for language de */
  "%s von %s",
  "Fehler: Konnte SumatraPDF nicht ausf\303\274hren!",
  "Fehler: SumatraPDF ist unaufindbar!",
  "Fehler: Das Dokument konnte nicht heruntergeladen werden!",
  NULL,
  NULL,
  NULL,
  "Das Dokument wird in SumatraPDF ge\303\266ffnet...",

  /* Translations for language pt */
  "%s de %s",
  "Erro: n\303\243o foi poss\303\255vel iniciar o SumatraPDF!",
  "Erro: o SumatraPDF n\303\243o foi encontrado!",
  "Erro: n\303\243o foi poss\303\255vel transferir o documento!",
  NULL,
  NULL,
  NULL,
  "Abrir documento no SumatraPDF",

  /* Translations for language ru */
  "%s \320\270\320\267 %s",
  "\320\236\321\210\320\270\320\261\320\272\320\260: \320\275\320\265 \321\203\320\264\320\260\320\273\320\276\321\201\321\214 \320\267\320\260\320\277\321\203\321\201\321\202\320\270\321\202\321\214 SumatraPDF!",
  "\320\236\321\210\320\270\320\261\320\272\320\260: SumatraPDF \320\275\320\265 \320\275\320\260\320\271\320\264\320\265\320\275\320\260!",
  "\320\236\321\210\320\270\320\261\320\272\320\260: \320\275\320\265 \321\203\320\264\320\260\320\273\320\276\321\201\321\214 \320\267\320\260\320\263\321\200\321\203\320\267\320\270\321\202\321\214 \320\264\320\276\320\272\321\203\320\274\320\265\320\275\321\202!",
  "\320\223\320\261",
  "\320\232\320\261",
  "\320\234\320\261",
  "\320\236\321\202\320\272\321\200\321\213\321\202\320\270\320\265 \320\264\320\276\320\272\321\203\320\274\320\265\320\275\321\202\320\260 \320\262 SumatraPDF...",

  /* Translations for language uk */
  "%s \321\226\320\267 %s",
  "\320\237\320\276\320\274\320\270\320\273\320\272\320\260: \320\275\320\265 \320\262\320\264\320\260\320\273\320\276\321\201\321\217 \320\267\320\260\320\277\321\203\321\201\321\202\320\270\321\202\320\270 SumatraPDF",
  "\320\237\320\276\320\274\320\270\320\273\320\272\320\260: SumatraPDF \320\275\320\265 \320\261\321\203\320\273\320\276 \320\267\320\275\320\260\320\271\320\264\320\265\320\275\320\276",
  "\320\237\320\276\320\274\320\270\320\273\320\272\320\260: \320\235\320\265\320\274\320\276\320\266\320\273\320\270\320\262\320\276 \320\267\320\260\320\262\320\260\320\275\321\202\320\260\320\266\320\270\321\202\320\270 \320\264\320\276\320\272\321\203\320\274\320\265\320\275\321\202!",
  NULL,
  NULL,
  NULL,
  "\320\242\321\200\320\270\320\262\320\260\321\224 \320\262\321\226\320\264\320\272\321\200\320\270\321\202\321\202\321\217 \320\264\320\276\320\272\321\203\320\274\320\265\320\275\321\202\320\260 \321\203 SumatraPDF...",
};
