.TH PDFCLEAN 1 "September  4, 2011"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
pdfclean \- pretty print, decompress and garbage collect PDF files
.SH SYNOPSIS
.B pdfclean
.RI [ options ]
.RI input.pdf
.RI [ output.pdf ]
.RI [ pages ]
.SH DESCRIPTION
.B pdfclean
pretty prints and rewrites the contents of a PDF file.
If no output file is specified, the new file will be written to "out.pdf" in
the current directory.
.PP
.SH OPTIONS
.TP
.B \-p password
Use the specified password if the file is encrypted.
.TP
.B \-g
Garbage collect objects that have no references from other objects.
Give the option twice to renumber all objects and compact the cross reference table.
Give it three times to merge and reuse duplicate objects.
.TP
.B \-d
Decompress streams. This will make the output file larger, but provides
easy access for reading and editing the contents with a text editor.
.TP
.B pages
Comma separated list of ranges to clean.
.SH SEE ALSO
.BR mupdf (1),
.BR pdfdraw (1).
.BR pdfshow (1).
.SH AUTHOR
MuPDF was written by Tor Andersson <tor@ghostscript.com>.
MuPDF is Copyright 2006-2010 Artifex Software, Inc.
