.TH PDFDRAW 1 "September  4, 2011"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
pdfdraw \- render PDF documents
.SH SYNOPSIS
.B pdfdraw
.RI [ options ]
.RI input.pdf
.RI [ pages]
.SH DESCRIPTION
.B pdfdraw
will render a PDF document to image files.
The supported image formats are: pgm, ppm, pam and png.
Select the pages to be rendered by specifying a comma
separated list of ranges and individual page numbers (for example: 1,5,10-15).
In no pages are specified all the pages will be rendered.
.SH OPTIONS
.TP
.B \-o output
The image format is deduced from the output file name.
Embed %d in the name to indicate the page number (for example: "page%d.png").
.TP
.B \-p password
Use the specified password if the file is encrypted.
.TP
.B \-r resolution
Render the page at the specified resolution.
The default resolution is 72 dpi.
.TP
.B \-R angle
Rotate clockwise by given number of degrees.
.TP
.B \-a
Save the alpha channel.
The default behavior is to render each page with a white background.
With this option, the page background is transparent.
Only supported for pam and png output formats.
.TP
.B \-g
Render in grayscale.
The default is to render a full color RGB image.
If the output format is pgm or ppm this option is ignored.
.TP
.B \-m
Show timing information.
Take the time it takes for each page to render and print
a summary at the end.
.TP
.B \-5
Print an MD5 checksum of the rendered image data for each page.
.TP
.B \-t
Print the text contents of each page in UTF-8 encoding.
Give the option twice to print detailed information
about the location of each character in XML format.
.TP
.B \-x
Print the display list used to render each page.
.TP
.B \-A
Disable the use of accelerated functions.
.TP
.B \-G gamma
Gamma correct the output image.
Some typical values are 0.7 or 1.4 to thin or darken text rendering.
.TP
.B \-I
Invert the output image colors.
.TP
.B pages
Comma separated list of ranges to render.
.SH SEE ALSO
.BR mupdf (1),
.BR pdfclean (1).
.BR pdfshow (1).
.SH AUTHOR
MuPDF was written by Tor Andersson <tor@ghostscript.com>.
MuPDF is Copyright 2006-2010 Artifex Software, Inc.
