.TH PDFSHOW 1 "July 19, 2010"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
pdfshow \- show objects and streams that make up a PDF document
.SH SYNOPSIS
.B pdfshow
.RI [ options ]
.RI file.pdf
.RI [ xref ]
.RI [ trailer ]
.RI [ pages ]
.RI [ grep ]
.RI [ object-number... ]
.SH DESCRIPTION
.B pdfshow
pretty prints the objects and streams specified on the command line.
Streams are decoded and non-printable characters are represented
with a period.
Specify objects with their number.
The special names xref, trailer and pages will
respectively print the cross reference, trailer,
and the object numbers for all pages.
The special name grep will print all objects in the file
in a compact one-line format suitable for piping to grep.
.PP
.SH OPTIONS
.TP
.B \-b
Print streams as binary data and omit the object header.
.TP
.B \-e
Print streams in their original encoded form.
.TP
.B \-p password
Use the specified password if the file is encrypted.
.SH SEE ALSO
.BR mupdf (1),
.BR pdfclean (1).
.BR pdfdraw (1).
.SH AUTHOR
MuPDF was written by Tor Andersson <tor@ghostscript.com>.
MuPDF is copyright 2006-2010 Artifex Software, Inc.
