#ifndef MUPDF_FITZ_VERSION_H
#define MUPDF_FITZ_VERSION_H
#ifndef FZ_VERSION
#define FZ_VERSION "1.16.1"
#define FZ_VERSION_MAJOR 1
#define FZ_VERSION_MINOR 16
#define FZ_VERSION_PATCH 1
#endif
#endif
