#!/usr/bin/env python

"""
Generates a list of all exports from libmupdf.dll from the function lists
contained in the mupdf/include/* headers (only MuPDF and MuXPS are included)
and adds exports for the other libraries contained within libmupdf.dll but
used by SumatraPDF / PdfPreview / etc. (djvudec, zlib, libwebp, libjxl, heicdec).
Image codec static libs must only be linked into libmupdf.dll — not into those
exes/dlls — and the few needed C APIs are re-exported below.
"""

import os, re, util

def generateExports(header, exclude=[]):
	if os.path.isdir(header):
		return "\n".join([generateExports(os.path.join(header, file), exclude) for file in os.listdir(header)])

	data = open(header, "r").read()
	data = re.sub(r"(?sm)^#ifndef NDEBUG\s.*?^#endif", "", data, 0)
	data = re.sub(r"(?sm)^#ifdef ARCH_ARM\s.*?^#endif", "", data, 0)
	data = re.sub(r"(?sm)^#ifdef FITZ_DEBUG_LOCKING\s.*?^#endif", "", data, 0)
	data = data.replace(" FZ_NORETURN;", ";")
	functions = re.findall(r"(?sm)^\w+ (?:\w+ )?\*?(\w+)\(.*?\);", data)
	return "\n".join(["\t" + name for name in functions if name not in exclude])

def collectFunctions(file):
	data = open(file, "r").read()
	return re.findall(r"(?sm)^\w+(?: \*\n|\n| \*| )((?:fz_|pdf_|xps_)\w+)\(", data)

LIBMUPDF_DEF = """\
; This file is auto-generated by gen_libmupdf.def.py

LIBRARY libmupdf
EXPORTS

; Fitz exports

%(fitz_exports)s

; MuPDF exports

%(mupdf_exports)s

; MuXPS exports

%(muxps_exports)s

; djvudec exports (required for EngineDjvuDec, ext/djvudec)

	djvu_init
	djvu_ctx_new
	djvu_ctx_free
	djvu_ctx_set_cache_per_page
	djvu_ctx_set_lazy_iw44
	djvu_ctx_set_no_compose
	djvu_ctx_set_iw_max_chunks
	djvu_ctx_set_bgr
	djvu_request_abort
	djvu_abort_init
	djvu_abort_request
	djvu_doc_open
	djvu_doc_close
	djvu_doc_page_count
	djvu_doc_page_info
	djvu_doc_drop_page_cache
	djvu_doc_page_cache_size
	djvu_page_get_type
	djvu_page_render
	djvu_page_render_info
	djvu_page_render_into
	djvu_page_render_abortable
	djvu_page_render_into_abortable
	djvu_image_destroy
	djvu_doc_page_id
	djvu_doc_page_title
	djvu_doc_page_by_name
	djvu_page_text_get_zones
	djvu_text_zones_destroy
	djvu_doc_outline
	djvu_outline_destroy
	djvu_page_get_links
	djvu_page_links_destroy

; zlib exports (required for ZipUtil, PsEngine, PdfCreator, LzmaSimpleArchive)

	crc32
	deflate
	deflateEnd
	deflateInit_
	deflateInit2_
	gzclose
	gzerror
	gzopen
	gzopen_w
	gzprintf
	gzread
	gzseek
	gztell
	inflate
	inflateEnd
	inflateInit_
	inflateInit2_

; lzma exports (required for LzmaSimpleArchive)

	LzmaDecode
	x86_Convert

; libwebp exports (required for WebpReader)

	WebPDecodeBGRAInto
	WebPGetInfo

; cmark-gfm exports (required for MarkdownToc; also used by mupdf md.c).
; Keep the cmark-gfm static-lib project; link it only into mupdf/libmupdf.dll
; and re-export these so SumatraPDF.exe does not carry a second copy.

	cmark_find_syntax_extension
	cmark_get_default_mem_allocator
	cmark_gfm_core_extensions_ensure_registered
	cmark_iter_free
	cmark_iter_get_node
	cmark_iter_new
	cmark_iter_next
	cmark_node_first_child
	cmark_node_free
	cmark_node_get_heading_level
	cmark_node_get_type
	cmark_node_next
	cmark_parser_attach_syntax_extension
	cmark_parser_feed
	cmark_parser_finish
	cmark_parser_free
	cmark_parser_get_syntax_extensions
	cmark_parser_new
	cmark_render_html

; libarchive exports (required for base/Archive.cpp). Keep the libarchive
; static-lib project; link it only into mupdf/libmupdf.dll (and static EXE)
; and re-export these so SumatraPDF.exe / PdfFilter / PdfPreview do not carry
; a second copy.

	archive_entry_filetype
	archive_entry_mtime
	archive_entry_pathname
	archive_entry_pathname_utf8
	archive_entry_size
	archive_format
	archive_read_add_passphrase
	archive_read_data
	archive_read_data_skip
	archive_read_free
	archive_read_has_encrypted_entries
	archive_read_new
	archive_read_next_header
	archive_read_open_filename
	archive_read_open_filename_w
	archive_read_open_memory
	archive_read_support_filter_all
	archive_read_support_format_all

; unrar exports (required for base/Archive.cpp RAR fallback). Keep the unrar
; static-lib project; link it only into libmupdf.dll (and static EXE) and
; re-export these so SumatraPDF.exe / PdfFilter / PdfPreview do not carry a
; second copy. Functions are PASCAL (stdcall); .def names stay undecorated.

	RAROpenArchiveEx
	RARCloseArchive
	RARReadHeaderEx
	RARProcessFile
"""

def main():
	util.chdir_top()
	os.chdir("mupdf")

	# don't include/export doc_* functions, support for additional input/output formats and form support
	doc_exports = collectFunctions("source/fitz/document.c") + collectFunctions("source/fitz/document-all.c") + collectFunctions("source/fitz/document-no-run.c") + ["fz_get_annot_type"]
	more_formats = collectFunctions("source/fitz/svg-device.c") + collectFunctions("source/fitz/output-pcl.c") + collectFunctions("source/fitz/output-pwg.c")
	form_exports = collectFunctions("source/pdf/pdf-form.c") + collectFunctions("source/pdf/pdf-event.c") + collectFunctions("source/pdf/pdf-appearance.c") + collectFunctions("source/pdf/js/pdf-jsimp-cpp.c") + ["pdf_access_submit_event", "pdf_init_ui_pointer_event"]
	misc_exports = collectFunctions("source/fitz/stream-prog.c") + collectFunctions("source/fitz/test-device.c")
	sign_exports = ["pdf_crypt_buffer", "pdf_read_pfx", "pdf_sign_signature", "pdf_signer_designated_name", "pdf_free_designated_name"]

	fitz_exports = generateExports("include/mupdf/fitz", doc_exports + more_formats + misc_exports)
	mupdf_exports = generateExports("include/mupdf/pdf", form_exports + sign_exports + ["pdf_open_compressed_stream"])
	muxps_exports = generateExports("include/mupdf/xps.h", ["xps_parse_solid_color_brush", "xps_print_path"])
	list = LIBMUPDF_DEF % locals()
	open("../src/libmupdf.def", "wb").write(list.replace("\n", "\r\n"))

if __name__ == "__main__":
	main()
