#!/usr/bin/env python
"""
Generates src/base/HtmlTags.h / .cpp: enums for HTML tags, align attribute
values and CSS properties, plus lookups from a name to the enum value and
from an HTML/XML entity name to its rune. Names live in tables (linear scan
for the short lists, binary search for entities); run clang-format after.
"""

import os
from html.entities import entitydefs


def chdir_top():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(os.path.abspath(os.path.join(script_dir, "..", "..")))


# given e.g. "mbp:pagebreak" returns "Tag_Mbp_Pagebreak"
def enum_name(name, prefix):
    parts = name.replace("-", ":").split(":")
    parts = [p[0].upper() + p[1:].lower() for p in parts]
    return "_".join([prefix] + parts)


# joins items with sep into lines of at most ~110 chars
def pack(items, sep, width=110):
    lines = []
    cur = ""
    for it in items:
        if cur and len(cur) + len(sep) + len(it) > width:
            lines.append(cur)
            cur = it
        else:
            cur = cur + sep + it if cur else it
    if cur:
        lines.append(cur)
    return lines


def enum_decl(kind, type_name, values):
    return "%s %s {\n    %s\n};\n" % (kind, type_name, ",\n    ".join(values))


# a SeqStrings literal: names in enum order, NUL-separated
def seq_strings(var, names):
    lines = pack(['"%s\\0"' % n for n in names], " ")
    return "// clang-format off\nstatic SeqStrings %s =\n    %s;\n// clang-format on\n" % (var, "\n    ".join(lines))


########## HTML tags and attributes ##########

# This list has been generated by instrumenting HtmlFormatter.cpp
# to dump all tags we see in a mobi file and also some from EPUB and FB2 files
List_HTML_Tags = "a abbr acronym area audio b base basefont blockquote body br center code col dd div dl dt em font frame h1 h2 h3 h4 h5 h6 head hr html i img input lh li link meta nav object ol p param pre s script section small span strike strong style sub sup table td th title tr tt u ul video"
List_Other_Tags = "image mbp:pagebreak pagebreak subtitle svg svg:image"
List_Align_Values = "center justify left right"

# these tags must all also appear in List_HTML_Tags or List_Other_Tags (else they're ignored)
List_Self_Closing_Tags = "area base basefont br col frame hr img input link mbp:pagebreak meta pagebreak param"
List_Inline_Tags = "a abbr acronym audio b code em font i s small span strike strong sub sup tt u video"

########## HTML and XML entities ##########

# selection of MathML2 entities that aren't HTML entities
List_MathML2_Entities = [("DoubleDot", 168), ("OverBar", 175), ("PlusMinus", 177), ("Cedilla", 184), ("Amacr", 256), ("amacr", 257), ("Abreve", 258), ("abreve", 259), ("Aogon", 260), ("aogon", 261), ("Cacute", 262), ("cacute", 263), ("Ccirc", 264), ("ccirc", 265), ("Cdot", 266), ("cdot", 267), ("Ccaron", 268), ("ccaron", 269), ("Dcaron", 270), ("dcaron", 271), ("Dstrok", 272), ("dstrok", 273), ("Emacr", 274), ("emacr", 275), ("Edot", 278), ("edot", 279), ("Eogon", 280), ("eogon", 281), ("Ecaron", 282), ("ecaron", 283), ("Gcirc", 284), ("gcirc", 285), ("Gbreve", 286), ("gbreve", 287), ("Gdot", 288), ("gdot", 289), ("Gcedil", 290), ("Hcirc", 292), ("hcirc", 293), ("Hstrok", 294), ("hstrok", 295), ("Itilde", 296), ("itilde", 297), ("Imacr", 298), ("imacr", 299), ("Iogon", 302), ("iogon", 303), ("Idot", 304), ("IJlig", 306), ("ijlig", 307), ("Jcirc", 308), ("jcirc", 309), ("Kcedil", 310), ("kcedil", 311), ("kgreen", 312), ("Lacute", 313), ("lacute", 314), ("Lcedil", 315), ("lcedil", 316), ("Lcaron", 317), ("lcaron", 318), ("Lmidot", 319), ("lmidot", 320), ("Lstrok", 321), ("lstrok", 322), ("Nacute", 323), ("nacute", 324), ("Ncedil", 325), ("ncedil", 326), ("Ncaron", 327), ("ncaron", 328), ("napos", 329), ("ENG", 330), ("eng", 331), ("Omacr", 332), ("omacr", 333), ("Odblac", 336), ("odblac", 337), ("Racute", 340), ("racute", 341), ("Rcedil", 342), ("rcedil", 343), ("Rcaron", 344), ("rcaron", 345), ("Sacute", 346), ("sacute", 347), ("Scirc", 348), ("scirc", 349), ("Scedil", 350), ("scedil", 351), ("Tcedil", 354), ("tcedil", 355), ("Tcaron", 356), ("tcaron", 357), ("Tstrok", 358), ("tstrok", 359), ("Utilde", 360), ("utilde", 361), ("Umacr", 362), ("umacr", 363), ("Ubreve", 364), ("ubreve", 365), ("Uring", 366), ("uring", 367), ("Udblac", 368), ("udblac", 369), ("Uogon", 370), ("uogon", 371), ("Wcirc", 372), ("wcirc", 373), ("Ycirc", 374), ("ycirc", 375), ("Zacute", 377), ("zacute", 378), ("Zdot", 379), ("zdot", 380), ("Zcaron", 381), ("zcaron", 382), ("imped", 437), ("gacute", 501), ("Hacek", 711), ("Breve", 728), ("DiacriticalDot", 729), ("ring", 730), ("ogon", 731), ("DiacriticalTilde", 732), ("DiacriticalDoubleAcute", 733), ("DownBreve", 785), ("UnderBar", 818), ("varepsilon", 949), ("varsigma", 962), ("varphi", 966), ("vartheta", 977), ("Upsi", 978), ("straightphi", 981), ("varpi", 982), ("Gammad", 988), ("digamma", 989), ("varkappa", 1008), ("varrho", 1009), ("straightepsilon", 1013), ("backepsilon", 1014)]

########## CSS properties ##########

List_CSS_Props = "color display font font-family font-size font-style font-weight list-style margin margin-bottom margin-left margin-right margin-top max-width opacity padding padding-bottom padding-left padding-right padding-top page-break-after page-break-before text-align text-decoration text-indent text-underline white-space word-wrap"

########## main ##########

Header = """\
/* Copyright 2022 the SumatraPDF project authors (see AUTHORS file).
   License: Simplified BSD (see COPYING.BSD) */

// This file is auto-generated by cmd/scripts/gen_htmlparserlookup.py

%(enum_htmltag)s
%(enum_alignattr)s
HtmlTag FindHtmlTag(Str name);
bool IsTagSelfClosing(HtmlTag tag);
bool IsInlineTag(HtmlTag tag);
AlignAttr FindAlignAttr(Str name);
u32 FindHtmlEntityRune(Str name);

%(enum_cssprop)s
CssProp FindCssProp(Str name);
"""

Code = """\
/* Copyright 2022 the SumatraPDF project authors (see AUTHORS file).
   License: Simplified BSD (see COPYING.BSD) */

// This file is auto-generated by cmd/scripts/gen_htmlparserlookup.py

#include "base/Base.h"
#include "base/HtmlTags.h"

// names in enum order, so the index of a name is its enum value
%(tag_names)s
%(align_names)s
%(css_names)s
HtmlTag FindHtmlTag(Str name) {
    int idx = SeqStrIndexI(gHtmlTagNames, name);
    return idx < 0 ? Tag_NotFound : (HtmlTag)idx;
}

AlignAttr FindAlignAttr(Str name) {
    int idx = SeqStrIndexI(gAlignAttrNames, name);
    return idx < 0 ? AlignAttr::NotFound : (AlignAttr)idx;
}

CssProp FindCssProp(Str name) {
    int idx = SeqStrIndexI(gCssPropNames, name);
    return idx < 0 ? Css_Unknown : (CssProp)idx;
}

// per tag: bit 0 = self-closing, bit 1 = inline
constexpr u8 kSelfClosing = 1;
constexpr u8 kInline = 2;
// clang-format off
static const u8 gTagFlags[Tag_NotFound] = {%(tag_flags)s};
// clang-format on

bool IsTagSelfClosing(HtmlTag tag) {
    return tag < Tag_NotFound && (gTagFlags[tag] & kSelfClosing) != 0;
}

bool IsInlineTag(HtmlTag tag) {
    return tag < Tag_NotFound && (gTagFlags[tag] & kInline) != 0;
}

// entity names to their Unicode runes, sorted for binary search (str::Cmp order), cf.
// http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
// and http://www.w3.org/TR/MathML2/bycodes.html
// clang-format off
static const struct {
    const char* name;
    u32 rune;
} gHtmlEntities[] = {
    %(entities)s
};
// clang-format on

u32 FindHtmlEntityRune(Str name) {
    int lo = 0;
    int hi = dimofi(gHtmlEntities) - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int c = str::Cmp(Str(gHtmlEntities[mid].name), name);
        if (c == 0) {
            return gHtmlEntities[mid].rune;
        }
        if (c < 0) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return (u32)-1;
}
"""


def main():
    chdir_top()

    tags = sorted(List_HTML_Tags.split() + List_Other_Tags.split())
    aligns = sorted(List_Align_Values.split())
    css_props = sorted(List_CSS_Props.split())

    self_closing = set(List_Self_Closing_Tags.split())
    inline = set(List_Inline_Tags.split())
    tag_flags = ", ".join(str((t in self_closing) + 2 * (t in inline)) for t in tags)  # per tag in enum order

    entitydefs["apos"] = "'"  # only XML entity that isn't an HTML entity as well
    entities = [(name, ord(value)) for name, value in entitydefs.items()]
    for name, value in List_MathML2_Entities:
        assert name not in entitydefs
        entities.append((name, value))
    # str::Cmp compares unsigned bytes then length, which sorted() matches for ASCII
    entities.sort()
    entities_str = "\n    ".join(pack(['{"%s", %d},' % e for e in entities], " "))

    header = Header % {
        "enum_htmltag": enum_decl("enum", "HtmlTag", [enum_name(t, "Tag") for t in tags] + ["Tag_NotFound"]),
        "enum_alignattr": enum_decl("enum class", "AlignAttr", [enum_name(a, "Align")[len("Align_"):] for a in aligns] + ["NotFound"]),
        "enum_cssprop": enum_decl("enum", "CssProp", [enum_name(p, "Css") for p in css_props] + ["Css_Unknown"]),
    }
    code = Code % {
        "tag_names": seq_strings("gHtmlTagNames", tags),
        "align_names": seq_strings("gAlignAttrNames", aligns),
        "css_names": seq_strings("gCssPropNames", css_props),
        "tag_flags": tag_flags,
        "entities": entities_str,
    }
    open("src/base/HtmlTags.h", "w", newline="\n").write(header)
    open("src/base/HtmlTags.cpp", "w", newline="\n").write(code)


if __name__ == "__main__":
    main()
