// #5933: a newly created annotation is selected (resize handles up). A click
// on empty page must leave that edit-size mode. Mouse-up used to re-select
// whatever annotationUnderCursor last saw, so a click away after creating a
// stamp (hover still on the stamp) kept the handles up.
import { mkdirSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { ControlClient, ControlCommand } from "./control";
import { ROOT, cmdId, runStandalone, tmpPath } from "./util";
import {
  captureWindowToPng,
  clientToScreen,
  getClientRect,
  packCoords,
  sendMessage,
  setCursorPos,
  sleep,
  MK_LBUTTON,
  MK_RBUTTON,
  VK_ESCAPE,
  WM_COMMAND,
  WM_KEYDOWN,
  WM_LBUTTONDOWN,
  WM_LBUTTONUP,
  WM_MOUSEMOVE,
  WM_RBUTTONDOWN,
  WM_RBUTTONUP,
} from "./winapi";
import { findCanvas, killAndWait, launchControlled } from "./win-automation";

function hover(canvas: number, x: number, y: number) {
  sendMessage(canvas, WM_MOUSEMOVE, 0, packCoords(x, y));
}

function clickAt(canvas: number, x: number, y: number) {
  const lp = packCoords(x, y);
  sendMessage(canvas, WM_LBUTTONDOWN, MK_LBUTTON, lp);
  sendMessage(canvas, WM_LBUTTONUP, 0, lp);
}

type SelectedAnnotState = {
  rect: { x: number; y: number; dx: number; dy: number };
  canResize: boolean;
  resizeRerenderPending: boolean;
  raw: string;
};

async function selectedAnnotState(client: ControlClient): Promise<SelectedAnnotState> {
  const res = await client.request(ControlCommand.TestAnnotEditorLayout, [0, 0]);
  const raw = String(res[1] ?? "").trim();
  const m = / annotType=\d+ annotRect=(-?\d+),(-?\d+),(\d+),(\d+) canResize=(\d)/.exec(raw);
  if (res[0] !== 0 || !m) {
    throw new Error(`issue-5933: could not read selected annotation: ${raw}`);
  }
  return {
    rect: { x: +m[1]!, y: +m[2]!, dx: +m[3]!, dy: +m[4]! },
    canResize: m[5] === "1",
    resizeRerenderPending: / resizeRerenderPending=1/.test(raw),
    raw,
  };
}

function dragLeftButton(canvas: number, x: number, y: number, endX: number, endY: number): void {
  const end = clientToScreen(canvas, endX, endY);
  // Keep any native WM_MOUSEMOVE generated by SetCursorPos at the same endpoint
  // as the synthetic drag; a queued move at the start point can undo it.
  setCursorPos(end.x, end.y);
  sendMessage(canvas, WM_MOUSEMOVE, 0, packCoords(endX, endY));
  sendMessage(canvas, WM_LBUTTONDOWN, MK_LBUTTON, packCoords(x, y));
  sendMessage(canvas, WM_MOUSEMOVE, MK_LBUTTON, packCoords(endX, endY));
  sendMessage(canvas, WM_LBUTTONUP, 0, packCoords(endX, endY));
}

// A real click usually moves a few pixels. That used to become a page pan
// (SM_CXDRAG) and skip the mouse-up deselect, so size-edit stuck.
function clickAwayWithJitter(canvas: number, x: number, y: number) {
  const x1 = x + 16;
  const y1 = y + 16;
  const p0 = clientToScreen(canvas, x, y);
  const p1 = clientToScreen(canvas, x1, y1);
  setCursorPos(p0.x, p0.y);
  sendMessage(canvas, WM_LBUTTONDOWN, MK_LBUTTON, packCoords(x, y));
  setCursorPos(p1.x, p1.y);
  sendMessage(canvas, WM_MOUSEMOVE, MK_LBUTTON, packCoords(x1, y1));
  sendMessage(canvas, WM_LBUTTONUP, 0, packCoords(x1, y1));
}

// Context-menu creation leaves dragRightClick set. Reproduce that without
// opening a modal menu: cross the right-drag threshold, return to the start so
// the page does not move, and release.
function primeRightDragState(canvas: number, x: number, y: number) {
  const x1 = x + 16;
  const y1 = y + 16;
  const p0 = clientToScreen(canvas, x, y);
  const p1 = clientToScreen(canvas, x1, y1);
  setCursorPos(p0.x, p0.y);
  sendMessage(canvas, WM_RBUTTONDOWN, MK_RBUTTON, packCoords(x, y));
  setCursorPos(p1.x, p1.y);
  sendMessage(canvas, WM_MOUSEMOVE, MK_RBUTTON, packCoords(x1, y1));
  setCursorPos(p0.x, p0.y);
  sendMessage(canvas, WM_MOUSEMOVE, MK_RBUTTON, packCoords(x, y));
  sendMessage(canvas, WM_RBUTTONUP, 0, packCoords(x, y));
}

export async function testit(): Promise<void> {
  const dir = tmpPath("issue-5933");
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  const appdata = join(dir, "appdata");
  mkdirSync(appdata, { recursive: true });
  const pdf = join(ROOT, "ext", "a-zlib", "zlib.3.pdf");
  const { proc, client, frame } = await launchControlled([
    "-appdata",
    appdata,
    "-view",
    "single page",
    "-zoom",
    "fit page",
    pdf,
  ]);
  try {
    await client.waitForRenderIdle();
    await client.setNotificationsEnabled(false);
    const canvas = findCanvas(frame);
    const cr = getClientRect(canvas);
    const stampX = 80;
    const stampY = 80;
    const awayX = Math.max(40, cr.right - 40);
    const awayY = Math.max(40, cr.bottom - 40);

    sendMessage(frame, WM_COMMAND, cmdId("CmdCreateAnnotStamp"), packCoords(stampX, stampY));
    await sleep(400);
    await client.waitForRenderIdle();

    const stampBeforeRight = await selectedAnnotState(client);
    if (!stampBeforeRight.canResize) {
      throw new Error(`issue-5933: stamp is not resizable: ${stampBeforeRight.raw}`);
    }
    const r0 = stampBeforeRight.rect;
    const rightX = r0.x + r0.dx;
    const middleY = r0.y + Math.floor(r0.dy / 2);
    const rightEnd = clientToScreen(canvas, rightX + 40, middleY);
    setCursorPos(rightEnd.x, rightEnd.y);
    sendMessage(canvas, WM_MOUSEMOVE, 0, packCoords(rightX + 40, middleY));
    sendMessage(canvas, WM_LBUTTONDOWN, MK_LBUTTON, packCoords(rightX, middleY));
    sendMessage(canvas, WM_MOUSEMOVE, MK_LBUTTON, packCoords(rightX + 40, middleY));
    let resizeInProgress = await selectedAnnotState(client);
    const resizeStartedDeadline = Date.now() + 750;
    while (
      (!resizeInProgress.resizeRerenderPending || resizeInProgress.rect.dx < r0.dx + 30) &&
      Date.now() < resizeStartedDeadline
    ) {
      sendMessage(canvas, WM_MOUSEMOVE, MK_LBUTTON, packCoords(rightX + 40, middleY));
      resizeInProgress = await selectedAnnotState(client);
    }
    if (!resizeInProgress.resizeRerenderPending || resizeInProgress.rect.dx < r0.dx + 30) {
      throw new Error(
        `issue-5933: resize bounds or rerender debounce was not updated immediately: ${resizeInProgress.raw}`,
      );
    }
    let resizeSettled = resizeInProgress;
    const rerenderDeadline = Date.now() + 2000;
    while (resizeSettled.resizeRerenderPending && Date.now() < rerenderDeadline) {
      await sleep(25);
      resizeSettled = await selectedAnnotState(client);
    }
    if (resizeSettled.resizeRerenderPending) {
      throw new Error(`issue-5933: annotation resize rerender did not run after 125 ms: ${resizeSettled.raw}`);
    }
    sendMessage(canvas, WM_LBUTTONUP, 0, packCoords(rightX + 40, middleY));
    await client.waitForRenderIdle();
    const stampAfterRight = await selectedAnnotState(client);
    const r1 = stampAfterRight.rect;
    if (Math.abs(r1.x - r0.x) > 2 || r1.dx < r0.dx + 30 || Math.abs(r1.y + r1.dy / 2 - (r0.y + r0.dy / 2)) > 2) {
      throw new Error(
        `issue-5933: right edge moved rather than resized stamp: before=${stampBeforeRight.raw} after=${stampAfterRight.raw}`,
      );
    }

    dragLeftButton(canvas, r1.x + Math.floor(r1.dx / 2), r1.y + r1.dy, r1.x + Math.floor(r1.dx / 2), r1.y + r1.dy + 20);
    await client.waitForRenderIdle();
    const stampAfterBottom = await selectedAnnotState(client);
    const r2 = stampAfterBottom.rect;
    if (Math.abs(r2.y - r1.y) > 2 || r2.dy < r1.dy + 14 || Math.abs(r2.x + r2.dx / 2 - (r1.x + r1.dx / 2)) > 2) {
      throw new Error(
        `issue-5933: bottom edge moved rather than resized stamp: before=${stampAfterRight.raw} after=${stampAfterBottom.raw}`,
      );
    }

    hover(canvas, stampX + 20, stampY + 20);
    await sleep(80);
    const selectedPng = join(dir, "selected.png");
    if (!captureWindowToPng(canvas, selectedPng)) {
      throw new Error("issue-5933: capture selected failed");
    }

    // click empty page without a hover update first — that's the regression
    clickAt(canvas, awayX, awayY);
    await sleep(400);
    await client.waitForRenderIdle();
    const afterClickPng = join(dir, "after-click.png");
    if (!captureWindowToPng(canvas, afterClickPng)) {
      throw new Error("issue-5933: capture after click failed");
    }

    sendMessage(frame, WM_KEYDOWN, VK_ESCAPE, 0);
    await sleep(200);
    await client.waitForRenderIdle();
    const afterEscPng = join(dir, "after-esc.png");
    if (!captureWindowToPng(canvas, afterEscPng)) {
      throw new Error("issue-5933: capture after Esc failed");
    }

    const selected = readFileSync(selectedPng);
    const afterClick = readFileSync(afterClickPng);
    const afterEsc = readFileSync(afterEscPng);
    if (selected.equals(afterClick)) {
      throw new Error("issue-5933: click away did not leave stamp size-edit mode");
    }
    if (!afterClick.equals(afterEsc)) {
      throw new Error("issue-5933: click away left a different selection than Esc");
    }

    sendMessage(frame, WM_COMMAND, cmdId("CmdCreateAnnotStamp"), packCoords(stampX, stampY));
    await sleep(400);
    await client.waitForRenderIdle();
    const selected2Png = join(dir, "selected2.png");
    if (!captureWindowToPng(canvas, selected2Png)) {
      throw new Error("issue-5933: capture selected2 failed");
    }
    clickAwayWithJitter(canvas, awayX, awayY);
    await sleep(400);
    await client.waitForRenderIdle();
    const afterJitterPng = join(dir, "after-jitter.png");
    if (!captureWindowToPng(canvas, afterJitterPng)) {
      throw new Error("issue-5933: capture after jitter click failed");
    }
    sendMessage(frame, WM_KEYDOWN, VK_ESCAPE, 0);
    await sleep(200);
    await client.waitForRenderIdle();
    const afterEsc2Png = join(dir, "after-esc2.png");
    if (!captureWindowToPng(canvas, afterEsc2Png)) {
      throw new Error("issue-5933: capture after Esc 2 failed");
    }
    const selected2 = readFileSync(selected2Png);
    const afterJitter = readFileSync(afterJitterPng);
    const afterEsc2 = readFileSync(afterEsc2Png);
    if (selected2.equals(afterJitter)) {
      throw new Error("issue-5933: jittered click away did not leave stamp size-edit mode");
    }
    if (!afterJitter.equals(afterEsc2)) {
      throw new Error("issue-5933: jittered click away left a different selection than Esc");
    }

    // Creating an annotation from the context menu used to leave the stale
    // right-drag flag set. A later left-button resize then ignored button-up
    // and continued resizing as the unpressed mouse moved.
    primeRightDragState(canvas, awayX, awayY);
    const freeTextX = 100;
    const freeTextY = 300;
    sendMessage(frame, WM_COMMAND, cmdId("CmdCreateAnnotFreeText"), packCoords(freeTextX, freeTextY));
    await sleep(400);
    await client.waitForRenderIdle();

    // At fit-page zoom the default FreeText rectangle's bottom-right handle
    // is 212x109 pixels from its placement point.
    const resizeX = freeTextX + 212;
    const resizeY = freeTextY + 109;
    const resizedX = resizeX + 40;
    const resizedY = resizeY + 40;
    const pResize = clientToScreen(canvas, resizeX, resizeY);
    const pResized = clientToScreen(canvas, resizedX, resizedY);
    setCursorPos(pResize.x, pResize.y);
    sendMessage(canvas, WM_LBUTTONDOWN, MK_LBUTTON, packCoords(resizeX, resizeY));
    setCursorPos(pResized.x, pResized.y);
    sendMessage(canvas, WM_MOUSEMOVE, MK_LBUTTON, packCoords(resizedX, resizedY));
    sendMessage(canvas, WM_LBUTTONUP, 0, packCoords(resizedX, resizedY));
    await sleep(300);
    await client.waitForRenderIdle();
    const afterResizeUpPng = join(dir, "after-resize-up.png");
    if (!captureWindowToPng(canvas, afterResizeUpPng)) {
      throw new Error("issue-5933: capture after resize mouse-up failed");
    }

    sendMessage(canvas, WM_MOUSEMOVE, 0, packCoords(resizedX + 60, resizedY + 60));
    await sleep(300);
    await client.waitForRenderIdle();
    const afterUnpressedMovePng = join(dir, "after-unpressed-move.png");
    if (!captureWindowToPng(canvas, afterUnpressedMovePng)) {
      throw new Error("issue-5933: capture after unpressed mouse move failed");
    }
    const afterResizeUp = readFileSync(afterResizeUpPng);
    const afterUnpressedMove = readFileSync(afterUnpressedMovePng);
    if (!afterResizeUp.equals(afterUnpressedMove)) {
      throw new Error("issue-5933: annotation kept resizing after the left mouse button was released");
    }

    sendMessage(frame, WM_COMMAND, cmdId("CmdCreateAnnotCaret"), packCoords(100, 200));
    const caret = await selectedAnnotState(client);
    if (caret.canResize) {
      throw new Error(`issue-5933: fixed-size caret has resize handles: ${caret.raw}`);
    }
    sendMessage(frame, WM_COMMAND, cmdId("CmdCreateAnnotFileAttachment"), packCoords(100, 240));
    const attachment = await selectedAnnotState(client);
    if (attachment.canResize) {
      throw new Error(`issue-5933: fixed-size file attachment has resize handles: ${attachment.raw}`);
    }
  } finally {
    client.close();
    await killAndWait(proc);
  }
  console.log("issue-5933: OK");
}

if (import.meta.main) {
  await runStandalone(testit);
}
