// Test for https://github.com/sumatrapdfreader/sumatrapdf/issues/1809
//
// A PDF with no page fill (transparent) and a white rectangle is invisible
// on Sumatra's white paper. CmdToggleTransparencyGrid paints a checkerboard
// under the page so the white box and the holes show up, like Acrobat.
// Session-only; not saved in settings.
//
// The fixture is tests/issue-1809.pdf (white box + blue box + black text,
// no page background). Regenerated by this file when run as main.
//
// Run: bun tests/issue-1809.ts [--no-build]   (or via tests/run-almost-all.ts)

import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { withControlledSumatra } from "./control.ts";
import { EXE, ROOT, cmdId, runStandalone, assemblePdf } from "./util.ts";
import { captureWindowPixels } from "./winapi.ts";
import { findCanvas, sendCommand, waitForFrame } from "./win-automation.ts";

const PDF = join(ROOT, "tests", "issue-1809.pdf");

// No page fill. White rect (invisible on white paper), blue rect, black text.
export function makeTransparentPdf(): string {
  const stream = [
    "1 1 1 rg",
    "40 40 160 100 re f",
    "0 0 0 RG",
    "1.5 w",
    "40 40 160 100 re S",
    "0 0.45 0.85 rg",
    "220 40 80 80 re f",
    "0 0 0 rg",
    "BT /F1 18 Tf 40 220 Td (White on transparent) Tj ET",
  ].join("\n");
  const objs = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Count 1 /Kids [3 0 R] >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 400 300] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  return assemblePdf(objs);
}

function countCheckerGray(data: Uint8Array): number {
  let n = 0;
  for (let i = 0; i < data.length; i += 4) {
    const b = data[i]!;
    const g = data[i + 1]!;
    const r = data[i + 2]!;
    // HdcPaintCheckerboard dark cell is 204,204,204
    if (Math.abs(r - 204) <= 8 && Math.abs(g - 204) <= 8 && Math.abs(b - 204) <= 8) {
      n++;
    }
  }
  return n;
}

export async function testit(): Promise<void> {
  if (!existsSync(PDF)) {
    writeFileSync(PDF, makeTransparentPdf());
  }

  await withControlledSumatra(
    EXE,
    async (client, proc) => {
      const frame = await waitForFrame(proc.pid!);
      await client.waitForRenderIdle(30000);
      await client.setNotificationsEnabled(false);
      const canvas = findCanvas(frame);
      if (!canvas) {
        throw new Error("issue-1809: no canvas");
      }
      const before = captureWindowPixels(canvas);
      if (!before) {
        throw new Error("issue-1809: capture failed");
      }
      const grayBefore = countCheckerGray(before.data);

      sendCommand(frame, cmdId("CmdToggleTransparencyGrid"));
      await client.waitForRenderIdle(30000);
      const after = captureWindowPixels(canvas);
      if (!after) {
        throw new Error("issue-1809: capture after toggle failed");
      }
      const grayAfter = countCheckerGray(after.data);
      if (grayAfter < grayBefore + 200) {
        throw new Error(
          `issue-1809: transparency grid did not show checkerboard (gray before=${grayBefore} after=${grayAfter})`,
        );
      }
      console.log(`  checker gray pixels ${grayBefore} -> ${grayAfter} ✓`);
    },
    [PDF],
  );
}

if (import.meta.main) {
  writeFileSync(PDF, makeTransparentPdf());
  const bugs = "C:\\Users\\kjk\\OneDrive\\!sumatra\\bugs\\bug-1809.pdf";
  try {
    writeFileSync(bugs, makeTransparentPdf());
    console.log(`wrote ${PDF} and ${bugs}`);
  } catch {
    console.log(`wrote ${PDF}`);
  }
  await runStandalone(testit);
}
