#!/usr/bin/env python

from hb_test_tools import *
import sys, os

if len (sys.argv) < 2:
	print "usage: %s FILES..." % sys.argv[0]
	sys.exit (1)

ZipDiffer.diff_files (FileHelpers.open_file_or_stdin (f) for f in sys.argv[1:])
