-- test gdiplus.lua
require'setupluafiles'
local winapi = require'winapi'
require'gdiplus'
local ffi = require'ffi'
local C = ffi.C

print(winapi.FlatnessDefault)
assert(C.FillModeAlternate == 0)
assert(C.QualityModeInvalid == -1)
assert(C.CompositingModeSourceOver == 0)
assert(C.CompositingQualityInvalid == -1)
assert(C.UnitWorld == 0)
assert(C.MetafileFrameUnitPixel == 2)
assert(C.CoordinateSpaceWorld == 0)
assert(C.WrapModeTile == 0)
assert(C.HatchStyleSolidDiamond == 52)
assert(C.DashStyleCustom == 5)
assert(C.DashCapTriangle == 3)
assert(C.LineCapArrowAnchor == 0x14)
assert(C.CustomLineCapTypeAdjustableArrow == 1)
assert(C.LineJoinRound == 2)
assert(C.PathPointTypeDashMode == 0x10)
assert(C.WarpModeBilinear == 1)
assert(C.LinearGradientModeForwardDiagonal == 2)
assert(C.CombineModeExclude == 4)
assert(C.ImageTypeMetafile == 2)
assert(C.InterpolationModeInvalid == -1)
assert(C.PenAlignmentInset == 1)
assert(C.BrushTypeLinearGradient == 4)
assert(C.PenTypeSolidColor == 0)
assert(C.MatrixOrderPrepend == 0)
assert(C.GenericFontFamilyMonospace == 2)
assert(C.FontStyleStrikeout == 8)
assert(C.SmoothingModeInvalid == -1)
assert(C.PixelOffsetModeInvalid == -1)
assert(C.TextRenderingHintClearTypeGridFit == 5)
assert(C.MetafileTypeEmfPlusDual == 5)
assert(C.EmfTypeEmfOnly == 3)
assert(C.ObjectTypeCustomLineCap == 9)
-- assert(C.GDIP_EMFPLUS_RECORD_BASE == 0x4000)
assert(C.StringFormatFlagsLineLimit == 0x2000)
assert(C.StringTrimmingEllipsisPath == 5)
assert(C.StringDigitSubstituteTraditional == 3)
assert(C.HotkeyPrefixHide == 2)
assert(C.StringAlignmentFar == 2)
assert(C.DriverStringOptionsLimitSubpixel == 8)
assert(C.FlushIntentionSync == 1)
assert(C.EncoderParameterValueTypeRationalRange == 8)
assert(C.EncoderValueCompressionLZW == 2)
assert(C.EmfToWmfBitsFlagsNoXORClip == 4)
--assert(C.ConvertToEmfPlusFlagsRopUsed == 1)
assert(C.TestControlGetBuildNumber == 2)
