#ifndef OPJ_COMMON_H
#define OPJ_COMMON_H

#define OPJ_COMMON_CBLK_DATA_EXTRA        2

#define OPJ_COMP_PARAM_DEFAULT_CBLOCKW        64
#define OPJ_COMP_PARAM_DEFAULT_CBLOCKH        64
#define OPJ_COMP_PARAM_DEFAULT_PROG_ORDER     OPJ_LRCP
#define OPJ_COMP_PARAM_DEFAULT_NUMRESOLUTION  6

#endif
