Arrays.lo Arrays.o: Arrays.cpp ../config.h Arrays.h GException.h DjVuGlobal.h \
  GSmartPointer.h atomic.h ByteStream.h
atomic.lo atomic.o: atomic.cpp ../config.h atomic.h GThreads.h DjVuGlobal.h \
  GException.h
BSByteStream.lo BSByteStream.o: BSByteStream.cpp ../config.h BSByteStream.h ByteStream.h \
  Arrays.h GException.h DjVuGlobal.h GSmartPointer.h atomic.h ZPCodec.h \
  GContainer.h
BSEncodeByteStream.lo BSEncodeByteStream.o: BSEncodeByteStream.cpp ../config.h BSByteStream.h \
  ByteStream.h Arrays.h GException.h DjVuGlobal.h GSmartPointer.h \
  atomic.h ZPCodec.h GContainer.h GString.h
ByteStream.lo ByteStream.o: ByteStream.cpp ../config.h DjVuGlobal.h ByteStream.h \
  Arrays.h GException.h GSmartPointer.h atomic.h GOS.h GString.h \
  GContainer.h GURL.h GThreads.h DjVuMessage.h DjVuMessageLite.h
DataPool.lo DataPool.o: DataPool.cpp ../config.h DataPool.h GThreads.h DjVuGlobal.h \
  GException.h GString.h GContainer.h GSmartPointer.h atomic.h GURL.h \
  Arrays.h IFFByteStream.h ByteStream.h GOS.h debug.h
ddjvuapi.lo ddjvuapi.o: ddjvuapi.cpp ../config.h GException.h DjVuGlobal.h \
  GSmartPointer.h atomic.h GThreads.h GContainer.h ByteStream.h Arrays.h \
  IFFByteStream.h GString.h BSByteStream.h ZPCodec.h GBitmap.h GPixmap.h \
  GScaler.h GRect.h DjVuPort.h GURL.h DataPool.h DjVuInfo.h IW44Image.h \
  DjVuImage.h DjVuFile.h DjVuPalette.h DjVuAnno.h DjVuFileCache.h \
  DjVuDocument.h DjVuDumpHelper.h DjVuMessageLite.h DjVuMessage.h \
  DjVmNav.h DjVuText.h GMapAreas.h DjVuToPS.h DjVmDir.h DjVmDir0.h \
  DjVuNavDir.h DjVmDoc.h miniexp.h ddjvuapi.h
debug.lo debug.o: debug.cpp ../config.h debug.h
DjVmDir0.lo DjVmDir0.o: DjVmDir0.cpp ../config.h DjVmDir0.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h atomic.h ByteStream.h \
  Arrays.h debug.h
DjVmDir.lo DjVmDir.o: DjVmDir.cpp ../config.h DjVmDir.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h atomic.h GThreads.h \
  BSByteStream.h ByteStream.h Arrays.h ZPCodec.h GURL.h debug.h
DjVmDoc.lo DjVmDoc.o: DjVmDoc.cpp ../config.h DjVmDoc.h DjVmDir.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h atomic.h \
  GThreads.h DjVmNav.h DataPool.h GURL.h Arrays.h IFFByteStream.h \
  ByteStream.h GOS.h debug.h
DjVmNav.lo DjVmNav.o: DjVmNav.cpp ../config.h DjVuDocument.h DjVuPort.h GThreads.h \
  DjVuGlobal.h GException.h GURL.h GString.h GContainer.h GSmartPointer.h \
  atomic.h Arrays.h DjVmNav.h BSByteStream.h ByteStream.h ZPCodec.h \
  debug.h
DjVuAnno.lo DjVuAnno.o: DjVuAnno.cpp ../config.h DjVuAnno.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h atomic.h IFFByteStream.h \
  ByteStream.h Arrays.h BSByteStream.h ZPCodec.h GMapAreas.h GRect.h \
  GURL.h GThreads.h debug.h
DjVuDocEditor.lo DjVuDocEditor.o: DjVuDocEditor.cpp ../config.h DjVuDocEditor.h \
  DjVuDocument.h DjVuPort.h GThreads.h DjVuGlobal.h GException.h GURL.h \
  GString.h GContainer.h GSmartPointer.h atomic.h Arrays.h DjVmDoc.h \
  DjVmDir.h DjVuImage.h DjVuFile.h DjVuInfo.h GRect.h DjVuPalette.h \
  GPixmap.h DjVuAnno.h IFFByteStream.h ByteStream.h DataPool.h \
  IW44Image.h ZPCodec.h GOS.h DjVmNav.h debug.h
DjVuDocument.lo DjVuDocument.o: DjVuDocument.cpp ../config.h DjVuDocument.h DjVuPort.h \
  GThreads.h DjVuGlobal.h GException.h GURL.h GString.h GContainer.h \
  GSmartPointer.h atomic.h Arrays.h DjVmDoc.h DjVmDir.h DjVmDir0.h \
  DjVmNav.h DjVuNavDir.h DjVuImage.h DjVuFile.h DjVuInfo.h GRect.h \
  DjVuPalette.h GPixmap.h DjVuAnno.h DjVuFileCache.h IFFByteStream.h \
  ByteStream.h GOS.h DataPool.h IW44Image.h ZPCodec.h debug.h
DjVuDumpHelper.lo DjVuDumpHelper.o: DjVuDumpHelper.cpp ../config.h DjVuDumpHelper.h \
  GSmartPointer.h DjVuGlobal.h atomic.h DataPool.h GThreads.h \
  GException.h GString.h GContainer.h GURL.h Arrays.h DjVmDir.h \
  DjVuInfo.h GRect.h IFFByteStream.h ByteStream.h
DjVuErrorList.lo DjVuErrorList.o: DjVuErrorList.cpp ../config.h DjVuErrorList.h DjVuPort.h \
  GThreads.h DjVuGlobal.h GException.h GURL.h GString.h GContainer.h \
  GSmartPointer.h atomic.h Arrays.h DjVmDoc.h DjVmDir.h GOS.h DataPool.h
DjVuFileCache.lo DjVuFileCache.o: DjVuFileCache.cpp ../config.h DjVuFileCache.h DjVuFile.h \
  DjVuInfo.h GSmartPointer.h DjVuGlobal.h atomic.h GRect.h DjVuPalette.h \
  GContainer.h GException.h GPixmap.h DjVuPort.h GThreads.h GURL.h \
  GString.h Arrays.h debug.h
DjVuFile.lo DjVuFile.o: DjVuFile.cpp ../config.h DjVuFile.h DjVuInfo.h \
  GSmartPointer.h DjVuGlobal.h atomic.h GRect.h DjVuPalette.h \
  GContainer.h GException.h GPixmap.h DjVuPort.h GThreads.h GURL.h \
  GString.h Arrays.h IFFByteStream.h ByteStream.h GOS.h MMRDecoder.h \
  JPEGDecoder.h DjVuAnno.h DjVuText.h GMapAreas.h DataPool.h JB2Image.h \
  ZPCodec.h IW44Image.h DjVuNavDir.h BSByteStream.h debug.h
DjVuGlobal.lo DjVuGlobal.o: DjVuGlobal.cpp ../config.h
DjVuGlobalMemory.lo DjVuGlobalMemory.o: DjVuGlobalMemory.cpp ../config.h
DjVuImage.lo DjVuImage.o: DjVuImage.cpp ../config.h DjVuImage.h DjVuFile.h DjVuInfo.h \
  GSmartPointer.h DjVuGlobal.h atomic.h GRect.h DjVuPalette.h \
  GContainer.h GException.h GPixmap.h DjVuPort.h GThreads.h GURL.h \
  GString.h Arrays.h DjVuAnno.h GScaler.h GBitmap.h DjVuDocument.h \
  JB2Image.h ZPCodec.h IW44Image.h DataPool.h ByteStream.h GMapAreas.h \
  DjVuText.h IFFByteStream.h BSByteStream.h debug.h
DjVuInfo.lo DjVuInfo.o: DjVuInfo.cpp ../config.h DjVuInfo.h GSmartPointer.h \
  DjVuGlobal.h atomic.h GRect.h GException.h ByteStream.h Arrays.h \
  GString.h GContainer.h
DjVuMessage.lo DjVuMessage.o: DjVuMessage.cpp ../config.h DjVuMessage.h \
  DjVuMessageLite.h GString.h DjVuGlobal.h GContainer.h GException.h \
  GSmartPointer.h atomic.h GOS.h XMLTags.h ByteStream.h Arrays.h GURL.h \
  GThreads.h debug.h
DjVuMessageLite.lo DjVuMessageLite.o: DjVuMessageLite.cpp ../config.h DjVuMessageLite.h \
  GString.h DjVuGlobal.h GContainer.h GException.h GSmartPointer.h \
  atomic.h GOS.h XMLTags.h ByteStream.h Arrays.h GURL.h GThreads.h \
  debug.h
DjVuNavDir.lo DjVuNavDir.o: DjVuNavDir.cpp ../config.h DjVuNavDir.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h atomic.h \
  GThreads.h GURL.h Arrays.h debug.h GOS.h ByteStream.h
DjVuPalette.lo DjVuPalette.o: DjVuPalette.cpp ../config.h GException.h DjVuGlobal.h \
  ByteStream.h Arrays.h GSmartPointer.h atomic.h BSByteStream.h ZPCodec.h \
  GContainer.h DjVuPalette.h GPixmap.h
DjVuPort.lo DjVuPort.o: DjVuPort.cpp ../config.h DjVuPort.h GThreads.h DjVuGlobal.h \
  GException.h GURL.h GString.h GContainer.h GSmartPointer.h atomic.h \
  Arrays.h GOS.h DjVuImage.h DjVuFile.h DjVuInfo.h GRect.h DjVuPalette.h \
  GPixmap.h DjVuAnno.h DjVuDocument.h DjVuMessageLite.h DataPool.h
DjVuText.lo DjVuText.o: DjVuText.cpp ../config.h DjVuText.h GMapAreas.h \
  GSmartPointer.h DjVuGlobal.h atomic.h GContainer.h GException.h \
  GString.h GRect.h GURL.h Arrays.h GThreads.h IFFByteStream.h \
  ByteStream.h BSByteStream.h ZPCodec.h debug.h
DjVuToPS.lo DjVuToPS.o: DjVuToPS.cpp ../config.h DjVuToPS.h DjVuGlobal.h GRect.h \
  DjVuDocument.h DjVuPort.h GThreads.h GException.h GURL.h GString.h \
  GContainer.h GSmartPointer.h atomic.h Arrays.h DjVuText.h GMapAreas.h \
  IFFByteStream.h ByteStream.h BSByteStream.h ZPCodec.h DjVuImage.h \
  DjVuFile.h DjVuInfo.h DjVuPalette.h GPixmap.h DjVuAnno.h DataPool.h \
  IW44Image.h JB2Image.h GBitmap.h debug.h
GBitmap.lo GBitmap.o: GBitmap.cpp ../config.h GBitmap.h GSmartPointer.h DjVuGlobal.h \
  atomic.h ByteStream.h Arrays.h GException.h GRect.h GString.h \
  GContainer.h GThreads.h
GContainer.lo GContainer.o: GContainer.cpp ../config.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h atomic.h
GException.lo GException.o: GException.cpp ../config.h GException.h DjVuGlobal.h \
  DjVuMessageLite.h GString.h GContainer.h GSmartPointer.h atomic.h \
  debug.h
GIFFManager.lo GIFFManager.o: GIFFManager.cpp ../config.h GIFFManager.h IFFByteStream.h \
  DjVuGlobal.h GException.h GString.h GContainer.h GSmartPointer.h \
  atomic.h ByteStream.h Arrays.h debug.h
GMapAreas.lo GMapAreas.o: GMapAreas.cpp ../config.h GMapAreas.h GSmartPointer.h \
  DjVuGlobal.h atomic.h GContainer.h GException.h GString.h GRect.h \
  GURL.h Arrays.h GThreads.h debug.h
GOS.lo GOS.o: GOS.cpp ../config.h GException.h DjVuGlobal.h GThreads.h GOS.h \
  GString.h GContainer.h GSmartPointer.h atomic.h GURL.h Arrays.h
GPixmap.lo GPixmap.o: GPixmap.cpp ../config.h GPixmap.h GSmartPointer.h DjVuGlobal.h \
  atomic.h GString.h GContainer.h GException.h ByteStream.h Arrays.h \
  GRect.h GBitmap.h GThreads.h JPEGDecoder.h
GRect.lo GRect.o: GRect.cpp ../config.h GRect.h DjVuGlobal.h GException.h
GScaler.lo GScaler.o: GScaler.cpp ../config.h GScaler.h GException.h DjVuGlobal.h \
  GRect.h GBitmap.h GSmartPointer.h atomic.h GPixmap.h
GSmartPointer.lo GSmartPointer.o: GSmartPointer.cpp ../config.h GThreads.h DjVuGlobal.h \
  GException.h GSmartPointer.h atomic.h
GString.lo GString.o: GString.cpp ../config.h GString.h DjVuGlobal.h GContainer.h \
  GException.h GSmartPointer.h atomic.h GThreads.h debug.h
GThreads.lo GThreads.o: GThreads.cpp ../config.h GThreads.h DjVuGlobal.h GException.h \
  DjVuMessageLite.h GString.h GContainer.h GSmartPointer.h atomic.h
GUnicode.lo GUnicode.o: GUnicode.cpp ../config.h GString.h DjVuGlobal.h GContainer.h \
  GException.h GSmartPointer.h atomic.h
GURL.lo GURL.o: GURL.cpp ../config.h GException.h DjVuGlobal.h GOS.h GString.h \
  GContainer.h GSmartPointer.h atomic.h GURL.h Arrays.h GThreads.h \
  debug.h
IFFByteStream.lo IFFByteStream.o: IFFByteStream.cpp ../config.h IFFByteStream.h \
  DjVuGlobal.h GException.h GString.h GContainer.h GSmartPointer.h \
  atomic.h ByteStream.h Arrays.h
IW44EncodeCodec.lo IW44EncodeCodec.o: IW44EncodeCodec.cpp ../config.h IW44Image.h \
  GSmartPointer.h DjVuGlobal.h atomic.h ZPCodec.h GContainer.h \
  GException.h GBitmap.h GPixmap.h IFFByteStream.h GString.h ByteStream.h \
  Arrays.h GRect.h MMX.h
IW44Image.lo IW44Image.o: IW44Image.cpp ../config.h IW44Image.h GSmartPointer.h \
  DjVuGlobal.h atomic.h ZPCodec.h GContainer.h GException.h GBitmap.h \
  GPixmap.h IFFByteStream.h GString.h ByteStream.h Arrays.h GRect.h MMX.h
JB2EncodeCodec.lo JB2EncodeCodec.o: JB2EncodeCodec.cpp ../config.h JB2Image.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h atomic.h \
  ZPCodec.h GBitmap.h
JB2Image.lo JB2Image.o: JB2Image.cpp ../config.h JB2Image.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h atomic.h ZPCodec.h GThreads.h \
  GRect.h GBitmap.h
JPEGDecoder.lo JPEGDecoder.o: JPEGDecoder.cpp ../config.h JPEGDecoder.h GSmartPointer.h \
  DjVuGlobal.h atomic.h ByteStream.h Arrays.h GException.h GPixmap.h
miniexp.lo miniexp.o: miniexp.cpp ../config.h miniexp.h
MMRDecoder.lo MMRDecoder.o: MMRDecoder.cpp ../config.h MMRDecoder.h GSmartPointer.h \
  DjVuGlobal.h atomic.h JB2Image.h GString.h GContainer.h GException.h \
  ZPCodec.h ByteStream.h Arrays.h GBitmap.h
MMX.lo MMX.o: MMX.cpp ../config.h MMX.h DjVuGlobal.h
UnicodeByteStream.lo UnicodeByteStream.o: UnicodeByteStream.cpp ../config.h \
  UnicodeByteStream.h DjVuGlobal.h GString.h GContainer.h GException.h \
  GSmartPointer.h atomic.h ByteStream.h Arrays.h
XMLParser.lo XMLParser.o: XMLParser.cpp ../config.h XMLParser.h GContainer.h \
  GException.h DjVuGlobal.h GSmartPointer.h atomic.h GURL.h GString.h \
  Arrays.h GThreads.h XMLTags.h ByteStream.h GOS.h DjVuDocument.h \
  DjVuPort.h DjVuText.h GMapAreas.h GRect.h DjVuAnno.h DjVuFile.h \
  DjVuInfo.h DjVuPalette.h GPixmap.h DjVuImage.h debug.h
XMLTags.lo XMLTags.o: XMLTags.cpp ../config.h XMLTags.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h atomic.h GString.h UnicodeByteStream.h \
  ByteStream.h Arrays.h
ZPCodec.lo ZPCodec.o: ZPCodec.cpp ../config.h ZPCodec.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h atomic.h ByteStream.h Arrays.h
