; Autogenerated by the Meson build system.
; Do not edit, your changes will be lost.

%define FORCE_VEX_ENCODING 0

%define PIC 1

%define STACK_ALIGNMENT 16

%define private_prefix dav1d

