.\"Shiju P. Nair September 30, 2004
.\"Thomas Weber <tweber@debian.org> April 23, 2014
.TH TRANSICC 1 "MAY 30, 2011"
.SH NAME
transicc - little cms ColorSpace conversion calculator.
.SH SYNOPSIS
.B transicc
.RI [ options ]\ [ CGATSINPUT ]\ [ CGATSOUTPUT ]
.SH DESCRIPTION
lcms is a standalone CMM engine, which deals with the color management.
It implements a fast transformation between ICC profiles.
.B transicc
is a lcms ColorSpace conversion calculator.
.SH OPTIONS
.TP
.B \-b
Black point compensation.
.TP
.BI \-c\  NUM
Precalculates transform (0=Off, 1=Normal, 2=Hi-res, 3=LoRes) [defaults to 1].
.TP
.BI \-d\  NUM
Observer adaptation state (abs.col. only), (0..1.0, float value) [defaults to 0.0].
.TP
.B \-e
Encoded representation of numbers is not float (Option \fB\-w\fR=use 16 bits, Option \fB\-x\fR=hexadecimal).
.TP
.B \-g
Marks out-of-gamut colors on softproof.
.TP
.BI \-i\  profile
Input profile (defaults to sRGB).
.TP
.B \-l
Transform by device-link profile.
.TP
.BI \-m\  NUM
SoftProof intent (0,1,2,3) [defaults to 0].
.TP
.B \-n
Terse output, intended for pipe usage.
.TP
.BI \-o\  profile
.p
Output profile (defaults to sRGB).
.TP
.B \-q
Quantize CGATS to 8 bits.
.TP
.BI \-s
Bounded mode.
.TP
.BI \-t\ NUM
Rendering intent
.nf
.RS
0=Perceptual [default]
1=Relative colorimetric
2=Saturation
3=Absolute colorimetric
10=Perceptual preserving black ink
11=Relative colorimetric preserving black ink
12=Saturation preserving black ink
13=Perceptual preserving black plane
14=Relative colorimetric preserving black plane
15=Saturation preserving black plane
.RE
.fi
.TP
.BI \-v\  verbosity
Verbosity level, (0=None, 1=Normal, 2=High, 3=Very High) [defaults to 1].
.TP
.B \-w
Use 16 bits.
.TP
.B \-x
Hexadecimal.
.TP
You can use '*Lab' and '*xyz' as built-in profiles.
.SH NOTES
For suggestions, comments, bug reports etc. send mail to
info@littlecms.com.
.SH SEE ALSO
.BR jpgicc (1),
.BR linkicc (1),
.BR psicc (1),
.BR tificc (1)
.SH AUTHOR
This manual page was written by Shiju p. Nair <shiju.p@gmail.com>,
for the Debian project.
