/* Copyright 2022 the SumatraPDF project authors (see AUTHORS file).
   License: GPLv3 */

/* Reader for Microsoft Reader .lit ebooks: parses the ITOLITLS container,
   unseals the DRM1 ("sealed") encryption present in every .lit, decompresses
   the LZX sections, reconstructs HTML / OPF from their tokenized binary form
   and repackages everything as an in-memory epub, which EngineMupdf renders.

   The format understanding comes from ConvertLIT and calibre's lit reader
   (src/calibre/ebooks/lit/reader.py); the tag code tables below are generated
   from calibre's maps by cmd/gen-litdoc.ts. DRM5 (books locked to a Microsoft
   Passport account) is not supported. */

#include "base/Base.h"
#include "base/ByteReaderWriter.h"
#include "base/File.h"
#include "base/GuessFileType.h"
#include "base/Zip.h"

#include "gui/UIModels.h"
#include "EngineBase.h"
#include "EngineAll.h"

extern "C" {
// public domain d3des, in ext/msdes
#include <d3des.h>

// the LZX decompressor inside ext/chmdec/chm.c
struct LZXstate;
struct LZXstate* LZXinit(int window);
void LZXteardown(struct LZXstate* pState);
int LZXreset(struct LZXstate* pState);
int LZXdecompress(struct LZXstate* pState, u8* inpos, u8* outpos, int inlen, int outlen);
}

#include "LitDoc.h"
#include "SumatraLog.h"

//--- Microsoft LIT tag / attribute code tables, for reconstructing HTML and
// OPF from their tokenized binary form. The data comes from calibre's
// src/calibre/ebooks/lit/maps/{html,opf}.py (themselves copied from
// ConvertLIT). Generated by `bun cmd/gen-litdoc.ts`; do not edit by hand.

// @gen-start litdoc-maps
// clang-format off
// tag code -> name, indexed by the code; "\x01" marks a code with no tag
static SeqStrings gLitHtmlTags =
    "\x01\0" "\x01\0" "\x01\0" "a\0" "acronym\0" "address\0" "applet\0" "area\0" "b\0" "base\0" "basefont\0" "bdo\0"
    "bgsound\0" "big\0" "blink\0" "blockquote\0" "body\0" "br\0" "button\0" "caption\0" "center\0" "cite\0" "code\0"
    "col\0" "colgroup\0" "\x01\0" "\x01\0" "dd\0" "del\0" "dfn\0" "dir\0" "div\0" "dl\0" "dt\0" "em\0" "embed\0"
    "fieldset\0" "font\0" "form\0" "frame\0" "frameset\0" "\x01\0" "h1\0" "h2\0" "h3\0" "h4\0" "h5\0" "h6\0" "head\0"
    "hr\0" "html\0" "i\0" "iframe\0" "img\0" "input\0" "ins\0" "kbd\0" "label\0" "legend\0" "li\0" "link\0" "tag61\0"
    "map\0" "tag63\0" "tag64\0" "meta\0" "nextid\0" "nobr\0" "noembed\0" "noframes\0" "noscript\0" "object\0" "ol\0"
    "option\0" "p\0" "param\0" "plaintext\0" "pre\0" "q\0" "rp\0" "rt\0" "ruby\0" "s\0" "samp\0" "script\0" "select\0"
    "small\0" "span\0" "strike\0" "strong\0" "style\0" "sub\0" "sup\0" "table\0" "tbody\0" "tc\0" "td\0" "textarea\0"
    "tfoot\0" "th\0" "thead\0" "title\0" "tr\0" "tt\0" "u\0" "ul\0" "var\0" "wbr\0" "\x01\0" "\0";

static SeqStrings gLitOpfTags =
    "\x01\0" "package\0" "dc:Title\0" "dc:Creator\0" "\x01\0" "\x01\0" "\x01\0" "\x01\0" "\x01\0" "\x01\0" "\x01\0"
    "\x01\0" "\x01\0" "\x01\0" "\x01\0" "\x01\0" "manifest\0" "item\0" "spine\0" "itemref\0" "metadata\0"
    "dc-metadata\0" "dc:Subject\0" "dc:Description\0" "dc:Publisher\0" "dc:Contributor\0" "dc:Date\0" "dc:Type\0"
    "dc:Format\0" "dc:Identifier\0" "dc:Source\0" "dc:Language\0" "dc:Relation\0" "dc:Coverage\0" "dc:Rights\0"
    "x-metadata\0" "meta\0" "tours\0" "tour\0" "site\0" "guide\0" "reference\0" "\x01\0" "\0";

// Every attribute list packed into two parallel arrays: entry i pairs the
// code gLitAttrCodes[i] with the i-th string of gLitAttrNames. Identical
// lists are stored once and shared.
static SeqStrings gLitAttrNames =
    "href\0" "target\0" "rel\0" "rev\0" "urn\0" "methods\0" "name\0" "title\0" "style\0" "class\0" "id\0" "clear\0"
    "name\0" "width\0" "height\0" "align\0" "classid\0" "data\0" "codebase\0" "codetype\0" "code\0" "type\0"
    "vspace\0" "hspace\0" "onerror\0" "href\0" "shape\0" "coords\0" "target\0" "alt\0" "nohref\0" "title\0" "style\0"
    "class\0" "id\0" "title\0" "style\0" "class\0" "id\0" "href\0" "target\0" "color\0" "face\0" "size\0" "src\0"
    "loop\0" "volume\0" "balance\0" "title\0" "style\0" "class\0" "id\0" "clear\0" "link\0" "alink\0" "vlink\0"
    "title\0" "style\0" "class\0" "id\0" "background\0" "text\0" "nowrap\0" "topmargin\0" "rightmargin\0"
    "bottommargin\0" "leftmargin\0" "bgproperties\0" "scroll\0" "onselect\0" "onload\0" "onunload\0"
    "onbeforeunload\0" "onbeforeprint\0" "onafterprint\0" "bgcolor\0" "type\0" "name\0" "title\0" "align\0" "style\0"
    "class\0" "id\0" "valign\0" "span\0" "width\0" "align\0" "valign\0" "bgcolor\0" "title\0" "style\0" "class\0"
    "id\0" "nowrap\0" "title\0" "align\0" "style\0" "class\0" "id\0" "nowrap\0" "compact\0" "title\0" "style\0"
    "class\0" "id\0" "name\0" "width\0" "height\0" "align\0" "palette\0" "pluginspage\0" "src\0" "units\0" "type\0"
    "hidden\0" "align\0" "title\0" "style\0" "class\0" "id\0" "color\0" "face\0" "size\0" "action\0" "enctype\0"
    "method\0" "target\0" "accept-charset\0" "name\0" "onsubmit\0" "onreset\0" "align\0" "name\0" "src\0" "border\0"
    "frameborder\0" "framespacing\0" "marginwidth\0" "marginheight\0" "noresize\0" "scrolling\0" "bordercolor\0"
    "rows\0" "cols\0" "border\0" "bordercolor\0" "frameborder\0" "framespacing\0" "name\0" "onload\0" "onunload\0"
    "onbeforeunload\0" "onbeforeprint\0" "onafterprint\0" "title\0" "align\0" "style\0" "class\0" "id\0" "clear\0"
    "noshade\0" "width\0" "size\0" "title\0" "align\0" "style\0" "class\0" "id\0" "color\0" "name\0" "width\0"
    "height\0" "align\0" "src\0" "border\0" "frameborder\0" "framespacing\0" "marginwidth\0" "marginheight\0"
    "noresize\0" "scrolling\0" "vspace\0" "hspace\0" "alt\0" "src\0" "border\0" "vspace\0" "hspace\0" "lowsrc\0"
    "vrml\0" "dynsrc\0" "loop\0" "start\0" "ismap\0" "usemap\0" "name\0" "width\0" "height\0" "title\0" "align\0"
    "style\0" "class\0" "id\0" "onabort\0" "onerror\0" "onload\0" "type\0" "size\0" "maxlength\0" "readonly\0"
    "indeterminate\0" "checked\0" "alt\0" "src\0" "border\0" "vspace\0" "hspace\0" "lowsrc\0" "vrml\0" "dynsrc\0"
    "loop\0" "start\0" "name\0" "width\0" "height\0" "align\0" "value\0" "onselect\0" "onabort\0" "onerror\0"
    "onchange\0" "onload\0" "for\0" "value\0" "title\0" "style\0" "class\0" "id\0" "type\0" "href\0" "rel\0" "rev\0"
    "type\0" "media\0" "target\0" "title\0" "style\0" "class\0" "id\0" "onerror\0" "onload\0" "name\0" "title\0"
    "style\0" "class\0" "id\0" "scrolldelay\0" "direction\0" "behavior\0" "scrollamount\0" "loop\0" "vspace\0"
    "hspace\0" "truespeed\0" "width\0" "height\0" "onbounce\0" "onfinish\0" "onstart\0" "bgcolor\0" "http-equiv\0"
    "content\0" "url\0" "charset\0" "name\0" "n\0" "usemap\0" "name\0" "width\0" "height\0" "title\0" "align\0"
    "style\0" "class\0" "id\0" "classid\0" "data\0" "codebase\0" "codetype\0" "code\0" "type\0" "vspace\0" "hspace\0"
    "onerror\0" "compact\0" "start\0" "title\0" "style\0" "class\0" "id\0" "type\0" "selected\0" "value\0" "type\0"
    "src\0" "for\0" "event\0" "defer\0" "type\0" "onerror\0" "size\0" "multiple\0" "align\0" "name\0" "onchange\0"
    "type\0" "media\0" "title\0" "onerror\0" "onload\0" "cols\0" "border\0" "rules\0" "frame\0" "cellspacing\0"
    "cellpadding\0" "datapagesize\0" "width\0" "height\0" "title\0" "align\0" "style\0" "class\0" "id\0"
    "background\0" "bordercolor\0" "bordercolorlight\0" "bordercolordark\0" "bgcolor\0" "align\0" "valign\0"
    "bgcolor\0" "align\0" "valign\0" "rowspan\0" "colspan\0" "width\0" "height\0" "title\0" "align\0" "style\0"
    "class\0" "id\0" "background\0" "nowrap\0" "bordercolor\0" "bordercolorlight\0" "bordercolordark\0" "valign\0"
    "bgcolor\0" "rows\0" "cols\0" "wrap\0" "readonly\0" "name\0" "onselect\0" "onchange\0" "height\0" "title\0"
    "align\0" "style\0" "class\0" "id\0" "bordercolor\0" "bordercolorlight\0" "bordercolordark\0" "valign\0"
    "bgcolor\0" "compact\0" "title\0" "style\0" "class\0" "id\0" "type\0" "tabindex\0" "title\0" "style\0"
    "disabled\0" "class\0" "id\0" "datafld\0" "datasrc\0" "dataformatas\0" "accesskey\0" "lang\0" "language\0" "dir\0"
    "onmouseover\0" "onmouseout\0" "onmousedown\0" "onmouseup\0" "onmousemove\0" "onkeydown\0" "onkeyup\0"
    "onkeypress\0" "onclick\0" "ondblclick\0" "onhelp\0" "onfocus\0" "onblur\0" "onrowexit\0" "onrowenter\0"
    "onbeforeupdate\0" "onafterupdate\0" "onreadystatechange\0" "onscroll\0" "ondragstart\0" "onresize\0"
    "onselectstart\0" "onerrorupdate\0" "ondatasetchanged\0" "ondataavailable\0" "ondatasetcomplete\0"
    "onfilterchange\0" "onlosecapture\0" "onpropertychange\0" "ondrag\0" "ondragend\0" "ondragenter\0" "ondragover\0"
    "ondragleave\0" "ondrop\0" "oncut\0" "oncopy\0" "onpaste\0" "onbeforecut\0" "onbeforecopy\0" "onbeforepaste\0"
    "onrowsdelete\0" "onrowsinserted\0" "oncellchange\0" "oncontextmenu\0" "onbeforeeditfocus\0" "href\0"
    "%never-used\0" "%guid\0" "%minimum_level\0" "%attr5\0" "id\0" "href\0" "media-type\0" "fallback\0" "idref\0"
    "xmlns:dc\0" "xmlns:oebpackage\0" "role\0" "file-as\0" "event\0" "scheme\0" "title\0" "type\0"
    "unique-identifier\0" "name\0" "content\0" "xml:lang\0" "\0";

static const u16 gLitAttrCodes[465] = {
    0x1, 0x3ec, 0x3ee, 0x3ef, 0x3f0, 0x3f1, 0x8001, 0x8046, 0x804b, 0x83ea, 0x83eb, 0x9399, 0x8001, 0x8006, 0x8007,
    0x804a, 0x8bbb, 0x8bbc, 0x8bbf, 0x8bc0, 0x8bc1, 0x8bc2, 0x8bc5, 0x8bc6, 0x978e, 0x1, 0x3ea, 0x3eb, 0x3ed, 0x3ee,
    0x3ef, 0x8046, 0x804b, 0x83ea, 0x83eb, 0x8046, 0x804b, 0x83ea, 0x83eb, 0x3ec, 0x3ed, 0x938b, 0x939b, 0x93a3,
    0x3ea, 0x3eb, 0x3ec, 0x3ed, 0x8046, 0x804b, 0x83ea, 0x83eb, 0x9399, 0x7db, 0x7dc, 0x7dd, 0x8046, 0x804b, 0x83ea,
    0x83eb, 0x938a, 0x938b, 0x938e, 0x93ae, 0x93af, 0x93b0, 0x93b1, 0x93b6, 0x93d8, 0x977b, 0x9791, 0x9792, 0x9798,
    0x97b3, 0x97b4, 0xfe0c, 0x7d1, 0x8001, 0x8046, 0x8049, 0x804b, 0x83ea, 0x83eb, 0x93a8, 0x3ea, 0x8006, 0x8049,
    0x93a8, 0xfe0c, 0x8046, 0x804b, 0x83ea, 0x83eb, 0x938e, 0x8046, 0x8049, 0x804b, 0x83ea, 0x83eb, 0x938e, 0x3ea,
    0x8046, 0x804b, 0x83ea, 0x83eb, 0x8001, 0x8006, 0x8007, 0x804a, 0x8bbd, 0x8bbe, 0x8bbf, 0x8bc1, 0x8bc2, 0x8bc3,
    0x804a, 0x8046, 0x804b, 0x83ea, 0x83eb, 0x938b, 0x939b, 0x939c, 0x3ea, 0x3ec, 0x3ed, 0x3ef, 0x3f4, 0x8001, 0x977c,
    0x977d, 0x8000, 0x8001, 0x8bb9, 0x8bbb, 0x8bbc, 0x8bbd, 0x8bbe, 0x8bbf, 0x8bc0, 0x8bc1, 0x8fa2, 0x3e9, 0x3ea,
    0x3eb, 0x3ec, 0x3ed, 0x3ee, 0x8001, 0x9791, 0x9792, 0x9798, 0x97b3, 0x97b4, 0x8046, 0x8049, 0x804b, 0x83ea,
    0x83eb, 0x9399, 0x3ea, 0x8006, 0x8007, 0x8046, 0x8049, 0x804b, 0x83ea, 0x83eb, 0x938b, 0x8001, 0x8006, 0x8007,
    0x804a, 0x8bb9, 0x8bbb, 0x8bbc, 0x8bbd, 0x8bbe, 0x8bbf, 0x8bc0, 0x8bc1, 0x8fa2, 0x8fa3, 0x3eb, 0x3ec, 0x3ed,
    0x3ee, 0x3ef, 0x3f0, 0x3f1, 0x3f2, 0x3f4, 0x3f6, 0x7d3, 0x7d9, 0x8001, 0x8006, 0x8007, 0x8046, 0x804a, 0x804b,
    0x83ea, 0x83eb, 0x978d, 0x978e, 0x9791, 0x7d1, 0x7d3, 0x7d4, 0x7d6, 0x7d8, 0x7da, 0x7db, 0x7dc, 0x7dd, 0x7de,
    0x7df, 0x7e0, 0x7e1, 0x7e2, 0x7e4, 0x7e5, 0x8001, 0x8006, 0x8007, 0x804a, 0x93ee, 0x977b, 0x978d, 0x978e, 0x978f,
    0x9791, 0x3e9, 0x3ea, 0x8046, 0x804b, 0x83ea, 0x83eb, 0x939a, 0x3ee, 0x3ef, 0x3f0, 0x3f1, 0x3f9, 0x3fa, 0x8046,
    0x804b, 0x83ea, 0x83eb, 0x978e, 0x9791, 0x8001, 0x8046, 0x804b, 0x83ea, 0x83eb, 0x1771, 0x1772, 0x1773, 0x1774,
    0x1775, 0x1776, 0x1777, 0x1778, 0x8006, 0x8007, 0x9785, 0x978b, 0x978c, 0xfe0c, 0x3ea, 0x3eb, 0x3ec, 0x3f6,
    0x8001, 0x3f5, 0x8000, 0x8001, 0x8006, 0x8007, 0x8046, 0x804a, 0x804b, 0x83ea, 0x83eb, 0x8bbb, 0x8bbc, 0x8bbf,
    0x8bc0, 0x8bc1, 0x8bc2, 0x8bc5, 0x8bc6, 0x978e, 0x3eb, 0x3ec, 0x8046, 0x804b, 0x83ea, 0x83eb, 0x939a, 0x3ea,
    0x3eb, 0x8000, 0x3ea, 0x3ed, 0x3ee, 0x3f0, 0x3f2, 0x978e, 0x3eb, 0x3ec, 0x8000, 0x8001, 0x978f, 0x3eb, 0x3ef,
    0x8046, 0x978e, 0x9791, 0x3ea, 0x3eb, 0x3ec, 0x3ed, 0x3ee, 0x3ef, 0x3fa, 0x8006, 0x8007, 0x8046, 0x804a, 0x804b,
    0x83ea, 0x83eb, 0x938a, 0x93a5, 0x93a6, 0x93a7, 0xfe0c, 0x8049, 0x93a8, 0xfe0c, 0x8049, 0x93a8, 0x7d2, 0x7d3,
    0x8006, 0x8007, 0x8046, 0x8049, 0x804b, 0x83ea, 0x83eb, 0x938a, 0x938e, 0x93a5, 0x93a6, 0x93a7, 0x93a8, 0xfe0c,
    0x1b5a, 0x1b5b, 0x1b5c, 0x1b5d, 0x8001, 0x977b, 0x978f, 0x8007, 0x8046, 0x8049, 0x804b, 0x83ea, 0x83eb, 0x93a5,
    0x93a6, 0x93a7, 0x93a8, 0xfe0c, 0x3eb, 0x8046, 0x804b, 0x83ea, 0x83eb, 0x939a, 0x8010, 0x8046, 0x804b, 0x804d,
    0x83ea, 0x83eb, 0x83fe, 0x83ff, 0x8400, 0x87d6, 0x9392, 0x93ed, 0x93fe, 0x9771, 0x9772, 0x9773, 0x9774, 0x9775,
    0x9776, 0x9777, 0x9778, 0x9779, 0x977a, 0x977e, 0x977f, 0x9780, 0x9783, 0x9784, 0x9786, 0x9787, 0x978a, 0x9790,
    0x9794, 0x9795, 0x9796, 0x9797, 0x9799, 0x979a, 0x979b, 0x979c, 0x979f, 0x97a0, 0x97a2, 0x97a3, 0x97a4, 0x97a5,
    0x97a6, 0x97a7, 0x97a8, 0x97a9, 0x97aa, 0x97ab, 0x97ac, 0x97ad, 0x97af, 0x97b0, 0x97b1, 0x97b2, 0x97b6, 0x1, 0x2,
    0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16,
};

// an attribute list: a slice of the two entry arrays above
struct LitAttrSpan {
    u16 first; // index into gLitAttrCodes / gLitAttrNames
    u16 n;
};

// per-tag attribute lists, indexed by the html tag code
static const LitAttrSpan gLitHtmlTagAttrs[109] = {
    {0, 0}, {0, 0}, {0, 0}, {0, 11}, {0, 0}, {11, 1}, {12, 13}, {25, 10}, {35, 4}, {39, 2}, {41, 3}, {0, 0}, {44, 4},
    {35, 4}, {0, 0}, {48, 5}, {53, 23}, {48, 5}, {76, 2}, {78, 6}, {48, 5}, {35, 4}, {35, 4}, {84, 5}, {84, 5},
    {0, 0}, {0, 0}, {89, 5}, {0, 0}, {35, 4}, {0, 0}, {94, 6}, {100, 5}, {89, 5}, {35, 4}, {105, 10}, {115, 1},
    {116, 7}, {123, 8}, {131, 11}, {142, 12}, {0, 0}, {154, 6}, {154, 6}, {154, 6}, {154, 6}, {154, 6}, {154, 6},
    {0, 0}, {160, 9}, {0, 0}, {35, 4}, {169, 14}, {183, 23}, {206, 26}, {0, 0}, {35, 4}, {232, 1}, {115, 1}, {233, 6},
    {239, 12}, {11, 1}, {251, 5}, {256, 14}, {0, 0}, {270, 5}, {275, 1}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {276, 18},
    {294, 7}, {301, 2}, {154, 6}, {303, 1}, {11, 1}, {48, 5}, {35, 4}, {0, 0}, {0, 0}, {0, 0}, {35, 4}, {35, 4},
    {304, 6}, {310, 5}, {35, 4}, {35, 4}, {35, 4}, {35, 4}, {315, 5}, {35, 4}, {35, 4}, {320, 19}, {339, 3}, {342, 2},
    {344, 16}, {360, 7}, {339, 3}, {344, 16}, {339, 3}, {0, 0}, {367, 11}, {35, 4}, {35, 4}, {378, 6}, {35, 4},
    {0, 0}, {0, 0},
};

// attributes shared by all html tags, tried when the per-tag list has no match
static const LitAttrSpan gLitHtmlAttrs = {384, 59};

static const LitAttrSpan gLitOpfAttrs = {443, 22};
// clang-format on
// @gen-end litdoc-maps

constexpr int kLzxOk = 0; // chm.c DECR_OK

static const char* kLzxGuid = "{0A9007C6-4076-11D3-8789-0000F8105754}";
static const char* kDesGuid = "{67F6E4A2-60BF-11D3-8540-00C04F58C3CF}";

//--- mssha1: SHA-1 as modified by Microsoft for .lit DRM key derivation:
// different initial state and a few rounds use the wrong mixing function

struct MsSha1 {
    u32 h[5];
    u64 nBytes = 0;
    u8 buf[64];
    int bufUsed = 0;
};

static u32 rol32(u32 x, int n) {
    return (x << n) | (x >> (32 - n));
}

static void MsSha1Init(MsSha1* s) {
    s->h[0] = 0x32107654;
    s->h[1] = 0x23016745;
    s->h[2] = 0xC4E680A2;
    s->h[3] = 0xDC679823;
    s->h[4] = 0xD0857A34;
    s->nBytes = 0;
    s->bufUsed = 0;
}

static void MsSha1Block(MsSha1* s, const u8* p) {
    u32 w[80];
    for (size_t i = 0; i < 16; i++) {
        w[i] = ((u32)p[i * 4] << 24) | ((u32)p[(i * 4) + 1] << 16) | ((u32)p[(i * 4) + 2] << 8) | (u32)p[(i * 4) + 3];
    }
    for (int t = 16; t < 80; t++) {
        w[t] = rol32(w[t - 3] ^ w[t - 8] ^ w[t - 14] ^ w[t - 16], 1);
    }
    static const u32 k[4] = {0x5A827999, 0x6ED9EBA1, 0x8F1BBCDC, 0xCA62C1D6};
    constexpr int kRoundsPerPhase = 20;
    u32 a = s->h[0], b = s->h[1], c = s->h[2], d = s->h[3], e = s->h[4];
    for (int t = 0; t < 80; t++) {
        // Microsoft changes the mixing function at specific rounds.
        int phase = t / kRoundsPerPhase;
        u32 f = b ^ c ^ d;
        if (t == 6 || t == 42) {
            f = (b + c) ^ c;
        } else if (t == 26 || t == 68 || (phase == 0 && t != 3 && t != 10 && t != 15)) {
            f = (b & (c ^ d)) ^ d;
        } else if (t == 31 || (phase == 2 && t != 51)) {
            f = (b & c) | (b & d) | (c & d);
        }
        u32 tmp = rol32(a, 5) + f + e + w[t] + k[phase];
        e = d;
        d = c;
        c = rol32(b, 30);
        b = a;
        a = tmp;
    }
    s->h[0] += a;
    s->h[1] += b;
    s->h[2] += c;
    s->h[3] += d;
    s->h[4] += e;
}

static void MsSha1Update(MsSha1* s, const u8* d, int n) {
    s->nBytes += (u64)n;
    while (n > 0) {
        int take = std::min(n, 64 - s->bufUsed);
        memcpy(s->buf + s->bufUsed, d, (size_t)take);
        s->bufUsed += take;
        d += take;
        n -= take;
        if (s->bufUsed == 64) {
            MsSha1Block(s, s->buf);
            s->bufUsed = 0;
        }
    }
}

static void MsSha1Final(MsSha1* s, u8 digest[20]) {
    u64 bitLen = s->nBytes * 8;
    u8 pad = 0x80;
    MsSha1Update(s, &pad, 1);
    u8 zero = 0;
    while (s->bufUsed != 56) {
        MsSha1Update(s, &zero, 1);
    }
    u8 lenBuf[8];
    for (int i = 0; i < 8; i++) {
        lenBuf[i] = (u8)(bitLen >> (56 - (i * 8)));
    }
    MsSha1Update(s, lenBuf, 8);
    for (size_t i = 0; i < 5; i++) {
        digest[i * 4] = (u8)(s->h[i] >> 24);
        digest[(i * 4) + 1] = (u8)(s->h[i] >> 16);
        digest[(i * 4) + 2] = (u8)(s->h[i] >> 8);
        digest[(i * 4) + 3] = (u8)(s->h[i]);
    }
}

//--- little-endian readers with bounds checking

static u32 LitU16(Str d, int off) {
    return ByteReader(d).UInt16LE(off);
}

static u32 LitU32(Str d, int off) {
    return ByteReader(d).UInt32LE(off);
}

// 7-bit groups, high bit set = continue; big-endian group order. Values too
// large for an int saturate at INT_MAX (the root "/" entry stores junk that
// overflows; its value is never used, but the bytes must be consumed)
static int LitEncInt(Str d, int* pos) {
    u64 v = 0;
    while (*pos < len(d)) {
        u8 b = (u8)d.s[(*pos)++];
        v = (v << 7) | (b & 0x7f);
        if (v > (u64)INT_MAX) {
            v = (u64)INT_MAX;
        }
        if (!(b & 0x80)) {
            return (int)v;
        }
    }
    return -1;
}

// one utf8-encoded value (the tokenized format uses utf8 for tag / attr
// codes, so values like 0x8000 span multiple bytes); -1 on malformed input
static int LitUtf8Char(Str d, int* pos) {
    if (*pos >= len(d)) {
        return -1;
    }
    u32 c = (u8)d.s[(*pos)++];
    if (c < 0x80) {
        return (int)c;
    }
    int mask = 0x80;
    int size = 0;
    while (c & mask) {
        mask >>= 1;
        size++;
    }
    // the tokenized format can use overlong encodings, up to 6 bytes
    if (size < 2 || size > 6) {
        return -1;
    }
    c &= mask - 1;
    for (int i = 1; i < size; i++) {
        if (*pos >= len(d)) {
            return -1;
        }
        u8 b = (u8)d.s[(*pos)++];
        if ((b & 0xC0) != 0x80) {
            return -1;
        }
        c = (c << 6) | (b & 0x3f);
    }
    return (int)c;
}

static void LitAppendUtf8(str::Builder& out, int c) {
    constexpr int kMaxRuneBytes = 4;
    char buf[kMaxRuneBytes];
    int n = 0;
    str::Utf8Encode(buf, n, c);
    // LIT keeps extra prefix bits for values outside Unicode.
    if (n == kMaxRuneBytes) {
        buf[0] = (char)(0xF0 | (c >> 18));
    }
    out.Append(Str(buf, n));
}

// length-prefixed utf8 string: first utf8 char is the length in characters
static TempStr LitSizedStringTemp(Str d, int* pos, bool zpad) {
    int nChars = LitUtf8Char(d, pos);
    if (nChars < 0) {
        return {};
    }
    str::Builder out;
    for (int i = 0; i < nChars; i++) {
        int c = LitUtf8Char(d, pos);
        if (c < 0) {
            return {};
        }
        LitAppendUtf8(out, c);
    }
    if (zpad && *pos < len(d) && d.s[*pos] == 0) {
        (*pos)++;
    }
    return ToStrTemp(out);
}

//--- the .lit container

struct LitEntry {
    Str name; // points into the directory piece
    int section = 0;
    int offset = 0;
    int size = 0;
};

struct LitManifestItem {
    TempStr internal{};
    TempStr path{}; // normalized path, also the path inside the epub
    bool isSpine = false;
};

constexpr int kLitMaxSections = 16;

struct LitFile {
    Str d; // the whole file
    int contentOffset = 0;
    u32 entryChunkLen = 0;
    Vec<LitEntry> entries;
    StrVec sectionNames;
    Str sectionData[kLitMaxSections]; // decoded caches, owned
    Vec<LitManifestItem> manifest;
    int drmLevel = 0;
    u8 bookKey[8] = {};

    ~LitFile() {
        for (Str& s : sectionData) {
            str::Free(s);
        }
    }

    LitEntry* FindEntry(Str name);
    Str GetFile(Str name); // temp or view; copy if kept
    Str GetSection(int section);
};

LitEntry* LitFile::FindEntry(Str name) {
    for (LitEntry& e : entries) {
        if (str::Eq(e.name, name)) {
            return &e;
        }
    }
    return nullptr;
}

static bool LitParseHeader(LitFile* lit) {
    Str d = lit->d;
    if (len(d) < 0x28 || !str::StartsWith(d, StrL("ITOLITLS"))) {
        return false;
    }
    if (LitU32(d, 8) != 1) {
        logf("LitDoc: unknown version %d\n", (int)LitU32(d, 8));
        return false;
    }
    int hdrLen = (int)LitU32(d, 12);
    int nPieces = (int)LitU32(d, 16);
    int secHdrLen = (int)LitU32(d, 20);
    if (hdrLen < 0x28 || nPieces < 5 || nPieces > 16 || secHdrLen < 0) {
        return false;
    }
    // hdrLen comes from the file; bound it before computing offsets from it
    // so hdrLen + nPieces * 16 can't overflow into a negative offset
    if ((i64)hdrLen + ((i64)nPieces * 16) > len(d)) {
        return false;
    }

    // secondary header: CAOL / ITSF blocks
    {
        int off = hdrLen + (nPieces * 16);
        Str sec(d.s + off, std::min(secHdrLen, len(d) - off));
        int pos = (int)LitU32(sec, 4);
        bool haveContentOffset = false;
        // pos comes from the file: compare without pos + 8 overflowing
        while (pos >= 0 && pos <= len(sec) - 8) {
            Str blockTag(sec.s + pos, 4);
            u32 ver = LitU32(sec, pos + 4);
            if (str::Eq(blockTag, StrL("CAOL"))) {
                if (ver != 2) {
                    return false;
                }
                lit->entryChunkLen = LitU32(sec, pos + 20);
                pos += 48;
            } else if (str::Eq(blockTag, StrL("ITSF"))) {
                if (ver != 4 || LitU32(sec, pos + 20) != 0) {
                    return false;
                }
                u32 contentOffset = LitU32(sec, pos + 16);
                if (contentOffset > (u32)len(d)) {
                    return false;
                }
                lit->contentOffset = (int)contentOffset;
                haveContentOffset = true;
                pos += 48;
            } else {
                break;
            }
        }
        if (!haveContentOffset) {
            return false;
        }
    }

    // header piece 1 is the directory
    i64 dirOff64 = (i64)ByteReader(d).UInt64LE(hdrLen + 16);
    i64 dirLen64 = (i64)ByteReader(d).UInt64LE(hdrLen + 16 + 8);
    if (dirOff64 <= 0 || dirLen64 <= 32 || dirOff64 > len(d) || dirLen64 > len(d) - dirOff64) {
        return false;
    }
    Str dir(d.s + (int)dirOff64, (int)dirLen64);
    if (!str::StartsWith(dir, StrL("IFCM"))) {
        return false;
    }
    int chunkSize = (int)LitU32(dir, 8);
    int nChunks = (int)LitU32(dir, 24);
    if (chunkSize <= 48 || nChunks <= 0 || 32 + ((i64)nChunks * chunkSize) != dirLen64) {
        return false;
    }
    if (lit->entryChunkLen && (u32)chunkSize != lit->entryChunkLen) {
        return false;
    }
    for (int i = 0; i < nChunks; i++) {
        int chunkOff = 32 + (i * chunkSize);
        Str chunk(dir.s + chunkOff, chunkSize);
        if (!str::StartsWith(chunk, StrL("AOLL"))) {
            continue;
        }
        int freeSpace = (int)LitU32(chunk, 4);
        if (freeSpace < 0 || freeSpace >= chunkSize) {
            return false;
        }
        int dataEnd = chunkSize - freeSpace - 2; // last 2 bytes: entry count
        int nEntries = (int)LitU16(chunk, chunkSize - 2);
        if (nEntries == 0) {
            nEntries = 0xffff;
        }
        int pos = 48;
        for (int j = 0; j < nEntries && pos < dataEnd; j++) {
            int nameLen = LitEncInt(chunk, &pos);
            // nameLen comes from the file: compare without pos + nameLen overflowing
            if (nameLen <= 0 || nameLen > dataEnd - pos) {
                break;
            }
            LitEntry e;
            e.name = Str(chunk.s + pos, nameLen);
            pos += nameLen;
            e.section = LitEncInt(chunk, &pos);
            e.offset = LitEncInt(chunk, &pos);
            e.size = LitEncInt(chunk, &pos);
            if (e.size < 0) {
                break; // ran off the end of the chunk
            }
            VecAppend(lit->entries, e);
        }
    }
    return len(lit->entries) > 0;
}

Str LitFile::GetFile(Str name) {
    LitEntry* e = FindEntry(name);
    if (!e) {
        return {};
    }
    // offset / size come from the file: check without offset + size overflowing
    if (e->offset < 0 || e->size < 0) {
        return {};
    }
    if (e->section == 0) {
        i64 off = (i64)contentOffset + e->offset;
        if (off < 0 || off > len(d) || e->size > len(d) - off) {
            return {};
        }
        return Str(d.s + (int)off, e->size);
    }
    Str sec = GetSection(e->section);
    if (e->offset > len(sec) || e->size > len(sec) - e->offset) {
        return {};
    }
    return Str(sec.s + e->offset, e->size);
}

static bool LitParseSectionNames(LitFile* lit) {
    Str raw = lit->GetFile(StrL("::DataSpace/NameList"));
    if (len(raw) < 4) {
        return false;
    }
    int nSections = (int)LitU16(raw, 2);
    if (nSections <= 0 || nSections > kLitMaxSections) {
        return false;
    }
    int pos = 4;
    for (int i = 0; i < nSections; i++) {
        if (pos > len(raw) - 2) {
            return false;
        }
        int nChars = (int)LitU16(raw, pos);
        pos += 2;
        if (((i64)nChars * 2) + 2 > (i64)len(raw) - pos) {
            return false;
        }
        WStr ws((const WCHAR*)(raw.s + pos), nChars);
        lit->sectionNames.Append(ToUtf8Temp(ws));
        pos += (nChars * 2) + 2;
    }
    return true;
}

static void LitDesDecrypt(u8* dst, const u8* src, int n, const u8 key[8]) {
    u8 k[8];
    memcpy(k, key, 8);
    deskey(k, DE1);
    for (int off = 0; off + 8 <= n; off += 8) {
        u8 in[8];
        memcpy(in, src + off, 8);
        des(in, dst + off);
    }
}

// DRM1 key: fold the mssha1 hash of (2 NUL bytes + /meta, zero-padded to a
// 64-byte multiple) + (/DRMStorage/DRMSource, same padding)
static bool LitReadDrm(LitFile* lit) {
    if (lit->FindEntry(StrL("/DRMStorage/Licenses/EUL"))) {
        lit->drmLevel = 5;
        logf("LitDoc: DRM5 (user-locked) book, cannot decrypt\n");
        return false;
    }
    if (lit->FindEntry(StrL("/DRMStorage/DRMBookplate"))) {
        lit->drmLevel = 3;
    } else if (lit->FindEntry(StrL("/DRMStorage/DRMSealed"))) {
        lit->drmLevel = 1;
    } else {
        return true; // no DRM
    }
    MsSha1 sha;
    MsSha1Init(&sha);
    const Str hashFiles[] = {StrL("/meta"), StrL("/DRMStorage/DRMSource"), StrL("/DRMStorage/DRMBookplate")};
    int nHashFiles = lit->drmLevel == 3 ? dimofi(hashFiles) : dimofi(hashFiles) - 1;
    constexpr int kMetaPrefixBytes = 2;
    u8 zeros[64] = {};
    for (int i = 0; i < nHashFiles; i++) {
        Str data = lit->GetFile(hashFiles[i]);
        if (str::IsNull(data)) {
            return false;
        }
        int prepad = i == 0 ? kMetaPrefixBytes : 0;
        MsSha1Update(&sha, zeros, prepad);
        MsSha1Update(&sha, (const u8*)data.s, len(data));
        int pad = 64 - ((len(data) + prepad) % 64);
        if (pad < 64) {
            MsSha1Update(&sha, zeros, pad);
        }
    }
    u8 digest[20];
    MsSha1Final(&sha, digest);
    u8 key[8] = {};
    for (int i = 0; i < 20; i++) {
        key[i % 8] ^= digest[i];
    }

    Str sealed = lit->GetFile(StrL("/DRMStorage/DRMSealed"));
    if (len(sealed) < 16) {
        return false;
    }
    u8 unsealed[16];
    LitDesDecrypt(unsealed, (const u8*)sealed.s, 16, key);
    if (unsealed[0] != 0) {
        logf("LitDoc: failed to unseal DRM key\n");
        return false;
    }
    memcpy(lit->bookKey, unsealed + 1, 8);
    return true;
}

static Str LitLzxDecompress(Str content, Str control, Str resetTable) {
    if (len(control) < 32 || !str::Eq(Str(control.s + 4, 4), StrL("LZXC"))) {
        return {};
    }
    if (len(resetTable) < 40) {
        return {};
    }
    int windowSize = 14;
    u32 u = LitU32(control, 12);
    while (u > 0) {
        u >>= 1;
        windowSize++;
    }
    if (windowSize < 15 || windowSize > 21) {
        return {};
    }
    struct LZXstate* lzx = LZXinit(windowSize);
    if (!lzx) {
        return {};
    }

    AutoCall teardown(LZXteardown, lzx);

    u32 ofsEntry32 = LitU32(resetTable, 12);
    if (ofsEntry32 > (u32)len(resetTable) - 8) {
        return {};
    }
    int ofsEntry = (int)ofsEntry32 + 8;
    if (LitU32(resetTable, 20) != 0) {
        return {};
    }
    int interval = (int)LitU32(resetTable, 32);
    int bytesRemaining = (int)LitU32(resetTable, 16);
    if (interval <= 0) {
        return {};
    }

    // Decode reset-table intervals, resetting LZX only at window boundaries.
    int windowBytes = 1 << windowSize;
    int intervalsPerWindow = (windowBytes >= interval) ? (windowBytes / interval) : 1;
    str::Builder out;
    AutoFree<u8> obuf(AllocArray<u8>(interval));
    int base = 0;
    int idx = 0;
    // Without a table entry, only one final interval may remain.
    while (bytesRemaining > 0) {
        bool hasEntry = ofsEntry <= len(resetTable) - 8;
        int size = hasEntry ? (int)LitU32(resetTable, ofsEntry) : len(content);
        if ((!hasEntry && bytesRemaining > interval) || (hasEntry && LitU32(resetTable, ofsEntry + 4) != 0) ||
            size > len(content) || size < base) {
            break;
        }
        int outThis = std::min(interval, bytesRemaining);
        if (idx % intervalsPerWindow == 0) {
            LZXreset(lzx);
        }
        int res = LZXdecompress(lzx, (u8*)content.s + base, obuf, size - base, outThis);
        if (res != kLzxOk) {
            break;
        }
        out.Append(Str((char*)obuf.Get(), outThis));
        bytesRemaining -= outThis;
        base = size;
        ofsEntry += hasEntry ? 8 : 0;
        idx++;
    }
    if (bytesRemaining != 0) {
        logf("LitDoc: LZX decompression failed\n");
        return {};
    }
    return out.TakeStr();
}

static TempStr LitGuidTemp(Str d) {
    if (len(d) < 16) {
        return {};
    }
    const u8* p = (const u8*)d.s;
    u32 a = LitU32(d, 0);
    u32 b = LitU16(d, 4);
    u32 c = LitU16(d, 6);
    return fmt("{%08X-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X}", a, b, c, p[8], p[9], p[10], p[11], p[12], p[13],
               p[14], p[15]);
}

Str LitFile::GetSection(int section) {
    if (section <= 0 || section >= kLitMaxSections || section >= len(sectionNames)) {
        return {};
    }
    if (!str::IsNull(sectionData[section])) {
        return sectionData[section];
    }
    Str name = sectionNames.At(section);
    TempStr base = fmt("::DataSpace/Storage/%s", name);
    Str transform = GetFile(fmt("%s/Transform/List", Str(base)));
    Str content = GetFile(fmt("%s/Content", Str(base)));
    Str control = GetFile(fmt("%s/ControlData", Str(base)));

    ScopedMem<char> decoded;
    Str view = content;
    while (len(transform) >= 16) {
        i64 csize64 = ((i64)LitU32(control, 0) + 1) * 4;
        if (csize64 > len(control)) {
            break;
        }
        int csize = (int)csize64;
        TempStr guid = LitGuidTemp(transform);
        Str next;
        if (str::Eq(guid, Str(kDesGuid))) {
            if (drmLevel == 0 || drmLevel == 5) {
                return {};
            }
            int n = len(view);
            int nPadded = RoundUp(n, 8);
            u8* dec = AllocArray<u8>(nPadded);
            u8* src = AllocArray<u8>(nPadded);
            memcpy(src, view.s, (size_t)n);
            LitDesDecrypt(dec, src, nPadded, bookKey);
            Free(nullptr, src);
            next = Str((char*)dec, n);
        } else if (str::Eq(guid, Str(kLzxGuid))) {
            Str resetTable = GetFile(fmt("%s/Transform/%s/InstanceData/ResetTable", Str(base), Str(kLzxGuid)));
            next = LitLzxDecompress(view, control, resetTable);
            if (str::IsNull(next)) {
                return {};
            }
        } else {
            logf("LitDoc: unknown transform %s\n", guid);
            return {};
        }
        decoded.Set(next.s);
        view = next;
        control = Str(control.s + csize, len(control) - csize);
        transform = Str(transform.s + 16, len(transform) - 16);
    }
    if (!decoded.Get()) {
        view = str::Dup(view);
    }
    sectionData[section] = view;
    decoded.Take();
    return view;
}

//--- manifest

// Normalize manifest paths, discarding parents that escape the archive root.
static TempStr LitNormPathTemp(Str path) {
    StrVec parts;
    Split(&parts, path, StrL("/"), true);
    StrVec out;
    for (Str p : parts) {
        if (len(p) == 0 || str::Eq(p, StrL("."))) {
            continue;
        }
        if (str::Eq(p, StrL(".."))) {
            if (!out.IsEmpty()) {
                out.RemoveAt(len(out) - 1);
            }
            continue;
        }
        out.Append(p);
    }
    return out.IsEmpty() ? TempStr{} : JoinTemp(&out, StrL("/"));
}

constexpr int kLitManifestGroups = 4;

static bool LitParseManifest(LitFile* lit) {
    Str raw = lit->GetFile(StrL("/manifest"));
    if (str::IsNull(raw)) {
        return false;
    }
    int pos = 0;
    while (pos < len(raw)) {
        int slen = (u8)raw.s[pos++];
        if (slen == 0 || slen > len(raw) - pos) {
            break;
        }
        pos += slen; // root name, unused
        for (int state = 0; state < kLitManifestGroups; state++) {
            // 0 = spine, 1 = not spine, 2 = css, 3 = images
            int nFiles = (int)LitU32(raw, pos);
            pos += 4;
            if (nFiles <= 0) {
                continue;
            }
            for (int i = 0; i < nFiles; i++) {
                if (len(raw) < 5 || pos > len(raw) - 5) {
                    return len(lit->manifest) > 0;
                }
                pos += 4; // offset, unused
                LitManifestItem item;
                item.internal = LitSizedStringTemp(raw, &pos, false);
                TempStr path = LitSizedStringTemp(raw, &pos, false);
                LitSizedStringTemp(raw, &pos, true); // consume unused MIME type
                if (len(item.internal) == 0 || len(path) == 0) {
                    return len(lit->manifest) > 0;
                }
                item.isSpine = (state == 0);
                // normalize the original path: windows separators, drive
                // letters, stray ".." (all seen in the wild per calibre)
                str::TransCharsInPlace(path, StrL("\\"), StrL("/"));
                if (len(path) > 2 && path.s[1] == ':' && path.s[2] == '/') {
                    path = Str(path.s + 3, len(path) - 3);
                }
                item.path = LitNormPathTemp(path);
                VecAppend(lit->manifest, item);
            }
        }
    }
    // Strip complete directories shared by all items.
    if (len(lit->manifest) > 1) {
        Str first = lit->manifest[0].path;
        int prefixLen = len(first);
        for (const LitManifestItem& it : lit->manifest) {
            int i = 0;
            while (i < prefixLen && i < len(it.path) && first.s[i] == it.path.s[i]) {
                i++;
            }
            prefixLen = i;
        }
        prefixLen = str::LastIndexOfChar(Str(first.s, prefixLen), '/') + 1;
        if (prefixLen > 0) {
            for (LitManifestItem& it : lit->manifest) {
                it.path = Str(it.path.s + prefixLen, len(it.path) - prefixLen);
            }
        }
    }
    for (LitManifestItem& it : lit->manifest) {
        if (len(it.path) == 0) {
            it.path = it.internal;
        }
    }
    return len(lit->manifest) > 0;
}

static LitManifestItem* LitFindManifest(LitFile* lit, Str internal) {
    for (LitManifestItem& it : lit->manifest) {
        if (str::Eq(it.internal, internal)) {
            return &it;
        }
    }
    return nullptr;
}

//--- UnBinary: reconstruct HTML / OPF text from the tokenized binary form

struct LitAtoms {
    StrVec tags;  // 1-based: tags[i - 1]
    StrVec attrs; // 1-based
};

// /data/{internal}/atom: custom tag / attribute names referenced by FLAG_ATOM
static void LitParseAtoms(LitFile* lit, Str internal, LitAtoms* atoms) {
    Str data = lit->GetFile(fmt("/data/%s/atom", internal));
    const struct {
        StrVec* names;
        int sizeBytes;
    } lists[] = {{&atoms->tags, sizeofi(u8)}, {&atoms->attrs, sizeofi(u32)}};

    int pos = 0;
    for (const auto& list : lists) {
        if (pos + sizeofi(u32) > len(data)) {
            return;
        }
        int n = (int)LitU32(data, pos);
        pos += sizeofi(u32);
        for (int i = 0; i < n; i++) {
            if (pos + list.sizeBytes > len(data)) {
                return;
            }
            int size = list.sizeBytes == sizeofi(u8) ? (u8)data.s[pos] : (int)LitU32(data, pos);
            pos += list.sizeBytes;
            if (size <= 0 || size > len(data) - pos) {
                return;
            }
            list.names->Append(Str(data.s + pos, size));
            pos += size;
        }
    }
}

constexpr int kLitFlagOpening = 1 << 0;
constexpr int kLitFlagClosing = 1 << 1;
constexpr int kLitFlagAtom = 1 << 4;

struct UnBinaryCtx {
    Str bin;
    int pos = 0;
    str::Builder out;
    LitFile* lit = nullptr;
    Str dir; // directory of the file being reconstructed
    bool isHtml = true;
    LitAtoms* atoms = nullptr;
};

static const char* LitTagName(UnBinaryCtx* ctx, int tag) {
    // the tag tables are SeqStrings indexed by tag code; a code with no tag
    // is stored as the "\x01" sentinel (empty isn't representable mid-list)
    Str name = SeqStrByIndex(ctx->isHtml ? gLitHtmlTags : gLitOpfTags, tag);
    if (len(name) > 0 && name.s[0] != '\x01') {
        return name.s; // points into the static literal
    }
    return nullptr;
}

static const char* LitAttrInSpan(LitAttrSpan span, int code) {
    for (int i = 0; i < (int)span.n; i++) {
        int idx = (int)span.first + i;
        if ((int)gLitAttrCodes[idx] == code) {
            return SeqStrByIndex(gLitAttrNames, idx).s; // points into the static literal
        }
    }
    return nullptr;
}

static const char* LitAttrName(UnBinaryCtx* ctx, int tag, bool tagIsAtom, int code) {
    if (tagIsAtom && ctx->atoms && code >= 1 && code <= len(ctx->atoms->attrs)) {
        Str s = ctx->atoms->attrs.At(code - 1);
        if (len(s) > 0) {
            return s.s; // page strings are 0-terminated
        }
    }
    const char* res = nullptr;
    if (!tagIsAtom && ctx->isHtml && tag >= 0 && tag < dimofi(gLitHtmlTagAttrs)) {
        res = LitAttrInSpan(gLitHtmlTagAttrs[tag], code);
    }
    if (!res) {
        res = LitAttrInSpan(ctx->isHtml ? gLitHtmlAttrs : gLitOpfAttrs, code);
    }
    return res;
}

// href/src values start with '/' and reference a manifest internal id;
// translate to the item's path, relative to the current file's directory
static TempStr LitResolveHrefTemp(UnBinaryCtx* ctx, Str href) {
    // the first character is a flag byte (not part of the path); drop it
    if (len(href) > 0) {
        href = Str(href.s + 1, len(href) - 1);
    }
    Str doc = href;
    Str frag;
    int hash = str::IndexOfChar(href, '#');
    if (hash >= 0) {
        doc = Str(href.s, hash);
        frag = Str(href.s + hash, len(href) - hash);
    }
    LitManifestItem* item = ctx->lit ? LitFindManifest(ctx->lit, doc) : nullptr;
    if (!item) {
        return len(frag) > 0 ? str::JoinTemp(doc, frag) : str::DupTemp(doc);
    }

    // make relative to ctx->dir
    Str target = item->path;
    Str base = ctx->dir;
    // Strip the common directory prefix.
    int slash = -1;
    for (int i = 0; i < std::min(len(target), len(base)); i++) {
        if (target.s[i] != base.s[i]) {
            break;
        }
        if (target.s[i] == '/') {
            slash = i;
        }
    }
    if (slash >= 0) {
        target = Str(target.s + slash + 1, len(target) - slash - 1);
        base = Str(base.s + slash + 1, len(base) - slash - 1);
    }
    str::Builder rel;
    for (int i = 0; i < len(base); i++) {
        if (base.s[i] == '/') {
            rel.Append(StrL("../"));
        }
    }
    if (len(base) > 0) {
        rel.Append(StrL("../")); // base is a dir path without trailing slash
    }
    rel.Append(target);
    rel.Append(frag);
    return ToStrTemp(rel);
}

// emit one output character: ASCII verbatim, everything else as a numeric
// character reference. Matches calibre and sidesteps any charset ambiguity in
// the reconstructed XHTML (mupdf would otherwise read raw UTF-8 as latin-1)
static void LitEmitChar(str::Builder& out, int c) {
    if (c < 0x80) {
        out.AppendChar((char)c);
    } else {
        out.Append(fmt("&#%d;", c));
    }
}

// appends c to out, escaping markup like the tokenized form expects: literal
// '<' / '>' in text are doubled here and fixed up in LitEscapeReserved()
static void LitEmitTextChar(str::Builder& out, int c) {
    if (c == '\v') {
        out.AppendChar('\n');
    } else if (c == '>') {
        out.Append(StrL(">>"));
    } else if (c == '<') {
        out.Append(StrL("<<"));
    } else {
        LitEmitChar(out, c);
    }
}

// port of calibre's UnBinary.binary_to_text state machine
static bool LitBinaryToText(UnBinaryCtx* ctx, int depth) {
    if (depth > 128) {
        return false;
    }
    str::Builder& out = ctx->out;
    Str bin = ctx->bin;
    int state = 0; // 0 text, 1 flags, 2 tag, 3 attr, 4 value-len, 5 value,
                   // 6 custom-len, 7 custom, 8 attr-len, 9 custom-attr,
                   // 10 href-len, 11 href
    int flags = 0;
    int count = 0;
    bool inCensorship = false;
    bool isGoingdown = false;
    bool tagIsAtom = false;
    int tag = 0;
    Str tagName;
    str::Builder custom;
    str::Builder href;

    while (ctx->pos < len(bin)) {
        int c = LitUtf8Char(bin, &ctx->pos);
        if (c < 0) {
            return false;
        }
        switch (state) {
            case 0: // text
                if (c == 0) {
                    state = 1;
                } else {
                    LitEmitTextChar(out, c);
                }
                break;
            case 1: // get flags
                if (c == 0) {
                    state = 0;
                    break;
                }
                flags = c;
                state = 2;
                break;
            case 2: // get tag
                state = (c == 0) ? 0 : 3;
                if (flags & kLitFlagOpening) {
                    tag = c;
                    out.Append(StrL("<"));
                    isGoingdown = !(flags & kLitFlagClosing);
                    if (tag == 0x8000) {
                        state = 6;
                        break;
                    }
                    tagIsAtom = false;
                    const char* name = nullptr;
                    if (flags & kLitFlagAtom) {
                        if (!ctx->atoms || tag < 1 || tag > len(ctx->atoms->tags)) {
                            return false;
                        }
                        name = ctx->atoms->tags.At(tag - 1).s;
                        tagIsAtom = true;
                    } else {
                        name = LitTagName(ctx, tag);
                    }
                    tagName = name ? Str(name) : fmt("x-lit-tag-%d", tag);
                    out.Append(Str(tagName));
                } else if (flags & kLitFlagClosing) {
                    if (depth == 0) {
                        return false;
                    }
                    return true; // parent writes the close tag
                }
                break;
            case 3: // get attr
                inCensorship = false;
                if (c == 0) {
                    state = 0;
                    if (!isGoingdown) {
                        tagName = {};
                        out.Append(StrL(" />"));
                    } else {
                        out.Append(StrL(">"));
                        // recursively emit children until the closing token
                        if (!LitBinaryToText(ctx, depth + 1)) {
                            return false;
                        }
                        if (len(tagName) == 0) {
                            return false;
                        }
                        out.Append(StrL("</"));
                        out.Append(Str(tagName));
                        out.Append(StrL(">"));
                        tagName = {};
                        isGoingdown = false;
                    }
                } else {
                    if (c == 0x8000) {
                        state = 8;
                        break;
                    }
                    const char* attr = LitAttrName(ctx, tag, tagIsAtom, c);
                    if (!attr) {
                        return false;
                    }
                    if (attr[0] == '%') {
                        inCensorship = true;
                        state = 4;
                        break;
                    }
                    out.Append(StrL(" "));
                    out.Append(Str(attr));
                    out.Append(StrL("="));
                    if (str::Eq(Str(attr), StrL("href")) || str::Eq(Str(attr), StrL("src"))) {
                        state = 10;
                    } else {
                        state = 4;
                    }
                }
                break;
            case 4: // get value length
                if (!inCensorship) {
                    out.Append(StrL("\""));
                }
                count = c - 1;
                if (count == 0) {
                    if (!inCensorship) {
                        out.Append(StrL("\""));
                    }
                    inCensorship = false;
                    state = 3;
                    break;
                }
                state = 5;
                if (c == 0xffff) {
                    break; // numeric value follows as one char
                }
                if (count < 0 || count > len(bin) - ctx->pos) {
                    return false;
                }
                break;
            case 5: // get value
                if (count == 0xfffe) {
                    if (!inCensorship) {
                        out.Append(fmt("%d\"", c - 1));
                    }
                    inCensorship = false;
                    state = 3;
                } else if (count > 0) {
                    if (!inCensorship) {
                        if (c == '"') {
                            out.Append(StrL("&quot;"));
                        } else if (c == '<') {
                            out.Append(StrL("&lt;"));
                        } else {
                            LitEmitChar(out, c);
                        }
                    }
                    count--;
                }
                if (count == 0 && state == 5) {
                    if (!inCensorship) {
                        out.Append(StrL("\""));
                    }
                    inCensorship = false;
                    state = 3;
                }
                break;
            case 6:  // custom tag name length
            case 8:  // custom attr name length
            case 10: // href length
                count = c - 1;
                if (count <= 0 || count > len(bin) - ctx->pos) {
                    return false;
                }
                if (state == 6) {
                    custom.Reset();
                } else if (state == 8) {
                    out.Append(StrL(" "));
                } else {
                    href.Reset();
                }
                state++; // each length state precedes its content state
                break;
            case 7: // custom tag name
                LitAppendUtf8(custom, c);
                if (--count == 0) {
                    tagName = ToStr(custom);
                    out.Append(Str(tagName));
                    state = 3;
                }
                break;
            case 9: // custom attr name
                LitEmitChar(out, c);
                if (--count == 0) {
                    out.Append(StrL("="));
                    state = 4;
                }
                break;
            case 11: // href
                LitAppendUtf8(href, c);
                if (--count == 0) {
                    TempStr path = LitResolveHrefTemp(ctx, ToStr(href));
                    out.Append(StrL("\""));
                    out.Append(Str(path));
                    out.Append(StrL("\""));
                    state = 3;
                }
                break;
        }
    }
    // EOF with unclosed tags is tolerated: parents still write their close tags
    return true;
}

static bool LitIsEntityStart(Str s, int pos) {
    // "&#123;", "&#x1f;" or "&name;"
    int i = pos + 1;
    bool numeric = i < len(s) && s.s[i] == '#';
    if (numeric) {
        i++;
        if (i < len(s) && (s.s[i] == 'x' || s.s[i] == 'X')) {
            i++;
        }
    }
    int start = i;
    while (i < len(s)) {
        char c = s.s[i];
        bool valid =
            numeric ? str::HexDigitVal(c) >= 0 : str::IsAlNum(c) || c == '_' || c == ':' || c == '.' || c == '-';
        if (!valid) {
            break;
        }
        i++;
    }
    return i > start && i < len(s) && s.s[i] == ';';
}

// literal '&' => &amp;; '<<' / '>>' pairs written for literal angle brackets
// become &lt; / &gt;
static Str LitEscapeReserved(Str s) {
    str::Builder out;
    for (int i = 0; i < len(s); i++) {
        char c = s.s[i];
        Str replacement;
        if (c == '&' && !LitIsEntityStart(s, i)) {
            replacement = StrL("&amp;");
        } else if ((c == '<' || c == '>') && i + 1 < len(s) && s.s[i + 1] == c) {
            bool commentStart = c == '<' && str::StartsWith(Str(s.s + i + 2, len(s) - i - 2), StrL("!--"));
            bool commentEnd = c == '>' && i >= 2 && s.s[i - 1] == '-' && s.s[i - 2] == '-';
            if (!commentStart && !commentEnd) {
                replacement = c == '<' ? StrL("&lt;") : StrL("&gt;");
            }
            i++;
        }
        if (replacement) {
            out.Append(replacement);
        } else {
            out.AppendChar(c);
        }
    }
    return out.TakeStr();
}

// binary tokenized content -> markup text; returns {} on failure
static Str LitUnBinary(LitFile* lit, Str bin, Str path, bool isHtml, LitAtoms* atoms) {
    UnBinaryCtx ctx;
    ctx.bin = bin;
    ctx.lit = lit;
    ctx.isHtml = isHtml;
    ctx.atoms = atoms;
    int lastSlash = str::LastIndexOfChar(path, '/');
    ctx.dir = lastSlash >= 0 ? Str(path.s, lastSlash) : StrL("");
    if (!LitBinaryToText(&ctx, 0)) {
        return {};
    }
    Str raw = ToStr(ctx.out);
    str::TrimWs(raw); // strip leading whitespace
    return LitEscapeReserved(raw);
}

//--- epub packaging

static const char* kOpfDecl =
    "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n"
    "<!DOCTYPE package\n"
    "  PUBLIC \"+//ISBN 0-9673008-1-9//DTD OEB 1.0.1 Package//EN\"\n"
    "  \"http://openebook.org/dtds/oeb-1.0.1/oebpkg101.dtd\">\n";

static const char* kHtmlDecl =
    "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n"
    "<!DOCTYPE html PUBLIC\n"
    " \"+//ISBN 0-9673008-1-9//DTD OEB 1.0.1 Document//EN\"\n"
    " \"http://openebook.org/dtds/oeb-1.0.1/oebdoc101.dtd\">\n";

static const char* kContainerXml =
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
    "<container version=\"1.0\" xmlns=\"urn:oasis:names:tc:opendocument:xmlns:container\">\n"
    "  <rootfiles>\n"
    "    <rootfile full-path=\"content.opf\" media-type=\"application/oebps-package+xml\"/>\n"
    "  </rootfiles>\n"
    "</container>\n";

Str LitToEpubConvert(Str litData) {
    LitFile lit;
    lit.d = litData;
    if (!LitParseHeader(&lit)) {
        logf("LitDoc: failed to parse header/directory\n");
        return {};
    }
    if (!LitParseSectionNames(&lit)) {
        logf("LitDoc: failed to parse section names\n");
        return {};
    }
    if (!LitParseManifest(&lit)) {
        logf("LitDoc: failed to parse manifest\n");
        return {};
    }
    if (!LitReadDrm(&lit)) {
        return {};
    }

    Str meta = lit.GetFile(StrL("/meta"));
    if (str::IsNull(meta)) {
        logf("LitDoc: no /meta\n");
        return {};
    }
    Str opf = LitUnBinary(&lit, meta, StrL("content.opf"), false, nullptr);
    if (str::IsNull(opf)) {
        logf("LitDoc: failed to reconstruct OPF\n");
        return {};
    }

    str::Builder zipData;
    ZipCreator zc(zipData);
    bool ok = zc.AddFileData(StrL("mimetype"), StrL("application/epub+zip"));
    ok &= zc.AddFileData(StrL("META-INF/container.xml"), Str(kContainerXml));
    {
        TempStr full = str::JoinTemp(Str(kOpfDecl), opf);
        ok &= zc.AddFileData(StrL("content.opf"), Str(full));
    }
    str::Free(opf);

    int nAdded = 0;
    for (LitManifestItem& item : lit.manifest) {
        if (!ok) {
            break;
        }
        Str data;
        if (item.isSpine) {
            Str raw = lit.GetFile(fmt("/data/%s/content", item.internal));
            if (str::IsNull(raw)) {
                logf("LitDoc: no content for spine item '%s'\n", item.internal);
                continue;
            }
            LitAtoms atoms;
            LitParseAtoms(&lit, item.internal, &atoms);
            Str html = LitUnBinary(&lit, raw, item.path, true, &atoms);
            if (str::IsNull(html)) {
                logf("LitDoc: failed to reconstruct '%s'\n", item.path);
                continue;
            }
            data = str::JoinTemp(Str(kHtmlDecl), html);
            str::Free(html);
        } else {
            data = lit.GetFile(fmt("/data/%s", item.internal));
            if (str::IsNull(data)) {
                continue;
            }
        }
        ok &= zc.AddFileData(item.path, data);
        nAdded++;
    }
    if (!ok || nAdded == 0) {
        logf("LitDoc: no files packaged\n");
        return {};
    }
    if (!zc.Finish()) {
        return {};
    }
    return zipData.TakeStr();
}

EngineBase* CreateEngineLitFromFile(Str path, PasswordUI* pwdUI) {
    Str litData = file::ReadFile(path);
    if (str::IsNull(litData)) {
        return nullptr;
    }
    Str epubData = LitToEpubConvert(litData);
    str::Free(litData);
    if (str::IsNull(epubData)) {
        return nullptr;
    }
    EngineBase* engine = CreateEngineMupdfFromData(epubData, StrL("book.epub"), pwdUI);
    str::Free(epubData);
    if (engine) {
        engine->SetFilePath(path);
    }
    return engine;
}

#if IS_DEBUG
bool LitDoc_UnitTestManifest() {
    const Str cases[][4] = {
        {StrL("same/a.html"), StrL("same/b.html"), StrL("a.html"), StrL("b.html")},
        {StrL("a/b/a.html"), StrL("a/b/c/b.html"), StrL("a.html"), StrL("c/b.html")},
        {StrL("abc/a.html"), StrL("abcd/b.html"), StrL("abc/a.html"), StrL("abcd/b.html")},
        {StrL("C:\\books\\a.html"), StrL("C:\\books\\b.html"), StrL("a.html"), StrL("b.html")},
        {StrL("dir/a.html"), {}, StrL("dir/a.html"), {}},
        {StrL("/"), StrL("x/b.html"), StrL("one"), StrL("x/b.html")},
    };
    for (const auto& c : cases) {
        ByteWriterLE raw(256);
        raw.Write8(1);
        raw.Write8('x');
        int count = len(c[1]) > 0 ? 2 : 1;
        raw.Write32(count);
        for (int i = 0; i < count; i++) {
            raw.Write32(0);
            const Str values[] = {i == 0 ? StrL("one") : StrL("two"), c[i], StrL("text/html")};
            for (Str value : values) {
                raw.Write8((u8)len(value));
                raw.d.Append(value);
            }
            raw.Write8(0);
        }
        for (int i = 1; i < kLitManifestGroups; i++) {
            raw.Write32(0);
        }
        LitFile lit;
        lit.d = ToStr(raw.d);
        LitEntry entry{};
        entry.name = StrL("/manifest");
        entry.size = len(lit.d);
        VecAppend(lit.entries, entry);
        if (!LitParseManifest(&lit) || len(lit.manifest) != count) {
            return false;
        }
        for (int i = 0; i < count; i++) {
            if (!str::Eq(lit.manifest[i].path, c[i + 2])) {
                return false;
            }
        }
    }
    return true;
}
#endif
