.\"Shiju P. Nair September 30, 2004
.TH WTPT 1 "September 30, 2004"
.SH NAME 
wtpt - Show media white of profiles, identifying black body locus.
.SH SYNOPSIS
.B wtpt
.RI [ profile ]
.SH DESCRIPTION
lcms is a standalone CMM engine, which deals with the color management.
It implements a fast transformation between ICC profiles.
.B wtpt 
shows media white of profiles, identifying black body locus.
.P
If no parameters are given, then this program will
ask for XYZ value of media white. If parameter given, it must be
the profile to inspect.
.SH NOTES
For suggestions, comments, bug reports etc. send mail to
info@littlecms.com
.SH SEE ALSO
.BR jpegicc (1),
.BR tifficc (1),
.BR icc2ps (1),
.BR icclink (1),
.BR icctrans (1)
.SH AUTHOR
This manual page was written by Shiju p. Nair <shiju.p@gmail.com>,
for the Debian project.
