// DON'T EDIT MANUALLY !!!!
// auto-generated by gen_txt.py !!!!

#include "BaseUtil.h"
#include "SerializeTxt.h"
#include "MuiScrollBarDef.h"

using namespace sertxt;

#define of offsetof
const FieldMetadata gScrollBarDefFieldMetadata[] = {
    { of(ScrollBarDef, name),   TYPE_STR, NULL },
    { of(ScrollBarDef, style),  TYPE_STR, NULL },
    { of(ScrollBarDef, cursor), TYPE_STR, NULL },
};

const StructMetadata gScrollBarDefMetadata = {
    sizeof(ScrollBarDef),
    3,
    "name\0style\0cursor\0\0",
    &gScrollBarDefFieldMetadata[0]
};

#undef of


