// DON'T EDIT MANUALLY !!!!
// auto-generated by gen_settings_bin.py !!!!

#ifndef SettingsBinSimple_h
#define SettingsBinSimple_h

namespace serbin {

struct Simple {
    bool           bTrue;
    bool           bFalse;
    uint16_t       u16_1;
    int32_t        i32_1;
    uint32_t       u32_1;
    uint64_t       u64_1;
    uint32_t       col_1;
    float          float_1;
    const char *   str_1;
    const char *   str_escape;
    const WCHAR *  wstr_1;
};

#define SimpleVersion "1.0"

Simple *DeserializeSimple(const uint8_t *data, int dataLen, bool *usedDefaultOut);
uint8_t *SerializeSimple(Simple *, int *dataLenOut);
void FreeSimple(Simple *);

} // namespace serbin
#endif
