// DON'T EDIT MANUALLY !!!!
// auto-generated by scripts/gen_settings.py !!!!

#include "BaseUtil.h"
#include "SerializeTxt.h"
#include "SettingsSumatra.h"

using namespace sertxt;

FieldMetadata gFavFieldMetadata[] = {
    { "name"      , TYPE_STR, offsetof(Fav, name), NULL },
    { "page_no"   , TYPE_I32, offsetof(Fav, pageNo), NULL },
    { "page_label", TYPE_STR, offsetof(Fav, pageLabel), NULL },
};

StructMetadata gFavMetadata = { sizeof(Fav), 3, &gFavFieldMetadata[0] };

FieldMetadata gForwardSearchFieldMetadata[] = {
    { "highlight_offset"       , TYPE_I32,   offsetof(ForwardSearch, highlightOffset), NULL },
    { "highlight_width"        , TYPE_I32,   offsetof(ForwardSearch, highlightWidth), NULL },
    { "highlight_permanent"    , TYPE_I32,   offsetof(ForwardSearch, highlightPermanent), NULL },
    { "highlight_color"        , TYPE_COLOR, offsetof(ForwardSearch, highlightColor), NULL },
    { "enable_tex_enhancements", TYPE_BOOL,  offsetof(ForwardSearch, enableTexEnhancements), NULL },
};

StructMetadata gForwardSearchMetadata = { sizeof(ForwardSearch), 5, &gForwardSearchFieldMetadata[0] };

FieldMetadata gPaddingSettingsFieldMetadata[] = {
    { "top"    , TYPE_U16, offsetof(PaddingSettings, top), NULL },
    { "bottom" , TYPE_U16, offsetof(PaddingSettings, bottom), NULL },
    { "left"   , TYPE_U16, offsetof(PaddingSettings, left), NULL },
    { "right"  , TYPE_U16, offsetof(PaddingSettings, right), NULL },
    { "space_x", TYPE_U16, offsetof(PaddingSettings, spaceX), NULL },
    { "space_y", TYPE_U16, offsetof(PaddingSettings, spaceY), NULL },
};

StructMetadata gPaddingSettingsMetadata = { sizeof(PaddingSettings), 6, &gPaddingSettingsFieldMetadata[0] };

FieldMetadata gRectIntFieldMetadata[] = {
    { "x" , TYPE_I32, offsetof(RectInt, x), NULL },
    { "y" , TYPE_I32, offsetof(RectInt, y), NULL },
    { "dx", TYPE_I32, offsetof(RectInt, dx), NULL },
    { "dy", TYPE_I32, offsetof(RectInt, dy), NULL },
};

StructMetadata gRectIntMetadata = { sizeof(RectInt), 4, &gRectIntFieldMetadata[0] };

FieldMetadata gAppStateFieldMetadata[] = {
    { "favorites", TYPE_ARRAY, offsetof(AppState, favorites), NULL },
};

StructMetadata gAppStateMetadata = { sizeof(AppState), 1, &gAppStateFieldMetadata[0] };

FieldMetadata gAdvancedSettingsFieldMetadata[] = {
    { "traditional_ebook_ui"  , TYPE_BOOL,       offsetof(AdvancedSettings, traditionalEbookUI), NULL },
    { "esc_to_exit"           , TYPE_BOOL,       offsetof(AdvancedSettings, escToExit), NULL },
    { "text_color"            , TYPE_COLOR,      offsetof(AdvancedSettings, textColor), NULL },
    { "page_color"            , TYPE_COLOR,      offsetof(AdvancedSettings, pageColor), NULL },
    { "main_window_background", TYPE_COLOR,      offsetof(AdvancedSettings, mainWindowBackground), NULL },
    { "page_padding"          , TYPE_STRUCT_PTR, offsetof(AdvancedSettings, pagePadding), &gPaddingSettingsMetadata },
    { "forward_search"        , TYPE_STRUCT_PTR, offsetof(AdvancedSettings, forwardSearch), &gForwardSearchMetadata },
    { "s"                     , TYPE_STR,        offsetof(AdvancedSettings, s), NULL },
    { "default_zoom"          , TYPE_FLOAT,      offsetof(AdvancedSettings, defaultZoom), NULL },
    { "ws"                    , TYPE_WSTR,       offsetof(AdvancedSettings, ws), NULL },
};

StructMetadata gAdvancedSettingsMetadata = { sizeof(AdvancedSettings), 10, &gAdvancedSettingsFieldMetadata[0] };

FieldMetadata gBasicSettingsFieldMetadata[] = {
    { "global_prefs_only"      , TYPE_BOOL,       offsetof(BasicSettings, globalPrefsOnly), NULL },
    { "curr_language"          , TYPE_STR,        offsetof(BasicSettings, currLanguage), NULL },
    { "toolbar_visible"        , TYPE_BOOL,       offsetof(BasicSettings, toolbarVisible), NULL },
    { "pdf_associate_dont_ask" , TYPE_BOOL,       offsetof(BasicSettings, pdfAssociateDontAsk), NULL },
    { "pdf_associate_do_it"    , TYPE_BOOL,       offsetof(BasicSettings, pdfAssociateDoIt), NULL },
    { "check_for_updates"      , TYPE_BOOL,       offsetof(BasicSettings, checkForUpdates), NULL },
    { "remember_mru_files"     , TYPE_BOOL,       offsetof(BasicSettings, rememberMruFiles), NULL },
    { "use_system_color_scheme", TYPE_BOOL,       offsetof(BasicSettings, useSystemColorScheme), NULL },
    { "inverse_search_cmd_line", TYPE_STR,        offsetof(BasicSettings, inverseSearchCmdLine), NULL },
    { "version_to_skip"        , TYPE_STR,        offsetof(BasicSettings, versionToSkip), NULL },
    { "last_update_time"       , TYPE_STR,        offsetof(BasicSettings, lastUpdateTime), NULL },
    { "default_display_mode"   , TYPE_U16,        offsetof(BasicSettings, defaultDisplayMode), NULL },
    { "default_zoom"           , TYPE_FLOAT,      offsetof(BasicSettings, defaultZoom), NULL },
    { "window_state"           , TYPE_I32,        offsetof(BasicSettings, windowState), NULL },
    { "window_pos"             , TYPE_STRUCT_PTR, offsetof(BasicSettings, windowPos), &gRectIntMetadata },
    { "toc_visible"            , TYPE_BOOL,       offsetof(BasicSettings, tocVisible), NULL },
    { "fav_visible"            , TYPE_BOOL,       offsetof(BasicSettings, favVisible), NULL },
    { "sidebar_dx"             , TYPE_I32,        offsetof(BasicSettings, sidebarDx), NULL },
    { "toc_dy"                 , TYPE_I32,        offsetof(BasicSettings, tocDy), NULL },
    { "show_start_page"        , TYPE_BOOL,       offsetof(BasicSettings, showStartPage), NULL },
    { "open_count_week"        , TYPE_I32,        offsetof(BasicSettings, openCountWeek), NULL },
    { "last_pref_update"       , TYPE_U64,        offsetof(BasicSettings, lastPrefUpdate), NULL },
};

StructMetadata gBasicSettingsMetadata = { sizeof(BasicSettings), 22, &gBasicSettingsFieldMetadata[0] };

FieldMetadata gSettingsFieldMetadata[] = {
    { "basic"    , TYPE_STRUCT_PTR, offsetof(Settings, basic), &gBasicSettingsMetadata },
    { "advanced" , TYPE_STRUCT_PTR, offsetof(Settings, advanced), &gAdvancedSettingsMetadata },
    { "app_state", TYPE_STRUCT_PTR, offsetof(Settings, appState), &gAppStateMetadata },
};

StructMetadata gSettingsMetadata = { sizeof(Settings), 3, &gSettingsFieldMetadata[0] };



Settings *DeserializeSettings(const uint8_t *data, int dataLen, bool *usedDefaultOut)
{
    void *res = NULL;
    res = Deserialize(data, dataLen, SettingsVersion, &gSettingsMetadata);
    if (res) {
        *usedDefaultOut = false;
        return (Settings*)res;
    }
    res = Deserialize(NULL, 0, SettingsVersion, &gSettingsMetadata);
    CrashAlwaysIf(!res);
    *usedDefaultOut = true;
    return (Settings*)res;
}

uint8_t *SerializeSettings(Settings *val, int *dataLenOut)
{
    return Serialize((const uint8_t*)val, SettingsVersion, &gSettingsMetadata, dataLenOut);
}

void FreeSettings(Settings *val)
{
    FreeStruct((uint8_t*)val, &gSettingsMetadata);
}


