import type { LibDef } from "./build-deps-common.ts";

// ── Library definitions ─────────────────────────────────────────────────────
// Each matches a project in premake5.lua / premake5.files.lua

export const zlib: LibDef = {
  name: "zlib",
  alwaysOptimize: true,
  defines: [],
  includes: [],
  files: [
    {
      dir: "ext/zlib",
      patterns: [
        "adler32.c",
        "compress.c",
        "crc32.c",
        "deflate.c",
        "inffast.c",
        "inflate.c",
        "inftrees.c",
        "trees.c",
        "zutil.c",
        "gzlib.c",
        "gzread.c",
        "gzwrite.c",
        "gzclose.c",
      ],
    },
  ],
};

export const unrar: LibDef = {
  name: "unrar",
  alwaysOptimize: true,
  // MSVC compiles throw/catch with exceptions disabled (warning 4530);
  // GCC requires -fexceptions for code that uses throw/catch
  exceptions: true,
  defines: ["UNRAR", "RARDLL", "SILENT"],
  includes: ["ext/unrar"],
  files: [
    {
      dir: "ext/unrar",
      patterns: [
        "archive.cpp",
        "arcread.cpp",
        "blake2s.cpp",
        "cmddata.cpp",
        "consio.cpp",
        "crc.cpp",
        "crypt.cpp",
        "dll.cpp",
        "encname.cpp",
        "errhnd.cpp",
        "extinfo.cpp",
        "extract.cpp",
        "filcreat.cpp",
        "file.cpp",
        "filefn.cpp",
        "filestr.cpp",
        "find.cpp",
        "getbits.cpp",
        "global.cpp",
        "hash.cpp",
        "headers.cpp",
        "isnt.cpp",
        "largepage.cpp",
        "list.cpp",
        "match.cpp",
        "motw.cpp",
        "options.cpp",
        "pathfn.cpp",
        "qopen.cpp",
        "rarvm.cpp",
        "rawread.cpp",
        "rdwrfn.cpp",
        "recvol.cpp",
        "rijndael.cpp",
        "rs.cpp",
        "rs16.cpp",
        "scantree.cpp",
        "secpassword.cpp",
        "sha1.cpp",
        "sha256.cpp",
        "smallfn.cpp",
        "strfn.cpp",
        "strlist.cpp",
        "system.cpp",
        "threadpool.cpp",
        "timefn.cpp",
        "ui.cpp",
        "unicode.cpp",
        "unpack.cpp",
        "volume.cpp",
      ],
    },
  ],
};

export const libdjvu: LibDef = {
  name: "libdjvu",
  alwaysOptimize: true,
  // libdjvu uses exceptions (GException.cpp, etc.)
  exceptions: true,
  defines: [
    "_CRT_SECURE_NO_WARNINGS",
    "NEED_JPEG_DECODER",
    "WINTHREADS=1",
    "DDJVUAPI=",
    "MINILISPAPI=",
    "DEBUGLVL=0",
    "DISABLE_MMX",
  ],
  includes: ["ext/libjpeg-turbo/src"],
  files: [
    {
      dir: "ext/libdjvu",
      patterns: [
        "Arrays.cpp",
        "atomic.cpp",
        "BSByteStream.cpp",
        "BSEncodeByteStream.cpp",
        "ByteStream.cpp",
        "DataPool.cpp",
        "DjVmDir0.cpp",
        "DjVmDoc.cpp",
        "DjVmNav.cpp",
        "DjVuAnno.cpp",
        "DjVuDocEditor.cpp",
        "DjVuDocument.cpp",
        "DjVuDumpHelper.cpp",
        "DjVuErrorList.cpp",
        "DjVuFile.cpp",
        "DjVuFileCache.cpp",
        "DjVuGlobal.cpp",
        "DjVuGlobalMemory.cpp",
        "DjVuImage.cpp",
        "DjVuInfo.cpp",
        "DjVuMessage.cpp",
        "DjVuMessageLite.cpp",
        "DjVuNavDir.cpp",
        "DjVuPalette.cpp",
        "DjVuPort.cpp",
        "DjVuText.cpp",
        "DjVuToPS.cpp",
        "GBitmap.cpp",
        "GContainer.cpp",
        "GException.cpp",
        "GIFFManager.cpp",
        "GMapAreas.cpp",
        "GOS.cpp",
        "GPixmap.cpp",
        "GRect.cpp",
        "GScaler.cpp",
        "GSmartPointer.cpp",
        "GString.cpp",
        "GThreads.cpp",
        "GUnicode.cpp",
        "GURL.cpp",
        "IFFByteStream.cpp",
        "IW44EncodeCodec.cpp",
        "IW44Image.cpp",
        "JB2EncodeCodec.cpp",
        "DjVmDir.cpp",
        "JB2Image.cpp",
        "JPEGDecoder.cpp",
        "MMRDecoder.cpp",
        "MMX.cpp",
        "UnicodeByteStream.cpp",
        "XMLParser.cpp",
        "XMLTags.cpp",
        "ZPCodec.cpp",
        "ddjvuapi.cpp",
        "debug.cpp",
        "miniexp.cpp",
      ],
    },
  ],
};

export const chm: LibDef = {
  name: "chm",
  alwaysOptimize: true,
  defines: ["_CRT_SECURE_NO_WARNINGS"],
  includes: [],
  files: [{ dir: "ext/CHMLib", patterns: ["chm_lib.c", "lzx.c"] }],
};

export const libarchive: LibDef = {
  name: "libarchive",
  alwaysOptimize: true,
  defines: [
    "_CRT_SECURE_NO_WARNINGS",
    "LIBARCHIVE_STATIC",
    'PLATFORM_CONFIG_H="config_windows.h"',
    "BZ_NO_STDIO",
    "HAVE_CONFIG_H",
    "LZMA_API_STATIC",
  ],
  includes: [
    "ext/libarchive/libarchive",
    "ext/libarchive",
    "ext/zlib",
    "ext/bzip2",
    "ext/lzma/C",
    "ext/liblzma/api",
    "ext/liblzma/common",
    "ext/liblzma/check",
    "ext/liblzma/delta",
    "ext/liblzma/lz",
    "ext/liblzma/lzma",
    "ext/liblzma/rangecoder",
    "ext/liblzma/simple",
    "ext/liblzma",
  ],
  files: [
    {
      dir: "ext/libarchive/libarchive",
      patterns: [
        "archive_acl.c",
        "archive_check_magic.c",
        "archive_cmdline.c",
        "archive_cryptor.c",
        "archive_digest.c",
        "archive_entry.c",
        "archive_entry_copy_bhfi.c",
        "archive_entry_copy_stat.c",
        "archive_entry_link_resolver.c",
        "archive_entry_sparse.c",
        "archive_entry_stat.c",
        "archive_entry_strmode.c",
        "archive_entry_xattr.c",
        "archive_hmac.c",
        "archive_match.c",
        "archive_options.c",
        "archive_pack_dev.c",
        "archive_pathmatch.c",
        "archive_ppmd7.c",
        "archive_ppmd8.c",
        "archive_random.c",
        "archive_rb.c",
        "archive_string.c",
        "archive_string_sprintf.c",
        "archive_time.c",
        "archive_util.c",
        "archive_version_details.c",
        "archive_virtual.c",
        "archive_windows.c",
        "archive_blake2s_ref.c",
        "archive_blake2sp_ref.c",
        "archive_read.c",
        "archive_read_add_passphrase.c",
        "archive_read_append_filter.c",
        "archive_read_data_into_fd.c",
        "archive_read_extract.c",
        "archive_read_extract2.c",
        "archive_read_open_fd.c",
        "archive_read_open_file.c",
        "archive_read_open_filename.c",
        "archive_read_open_memory.c",
        "archive_read_set_format.c",
        "archive_read_set_options.c",
        "archive_read_support_filter_all.c",
        "archive_read_support_filter_by_code.c",
        "archive_read_support_filter_bzip2.c",
        "archive_read_support_filter_compress.c",
        "archive_read_support_filter_grzip.c",
        "archive_read_support_filter_gzip.c",
        "archive_read_support_filter_lrzip.c",
        "archive_read_support_filter_lz4.c",
        "archive_read_support_filter_lzop.c",
        "archive_read_support_filter_none.c",
        "archive_read_support_filter_program.c",
        "archive_read_support_filter_rpm.c",
        "archive_read_support_filter_uu.c",
        "archive_read_support_filter_xz.c",
        "archive_read_support_filter_zstd.c",
        "archive_read_support_format_7zip.c",
        "archive_read_support_format_all.c",
        "archive_read_support_format_ar.c",
        "archive_read_support_format_by_code.c",
        "archive_read_support_format_cab.c",
        "archive_read_support_format_cpio.c",
        "archive_read_support_format_empty.c",
        "archive_read_support_format_iso9660.c",
        "archive_read_support_format_lha.c",
        "archive_read_support_format_mtree.c",
        "archive_read_support_format_rar.c",
        "archive_read_support_format_rar5.c",
        "archive_read_support_format_raw.c",
        "archive_read_support_format_tar.c",
        "archive_read_support_format_warc.c",
        "archive_read_support_format_xar.c",
        "archive_read_support_format_zip.c",
        "archive_read_disk_set_standard_lookup.c",
        "archive_read_disk_windows.c",
        "archive_parse_date.c",
        "filter_fork_windows.c",
        "xxhash.c",
      ],
    },
    {
      dir: "ext/bzip2",
      patterns: [
        "blocksort.c",
        "bzlib.c",
        "bz_internal_error.c",
        "compress.c",
        "crctable.c",
        "decompress.c",
        "huffman.c",
        "randtable.c",
      ],
    },
    {
      dir: "ext/lzma/C",
      patterns: ["LzmaDec.c", "Bra86.c", "Bra.c"],
    },
    {
      dir: "ext/liblzma",
      patterns: [
        "common/alone_decoder.c",
        "common/auto_decoder.c",
        "common/block_decoder.c",
        "common/block_header_decoder.c",
        "common/block_util.c",
        "common/common.c",
        "common/filter_common.c",
        "common/filter_decoder.c",
        "common/filter_flags_decoder.c",
        "common/index.c",
        "common/index_decoder.c",
        "common/index_hash.c",
        "common/stream_decoder.c",
        "common/stream_flags_common.c",
        "common/stream_flags_decoder.c",
        "common/vli_decoder.c",
        "common/vli_size.c",
        "check/check.c",
        "check/crc32_fast.c",
        "check/crc64_fast.c",
        "lz/lz_decoder.c",
        "lzma/lzma_decoder.c",
        "lzma/lzma2_decoder.c",
        "rangecoder/price_table.c",
        "delta/delta_common.c",
        "delta/delta_decoder.c",
        "simple/simple_coder.c",
        "simple/simple_decoder.c",
        "simple/x86.c",
      ],
    },
  ],
};

export const libwebp: LibDef = {
  name: "libwebp",
  alwaysOptimize: true,
  defines: [],
  includes: ["ext/libwebp"],
  files: [
    { dir: "ext/libwebp/src/dec", patterns: ["*.c"] },
    {
      dir: "ext/libwebp/src/dsp",
      patterns: [
        "alpha_processing.c",
        "alpha_processing_sse2.c",
        "alpha_processing_sse41.c",
        "alpha_processing_neon.c",
        "cost.c",
        "cpu.c",
        "dec.c",
        "dec_clip_tables.c",
        "dec_sse2.c",
        "dec_sse41.c",
        "dec_neon.c",
        "filters.c",
        "filters_sse2.c",
        "filters_neon.c",
        "lossless.c",
        "lossless_sse2.c",
        "lossless_sse41.c",
        "lossless_avx2.c",
        "lossless_neon.c",
        "rescaler.c",
        "rescaler_sse2.c",
        "rescaler_neon.c",
        "ssim.c",
        "ssim_sse2.c",
        "upsampling.c",
        "upsampling_sse2.c",
        "upsampling_sse41.c",
        "upsampling_neon.c",
        "yuv.c",
        "yuv_sse2.c",
        "yuv_sse41.c",
        "yuv_neon.c",
      ],
    },
    { dir: "ext/libwebp/src/sharpyuv", patterns: ["*.c"] },
    { dir: "ext/libwebp/src/utils", patterns: ["*.c"] },
  ],
};

export const dav1d: LibDef = {
  name: "dav1d",
  alwaysOptimize: true,
  defines: ["_CRT_SECURE_NO_WARNINGS", "ARCH_X86_32=0", "ARCH_X86_64=1", "HAVE_ASM=0"],
  // NOTE: do NOT include ext/dav1d/include/compat/msvc — it shadows GCC's
  // native <stdatomic.h> with an MSVC-only version
  includes: ["ext/dav1d", "ext/dav1d/include"],
  files: [
    {
      dir: "ext/dav1d/src",
      patterns: [
        "lib.c",
        "thread_task.c",
        "cdf.c",
        "cpu.c",
        "ctx.c",
        "data.c",
        "decode.c",
        "dequant_tables.c",
        "getbits.c",
        "intra_edge.c",
        "itx_1d.c",
        "lf_mask.c",
        "log.c",
        "mem.c",
        "msac.c",
        "obu.c",
        "pal.c",
        "picture.c",
        "qm.c",
        "ref.c",
        "refmvs.c",
        "scan.c",
        "tables.c",
        "warpmv.c",
        "wedge.c",
        "win32/thread.c",
        "sumatra_bitdepth_8.c",
        "sumatra_bitdepth_8_2.c",
        "sumatra_bitdepth_16.c",
        "sumatra_bitdepth_16_2.c",
      ],
    },
    // x86 C files — only cpu.c; skip msac_init.c and refmvs_init.c as they
    // reference asm symbols and we build with HAVE_ASM=0 (no NASM)
    {
      dir: "ext/dav1d/src/x86",
      patterns: ["cpu.c"],
    },
  ],
};

export const skcms: LibDef = {
  name: "skcms",
  alwaysOptimize: true,
  defines: ["SKCMS_DISABLE_HSW", "SKCMS_DISABLE_SKX"],
  includes: ["ext/skcms"],
  files: [
    { dir: "ext/skcms", patterns: ["skcms.cc"] },
    { dir: "ext/skcms/src", patterns: ["skcms_TransformBaseline.cc"] },
  ],
};

export const highway: LibDef = {
  name: "highway",
  alwaysOptimize: true,
  defines: [],
  includes: ["ext/highway"],
  rtti: true,
  exceptions: true,
  files: [{ dir: "ext/highway/hwy", patterns: ["*.cc"] }],
};

export const libjxl: LibDef = {
  name: "libjxl",
  alwaysOptimize: true,
  rtti: true,
  exceptions: true,
  defines: [
    "JPEGXL_ENABLE_SKCMS=1",
    "JPEGXL_ENABLE_TRANSCODE_JPEG=0",
    "JPEGXL_BUNDLING_LIBJXL=1",
    "_CRT_SECURE_NO_WARNINGS",
  ],
  includes: ["ext/libjxl", "ext/libjxl/lib/include", "ext/highway", "ext/skcms", "ext/brotli/c/include"],
  files: [{ dir: "ext/libjxl/lib/jxl", patterns: ["**/*.cc"] }],
};

export const libheif: LibDef = {
  name: "libheif",
  alwaysOptimize: true,
  rtti: true,
  exceptions: true,
  defines: ["_CRT_SECURE_NO_WARNINGS", "HAVE_DAV1D", "LIBHEIF_STATIC_BUILD"],
  includes: ["ext/libheif/libheif", "ext/libheif/libheif/api", "ext/dav1d/include"],
  files: [
    {
      dir: "ext/libheif/libheif",
      patterns: [
        "bitstream.*",
        "box.*",
        "brands.*",
        "common_utils.*",
        "context.*",
        "error.*",
        "file.*",
        "file_layout.*",
        "id_creator.*",
        "init.*",
        "logging.*",
        "mini.*",
        "nclx.*",
        "omaf_boxes.*",
        "plugin_registry.*",
        "region.*",
        "security_limits.*",
        "text.*",
      ],
    },
    {
      dir: "ext/libheif/libheif/image",
      patterns: ["image_description.*", "pixelimage.*"],
    },
    {
      dir: "ext/libheif/libheif/image-items",
      patterns: [
        "avc.*",
        "avif.*",
        "grid.*",
        "hevc.*",
        "iden.*",
        "image_item.*",
        "jpeg.*",
        "jpeg2000.*",
        "mask_image.*",
        "overlay.*",
        "tiled.*",
        "vvc.*",
      ],
    },
    {
      dir: "ext/libheif/libheif/codecs",
      patterns: [
        "avif_boxes.*",
        "avif_dec.*",
        "avif_enc.*",
        "avc_boxes.*",
        "avc_dec.*",
        "avc_enc.*",
        "decoder.*",
        "encoder.*",
        "hevc_boxes.*",
        "hevc_dec.*",
        "hevc_enc.*",
        "jpeg_boxes.*",
        "jpeg_dec.*",
        "jpeg_enc.*",
        "jpeg2000_boxes.*",
        "jpeg2000_dec.*",
        "jpeg2000_enc.*",
        "vvc_boxes.*",
        "vvc_enc.*",
        "vvc_dec.*",
      ],
    },
    {
      dir: "ext/libheif/libheif/color-conversion",
      patterns: [
        "alpha.*",
        "bayer_bilinear.*",
        "chroma_sampling.*",
        "colorconversion.*",
        "hdr_sdr.*",
        "monochrome.*",
        "rgb2yuv.*",
        "rgb2yuv_sharp.*",
        "rgb2rgb.*",
        "yuv2rgb.*",
      ],
    },
    {
      dir: "ext/libheif/libheif/plugins",
      patterns: ["decoder_dav1d.*", "encoder_mask.*"],
    },
    {
      dir: "ext/libheif/libheif/sequences",
      patterns: ["chunk.*", "seq_boxes.*", "track.*", "track_metadata.*", "track_visual.*"],
    },
    {
      dir: "ext/libheif/libheif/api/libheif",
      patterns: [
        "heif.*",
        "heif_brands.*",
        "heif_color.*",
        "heif_context.*",
        "heif_decoding.*",
        "heif_encoding.*",
        "heif_image.*",
        "heif_image_handle.*",
        "heif_plugin.*",
        "heif_security.*",
        "heif_sequences.*",
        "heif_tai_timestamps.*",
      ],
    },
  ],
};

// mupdf-libs: combined library (libjpeg-turbo + jbig2dec + openjpeg + freetype
// + lcms2 + harfbuzz + mujs + gumbo + extract + brotli)
export const mupdfLibs: LibDef = {
  name: "mupdf-libs",
  alwaysOptimize: true,
  defines: [
    "_CRT_SECURE_NO_WARNINGS",
    // jbig2dec
    "HAVE_STRING_H=1",
    "JBIG_NO_MEMENTO",
    // openjpeg
    "USE_JPIP",
    "OPJ_STATIC",
    "OPJ_EXPORTS",
    // freetype
    "FT2_BUILD_LIBRARY",
    'FT_CONFIG_MODULES_H="slimftmodules.h"',
    'FT_CONFIG_OPTIONS_H="slimftoptions.h"',
    "FT_CONFIG_OPTION_USE_BROTLI",
    // harfbuzz
    "HAVE_FALLBACK=1",
    "HAVE_OT",
    "HAVE_UCDN",
    "HAVE_FREETYPE",
    // libheif interop
    "LIBHEIF_STATIC_BUILD",
    // libjpeg-turbo: this build does not assemble the NASM SIMD sources, so
    // force the pure-C code path (no jsimd_* references).
    "WITHOUT_SIMD",
  ],
  includes: [
    "ext/libjpeg-turbo/src",
    "ext/jbig2dec",
    "mupdf/scripts/freetype",
    "ext/freetype/include",
    "ext/lcms2/include",
    "ext/harfbuzz/src/hb-ucdn",
    "ext/mujs",
    "ext/gumbo-parser/include",
    "ext/gumbo-parser/visualc/include",
    "ext/extract/include",
    "ext/brotli/c/include",
    "ext/zlib",
  ],
  // plain malloc/free wrappers (ext/mupdf_load_system_font.c) so that harfbuzz
  // allocations don't depend on mupdf's thread-local fz_hb_secret context
  // being set; HAVE_ATEXIT (frees harfbuzz singletons at exit) is debug-only,
  // it only matters for leak detection
  debugExtraDefines: [
    "HAVE_ATEXIT",
    "hb_malloc_impl=sumatra_hb_malloc",
    "hb_calloc_impl=sumatra_hb_calloc",
    "hb_realloc_impl=sumatra_hb_realloc",
    "hb_free_impl=sumatra_hb_free",
  ],
  releaseExtraDefines: [
    "hb_malloc_impl=sumatra_hb_malloc",
    "hb_calloc_impl=sumatra_hb_calloc",
    "hb_realloc_impl=sumatra_hb_realloc",
    "hb_free_impl=sumatra_hb_free",
  ],
  files: [
    // ── libjpeg-turbo 3.x: core (precision-independent) sources.
    //    NASM SIMD is skipped here; WITHOUT_SIMD forces the pure-C path. ──
    {
      dir: "ext/libjpeg-turbo/src",
      patterns: [
        "jaricom.c",
        "jcapimin.c",
        "jcarith.c",
        "jchuff.c",
        "jcicc.c",
        "jcinit.c",
        "jclhuff.c",
        "jcmarker.c",
        "jcmaster.c",
        "jcomapi.c",
        "jcparam.c",
        "jcphuff.c",
        "jctrans.c",
        "jdapimin.c",
        "jdarith.c",
        "jdatadst.c",
        "jdatasrc.c",
        "jdhuff.c",
        "jdicc.c",
        "jdinput.c",
        "jdlhuff.c",
        "jdmarker.c",
        "jdmaster.c",
        "jdphuff.c",
        "jdtrans.c",
        "jerror.c",
        "jfdctflt.c",
        "jmemmgr.c",
        "jmemnobs.c",
        "jpeg_nbits.c",
      ],
    },
    // ── libjpeg-turbo 3.x: per-precision wrappers (8/12/16-bit) ──
    {
      dir: "ext/libjpeg-turbo/src/wrapper",
      patterns: [
        "jcapistd-8.c", "jcapistd-12.c", "jcapistd-16.c",
        "jccoefct-8.c", "jccoefct-12.c",
        "jccolor-8.c", "jccolor-12.c", "jccolor-16.c",
        "jcdctmgr-8.c", "jcdctmgr-12.c",
        "jcdiffct-8.c", "jcdiffct-12.c", "jcdiffct-16.c",
        "jclossls-8.c", "jclossls-12.c", "jclossls-16.c",
        "jcmainct-8.c", "jcmainct-12.c", "jcmainct-16.c",
        "jcprepct-8.c", "jcprepct-12.c", "jcprepct-16.c",
        "jcsample-8.c", "jcsample-12.c", "jcsample-16.c",
        "jdapistd-8.c", "jdapistd-12.c", "jdapistd-16.c",
        "jdcoefct-8.c", "jdcoefct-12.c",
        "jdcolor-8.c", "jdcolor-12.c", "jdcolor-16.c",
        "jddctmgr-8.c", "jddctmgr-12.c",
        "jddiffct-8.c", "jddiffct-12.c", "jddiffct-16.c",
        "jdlossls-8.c", "jdlossls-12.c", "jdlossls-16.c",
        "jdmainct-8.c", "jdmainct-12.c", "jdmainct-16.c",
        "jdmerge-8.c", "jdmerge-12.c",
        "jdpostct-8.c", "jdpostct-12.c", "jdpostct-16.c",
        "jdsample-8.c", "jdsample-12.c", "jdsample-16.c",
        "jfdctfst-8.c", "jfdctfst-12.c",
        "jfdctint-8.c", "jfdctint-12.c",
        "jidctflt-8.c", "jidctflt-12.c",
        "jidctfst-8.c", "jidctfst-12.c",
        "jidctint-8.c", "jidctint-12.c",
        "jidctred-8.c", "jidctred-12.c",
        "jquant1-8.c", "jquant1-12.c",
        "jquant2-8.c", "jquant2-12.c",
        "jutils-8.c", "jutils-12.c", "jutils-16.c",
      ],
    },
    // ── jbig2dec ──
    {
      dir: "ext/jbig2dec",
      patterns: [
        "jbig2.c",
        "jbig2_arith.c",
        "jbig2_arith_iaid.c",
        "jbig2_arith_int.c",
        "jbig2_generic.c",
        "jbig2_huffman.c",
        "jbig2_hufftab.c",
        "jbig2_halftone.c",
        "jbig2_image.c",
        "jbig2_mmr.c",
        "jbig2_page.c",
        "jbig2_refinement.c",
        "jbig2_segment.c",
        "jbig2_symbol_dict.c",
        "jbig2_text.c",
      ],
    },
    // ── openjpeg ──
    {
      dir: "ext/openjpeg/src/lib/openjp2",
      patterns: [
        "bio.c",
        "cidx_manager.c",
        "cio.c",
        "dwt.c",
        "event.c",
        "function_list.c",
        "ht_dec.c",
        "image.c",
        "invert.c",
        "j2k.c",
        "jp2.c",
        "mct.c",
        "mqc.c",
        "openjpeg.c",
        "opj_clock.c",
        "phix_manager.c",
        "pi.c",
        "ppix_manager.c",
        "sparse_array.c",
        "t1.c",
        "t2.c",
        "tcd.c",
        "tgt.c",
        "thix_manager.c",
        "thread.c",
        "tpix_manager.c",
      ],
    },
    // ── freetype ──
    {
      dir: "ext/freetype/src/base",
      patterns: [
        "ftbase.c",
        "ftbbox.c",
        "ftbitmap.c",
        "ftdebug.c",
        "ftfstype.c",
        "ftgasp.c",
        "ftglyph.c",
        "ftinit.c",
        "ftstroke.c",
        "ftsynth.c",
        "ftsystem.c",
        "fttype1.c",
        "ftotval.c",
      ],
    },
    {
      dir: "ext/freetype/src",
      patterns: [
        "gzip/ftgzip.c",
        "cff/cff.c",
        "psaux/psaux.c",
        "pshinter/pshinter.c",
        "psnames/psnames.c",
        "raster/raster.c",
        "sfnt/sfnt.c",
        "smooth/smooth.c",
        "truetype/truetype.c",
        "type1/type1.c",
        "cid/type1cid.c",
      ],
    },
    // ── lcms2 ──
    { dir: "ext/lcms2/src", patterns: ["*.c"] },
    // ── harfbuzz (.cc files) ──
    {
      dir: "ext/harfbuzz/src",
      patterns: [
        "OT/Var/VARC/VARC.cc",
        "hb-aat-layout.cc",
        "hb-aat-map.cc",
        "hb-blob.cc",
        "hb-buffer.cc",
        "hb-buffer-verify.cc",
        "hb-buffer-serialize.cc",
        "hb-common.cc",
        "hb-draw.cc",
        "hb-face.cc",
        "hb-face-builder.cc",
        "hb-fallback-shape.cc",
        "hb-font.cc",
        "hb-ft.cc",
        "hb-map.cc",
        "hb-number.cc",
        "hb-ot-cff1-table.cc",
        "hb-ot-cff2-table.cc",
        "hb-ot-color.cc",
        "hb-ot-face.cc",
        "hb-ot-font.cc",
        "hb-ot-layout.cc",
        "hb-ot-map.cc",
        "hb-ot-math.cc",
        "hb-ot-meta.cc",
        "hb-ot-metrics.cc",
        "hb-ot-name.cc",
        "hb-ot-shape.cc",
        "hb-ot-shaper-arabic.cc",
        "hb-ot-shaper-default.cc",
        "hb-ot-shaper-hangul.cc",
        "hb-ot-shaper-hebrew.cc",
        "hb-ot-shaper-indic-table.cc",
        "hb-ot-shaper-indic.cc",
        "hb-ot-shaper-khmer.cc",
        "hb-ot-shaper-myanmar.cc",
        "hb-ot-shaper-syllabic.cc",
        "hb-ot-shaper-thai.cc",
        "hb-ot-shaper-use.cc",
        "hb-ot-shaper-vowel-constraints.cc",
        "hb-ot-shape-fallback.cc",
        "hb-ot-shape-normalize.cc",
        "hb-ot-tag.cc",
        "hb-ot-var.cc",
        "hb-outline.cc",
        "hb-paint.cc",
        "hb-paint-bounded.cc",
        "hb-paint-extents.cc",
        "hb-set.cc",
        "hb-shape.cc",
        "hb-shape-plan.cc",
        "hb-shaper.cc",
        "hb-static.cc",
        "hb-unicode.cc",
        "hb-subset-cff-common.cc",
        "hb-subset-cff1.cc",
        "hb-subset-cff2-to-cff1.cc",
        "hb-subset-cff2.cc",
        "hb-subset-input.cc",
        "hb-subset-instancer-iup.cc",
        "hb-subset-instancer-solver.cc",
        "hb-subset-plan-layout.cc",
        "hb-subset-plan-var.cc",
        "hb-subset-plan.cc",
        "hb-subset-serialize.cc",
        "hb-subset-table-cff.cc",
        "hb-subset-table-color.cc",
        "hb-subset-table-layout.cc",
        "hb-subset-table-other.cc",
        "hb-subset-table-var.cc",
        "hb-subset.cc",
        "hb-ucd.cc",
      ],
    },
    // ── mujs ──
    { dir: "ext/mujs", patterns: ["one.c"] },
    // ── gumbo ──
    { dir: "ext/gumbo-parser/src", patterns: ["*.c"] },
    // ── extract ──
    {
      dir: "ext/extract/src",
      patterns: [
        "alloc.c",
        "astring.c",
        "boxer.c",
        "buffer.c",
        "document.c",
        "docx.c",
        "docx_template.c",
        "extract.c",
        "html.c",
        "join.c",
        "json.c",
        "mem.c",
        "memento.c",
        "odt_template.c",
        "odt.c",
        "outf.c",
        "rect.c",
        "sys.c",
        "text.c",
        "xml.c",
        "zip.c",
      ],
    },
    // ── brotli ──
    { dir: "ext/brotli/c/common", patterns: ["*.c"] },
    { dir: "ext/brotli/c/dec", patterns: ["*.c"] },
    { dir: "ext/brotli/c/enc", patterns: ["*.c"] },
  ],
};

// mupdf core library (mixed debug/release optimization)
export const mupdf: LibDef = {
  name: "mupdf",
  alwaysOptimize: false,
  // deskew.c/skew.c use SSE4.1 intrinsics
  extraCflags: ["-msse4.1"],
  defines: [
    "USE_JPIP",
    "OPJ_EXPORTS",
    "HAVE_LCMS2MT=1",
    "OPJ_STATIC",
    "SHARE_JPEG",
    "TOFU_NOTO",
    "TOFU_CJK_LANG",
    "TOFU_NOTO_SUMATRA",
    "FZ_ENABLE_SVG=1",
    "FZ_ENABLE_BROTLI=1",
    "FZ_ENABLE_BARCODE=0",
    "FZ_ENABLE_JS=1",
    "FZ_ENABLE_HYPHEN=0",
  ],
  includes: [
    "mupdf/include",
    "mupdf/generated",
    "ext/jbig2dec",
    "ext/libjpeg-turbo/src",
    "ext/openjpeg/src/lib/openjp2",
    "mupdf/scripts/freetype",
    "ext/freetype/include",
    "ext/mujs",
    "ext/brotli/c/include",
    "ext/harfbuzz/src",
    "ext/lcms2/include",
    "ext/gumbo-parser/src",
    "ext/extract/include",
    "ext/zlib",
    "ext/libarchive",
  ],
  files: [
    { dir: "ext", patterns: ["mupdf_load_system_font.c"] },
    { dir: "mupdf/source/cbz", patterns: ["mucbz.c", "muimg.c"] },
    {
      dir: "mupdf/source/fitz",
      patterns: [
        "archive.c",
        "barcode.c",
        "bbox-device.c",
        "bidi.c",
        "bidi-std.c",
        "bitmap.c",
        "brotli.c",
        "buffer.c",
        "color-fast.c",
        "color-icc-create.c",
        "color-lcms.c",
        "colorspace.c",
        "compress.c",
        "compressed-buffer.c",
        "context.c",
        "crypt-aes.c",
        "crypt-arc4.c",
        "crypt-md5.c",
        "crypt-sha2.c",
        "deskew.c",
        "device.c",
        "directory.c",
        "document.c",
        "document-all.c",
        "draw-affine.c",
        "draw-blend.c",
        "draw-device.c",
        "draw-edge.c",
        "draw-edgebuffer.c",
        "draw-glyph.c",
        "draw-mesh.c",
        "draw-paint.c",
        "draw-path.c",
        "draw-rasterize.c",
        "draw-scale-simple.c",
        "draw-unpack.c",
        "encode-basic.c",
        "encode-fax.c",
        "encode-jpx.c",
        "encodings.c",
        "error.c",
        "filter-basic.c",
        "filter-brotli.c",
        "filter-dct.c",
        "filter-fax.c",
        "filter-flate.c",
        "filter-jbig2.c",
        "filter-leech.c",
        "filter-lzw.c",
        "filter-predict.c",
        "filter-sgi.c",
        "filter-thunder.c",
        "font.c",
        "ftoa.c",
        "geometry.c",
        "getopt.c",
        "glyph.c",
        "glyphbox.c",
        "gz-doc.c",
        "halftone.c",
        "harfbuzz.c",
        "hash.c",
        "heap.c",
        "hyphen.c",
        "image.c",
        "jmemcust.c",
        "json.c",
        "link.c",
        "list-device.c",
        "load-bmp.c",
        "load-gif.c",
        "load-jbig2.c",
        "load-jpeg.c",
        "load-jpx.c",
        "load-jxr-win.c",
        "load-png.c",
        "load-pnm.c",
        "load-psd.c",
        "load-tiff.c",
        "log.c",
        "memento.c",
        "memory.c",
        "noto.c",
        "ocr-device.c",
        "outline.c",
        "output.c",
        "output-cbz.c",
        "output-csv.c",
        "output-docx.c",
        "output-jpeg.c",
        "output-pcl.c",
        "output-pclm.c",
        "output-pdfocr.c",
        "output-png.c",
        "output-pnm.c",
        "output-ps.c",
        "output-psd.c",
        "output-pwg.c",
        "output-svg.c",
        "path.c",
        "pixmap.c",
        "pool.c",
        "printf.c",
        "random.c",
        "skew.c",
        "separation.c",
        "shade.c",
        "stext-boxer.c",
        "stext-classify.c",
        "stext-device.c",
        "stext-iterator.c",
        "stext-output.c",
        "stext-para.c",
        "stext-raft.c",
        "stext-search.c",
        "stext-table.c",
        "store.c",
        "stream-open.c",
        "stream-read.c",
        "string.c",
        "strtof.c",
        "svg-device.c",
        "test-device.c",
        "text.c",
        "text-decoder.c",
        "time.c",
        "trace-device.c",
        "track-usage.c",
        "transition.c",
        "tree.c",
        "ucdn.c",
        "uncfb.c",
        "unlibarchive.c",
        "subset-cff.c",
        "subset-ttf.c",
        "untar.c",
        "unzip.c",
        "util.c",
        "warp.c",
        "writer.c",
        "xml-write.c",
        "xml.c",
        "xmltext-device.c",
        "zip.c",
      ],
    },
    {
      dir: "mupdf/source/html",
      patterns: [
        "css-apply.c",
        "css-parse.c",
        "epub-doc.c",
        "html-doc.c",
        "html-font.c",
        "html-layout.c",
        "html-outline.c",
        "html-parse.c",
        "mobi.c",
        "office.c",
        "story-writer.c",
        "txt.c",
        "xml-dom.c",
      ],
    },
    {
      dir: "mupdf/source/pdf",
      patterns: [
        "pdf-af.c",
        "pdf-annot.c",
        "pdf-appearance.c",
        "pdf-clean.c",
        "pdf-clean-file.c",
        "pdf-cmap.c",
        "pdf-cmap-load.c",
        "pdf-cmap-parse.c",
        "pdf-colorspace.c",
        "pdf-crypt.c",
        "pdf-device.c",
        "pdf-event.c",
        "pdf-font.c",
        "pdf-font-add.c",
        "pdf-form.c",
        "pdf-function.c",
        "pdf-graft.c",
        "pdf-image.c",
        "pdf-image-rewriter.c",
        "pdf-interpret.c",
        "pdf-js.c",
        "pdf-label.c",
        "pdf-layer.c",
        "pdf-layout.c",
        "pdf-lex.c",
        "pdf-link.c",
        "pdf-metrics.c",
        "pdf-nametree.c",
        "pdf-object.c",
        "pdf-op-buffer.c",
        "pdf-op-color.c",
        "pdf-op-filter.c",
        "pdf-op-run.c",
        "pdf-op-vectorize.c",
        "pdf-outline.c",
        "pdf-page.c",
        "pdf-parse.c",
        "pdf-pattern.c",
        "pdf-recolor.c",
        "pdf-repair.c",
        "pdf-resources.c",
        "pdf-run.c",
        "pdf-shade.c",
        "pdf-shade-recolor.c",
        "pdf-signature.c",
        "pdf-store.c",
        "pdf-stream.c",
        "pdf-subset.c",
        "pdf-type3.c",
        "pdf-unicode.c",
        "pdf-util.c",
        "pdf-write.c",
        "pdf-xobject.c",
        "pdf-xref.c",
        "pdf-zugferd.c",
      ],
    },
    {
      dir: "mupdf/source/svg",
      patterns: ["svg-color.c", "svg-doc.c", "svg-parse.c", "svg-run.c"],
    },
    {
      dir: "mupdf/source/xps",
      patterns: [
        "xps-common.c",
        "xps-doc.c",
        "xps-glyphs.c",
        "xps-gradient.c",
        "xps-image.c",
        "xps-link.c",
        "xps-outline.c",
        "xps-path.c",
        "xps-resource.c",
        "xps-tile.c",
        "xps-util.c",
        "xps-zip.c",
      ],
    },
    { dir: "mupdf/source/reflow", patterns: ["*.c"] },
    {
      dir: "mupdf/source/tools",
      patterns: [
        "muconvert.c",
        "mudraw.c",
        "mugrep.c",
        "murun.c",
        "mutrace.c",
        "pdfaudit.c",
        "pdfbake.c",
        "pdfclean.c",
        "pdfcreate.c",
        "pdfextract.c",
        "pdfinfo.c",
        "pdfmerge.c",
        "pdfpages.c",
        "pdfposter.c",
        "pdfrecolor.c",
        "pdfshow.c",
        "pdfsign.c",
        "pdftrim.c",
      ],
    },
    { dir: "mupdf/source/helpers/pkcs7", patterns: ["pkcs7-windows.c"] },
    { dir: "mupdf/source/helpers/mu-threads", patterns: ["mu-threads.c"] },
  ],
};
