// gen-code.ts - runs all C++ codegen (imports gen-flags, gen-commands, gen-settings;
// gVirtKeysNum generation lives here only)
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { main as genFlags } from "./gen-flags";
import { main as genCommands } from "./gen-commands";
import { main as genSettings } from "./gen-settings";
import { clangFormatFiles } from "./util";

// C++ outputs touched by gen-code; formatted at the end so a follow-up
// cmd/format.ts run does not dirty the tree (e.g. indented @gen markers).
const generatedCppFiles = [
    "src/Flags.cpp",
    "src/Commands.h",
    "src/Commands.cpp",
    "src/Accelerators.cpp",
    "src/EbookDoc.cpp",
    "src/PdfCreator.cpp",
    "src/EngineMupdf.cpp",
    "src/Settings.h",
];

// prettier-ignore
// if there are multiple declarations, the first one will be shown in menu
const virtKeys: [string, string][] = [
    ["VK_NUMPAD0", "numpad0"],
    ["VK_NUMPAD1", "numpad1"],
    ["VK_NUMPAD2", "numpad2"],
    ["VK_NUMPAD3", "numpad3"],
    ["VK_NUMPAD4", "numpad4"],
    ["VK_NUMPAD5", "numpad5"],
    ["VK_NUMPAD6", "numpad6"],
    ["VK_NUMPAD7", "numpad7"],
    ["VK_NUMPAD8", "numpad8"],
    ["VK_NUMPAD9", "numpad9"],
    ["VK_TAB", "Tab"],
    ["VK_END", "End"],
    ["VK_HOME", "Home"],
    ["VK_LEFT", "Left"],
    ["VK_RIGHT", "Right"],
    ["VK_UP", "Up"],
    ["VK_DOWN", "Down"],
    ["VK_NEXT", "PageDown"],
    ["VK_NEXT", "PgDown"],
    ["VK_PRIOR", "PageUp"],
    ["VK_PRIOR", "PgUp"],
    ["VK_BACK", "Back"],
    ["VK_BACK", "Backspace"],
    ["VK_DELETE", "Del"],
    ["VK_DELETE", "Delete"],
    ["VK_INSERT", "Ins"],
    ["VK_INSERT", "Insert"],
    ["VK_ESCAPE", "Esc"],
    ["VK_ESCAPE", "Escape"],
    ["VK_RETURN", "Return"],
    ["VK_CONVERT", "Convert"],
    ["VK_NONCONVERT", "NoConvert"],
    ["VK_SPACE", "Space"],
    ["VK_MULTIPLY", "*"],
    ["VK_MULTIPLY", "Multiply"],
    ["VK_MULTIPLY", "Mult"],
    ["VK_ADD", "+"],
    ["VK_OEM_PLUS", "+"],
    ["VK_ADD", "Add"],
    ["VK_OEM_MINUS", "-"],
    ["VK_SUBTRACT", "-"],
    ["VK_SUBTRACT", "Subtract"],
    ["VK_SUBTRACT", "Sub"],
    ["VK_DIVIDE", "/"],
    ["VK_DIVIDE", "Divide"],
    ["VK_DIVIDE", "Div"],
    ["VK_HELP", "Help"],
    ["VK_SELECT", "Select"],
    ["VK_VOLUME_DOWN", "Volume Down"],
    ["VK_VOLUME_DOWN", "VolumeDown"],
    ["VK_VOLUME_UP", "Volume Up"],
    ["VK_VOLUME_UP", "VolumeUp"],
    ["VK_XBUTTON1", "XButton1"],
    ["VK_XBUTTON2", "XButton2"],
    ["VK_F1", "F1"],
    ["VK_F2", "F2"],
    ["VK_F3", "F3"],
    ["VK_F4", "F4"],
    ["VK_F5", "F5"],
    ["VK_F6", "F6"],
    ["VK_F7", "F7"],
    ["VK_F8", "F8"],
    ["VK_F9", "F9"],
    ["VK_F10", "F10"],
    ["VK_F11", "F11"],
    ["VK_F12", "F12"],
    ["VK_F13", "F13"],
    ["VK_F14", "F14"],
    ["VK_F15", "F15"],
    ["VK_F16", "F16"],
    ["VK_F17", "F17"],
    ["VK_F18", "F18"],
    ["VK_F19", "F19"],
    ["VK_F20", "F20"],
    ["VK_F21", "F21"],
    ["VK_F22", "F22"],
    ["VK_F23", "F23"],
    ["VK_F24", "F24"],
    ["VK_CLEAR", "Clear"],
    ["VK_ACCEPT", "Accept"],
    ["VK_MODECHANGE", "ModeChange"],
    ["VK_PRINT", "Print"],
    ["VK_EXECUTE", "Execute"],
    ["VK_SNAPSHOT", "PrtSc"],
    ["VK_SNAPSHOT", "PrintScreen"],
    ["VK_SLEEP", "Sleep"],
    ["VK_SEPARATOR", "Separator"],
    ["VK_DECIMAL", "Decimal"],
    ["VK_SCROLL", "Scroll"],
    ["VK_OEM_1", ";"],
    ["VK_OEM_3", "`"],
    ["VK_OEM_4", "["],
    ["VK_OEM_6", "]"],
];

function uniqueVkNames(): string[] {
    const seen = new Set<string>();
    const names: string[] = [];
    for (const [vkName] of virtKeys) {
        if (!seen.has(vkName)) {
            seen.add(vkName);
            names.push(vkName);
        }
    }
    return names;
}

function generateVkCodesC(vkNames: string[]): string {
    const lines = [
        "/* generated by cmd/gen-code.ts; do not edit */",
        "#include <stdio.h>",
        "#include <windows.h>",
        "",
        "int main(void) {",
    ];
    for (const name of vkNames) {
        lines.push(`    printf("${name}=%d\\n", ${name});`);
    }
    lines.push("    return 0;", "}");
    return lines.join("\n") + "\n";
}

function parseVkCodesOutput(stdout: string): Record<string, number> {
    const map: Record<string, number> = {};
    for (const line of stdout.split(/\r?\n/)) {
        const trimmed = line.trim();
        if (!trimmed) {
            continue;
        }
        const eq = trimmed.indexOf("=");
        if (eq <= 0) {
            continue;
        }
        const name = trimmed.slice(0, eq);
        const value = parseInt(trimmed.slice(eq + 1), 10);
        if (!Number.isFinite(value)) {
            throw new Error(`invalid VK code line: ${trimmed}`);
        }
        map[name] = value;
    }
    return map;
}

// Compile and run a tiny C program that prints VK_* values from <windows.h>.
function fetchVkIdsFromCompiler(cmdDir: string): Record<string, number> {
    const vkNames = uniqueVkNames();
    const tmpDir = join(cmdDir, "tmp");
    mkdirSync(tmpDir, { recursive: true });

    const cPath = join(tmpDir, "gen-vk-codes.c");
    const exePath = join(tmpDir, "gen-vk-codes.exe");
    writeFileSync(cPath, generateVkCodesC(vkNames));

    const compile = Bun.spawnSync(["cl", "/nologo", `/Fe:${exePath}`, cPath], {
        cwd: tmpDir,
        stdout: "pipe",
        stderr: "pipe",
    });
    if (compile.exitCode !== 0) {
        const err = compile.stderr.toString() || compile.stdout.toString();
        throw new Error(
            `failed to compile cmd/tmp/gen-vk-codes.c (is cl.exe in PATH / VS dev shell active?):\n${err}`,
        );
    }

    const run = Bun.spawnSync([exePath], { stdout: "pipe", stderr: "pipe" });
    if (run.exitCode !== 0) {
        const err = run.stderr.toString() || run.stdout.toString();
        throw new Error(`failed to run gen-vk-codes.exe:\n${err}`);
    }

    const map = parseVkCodesOutput(run.stdout.toString());
    for (const name of vkNames) {
        if (map[name] === undefined) {
            throw new Error(`gen-vk-codes.exe did not print ${name}`);
        }
    }
    return map;
}

// unsigned LEB128 of zigzag-encoded i64 (matches Str.cpp VarIntEncode)
function varIntEncode(val: number): number[] {
    const bytes: number[] = [];
    let n = BigInt(val);
    let zigzag = (n << 1n) ^ (n >> 63n);
    while (true) {
        let b = Number(zigzag & 0x7fn);
        zigzag >>= 7n;
        if (zigzag !== 0n) {
            b |= 0x80;
        }
        bytes.push(b);
        if (zigzag === 0n) {
            break;
        }
    }
    return bytes;
}

function escapeCString(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function varIntCString(val: number): string {
    const bytes = varIntEncode(val);
    return '"' + bytes.map((b) => `\\x${b.toString(16).padStart(2, "0")}`).join("") + '"';
}

function generateVirtKeysNum(vkIds: Record<string, number>): string {
    const lines: string[] = [];
    lines.push("// clang-format off");
    lines.push("static SeqStrNum gVirtKeysNum =");
    for (const [vkName, txt] of virtKeys) {
        const vk = vkIds[vkName];
        if (vk === undefined) {
            throw new Error(`unknown virtual key: ${vkName}`);
        }
        const strLit = `"${escapeCString(txt)}\\0"`;
        const numLit = varIntCString(vk);
        lines.push(`    ${strLit} ${numLit} \\`);
    }
    lines.push('    "\\0";');
    lines.push("// clang-format on");
    return lines.join("\n");
}

function replaceBetweenMarkers(content: string, startMarker: string, endMarker: string, generated: string): string {
    const startIdx = content.indexOf(startMarker);
    const endIdx = content.indexOf(endMarker);
    if (startIdx < 0 || endIdx < 0) {
        console.error(`Could not find markers '${startMarker}' and '${endMarker}'`);
        process.exit(1);
    }
    const before = content.substring(0, startIdx + startMarker.length);
    const after = content.substring(endIdx);
    return before + "\n" + generated + "\n" + after;
}

export function genVirtKeys(rootDir: string) {
    const cmdDir = join(rootDir, "cmd");
    const vkIds = fetchVkIdsFromCompiler(cmdDir);

    const accelPath = join(rootDir, "src", "Accelerators.cpp");
    let content = readFileSync(accelPath, "utf-8");
    content = replaceBetweenMarkers(
        content,
        "// @gen-start virt-keys-num",
        "// @gen-end virt-keys-num",
        generateVirtKeysNum(vkIds),
    );
    writeFileSync(accelPath, content, "utf-8");
    console.log("Generated gVirtKeysNum in src/Accelerators.cpp");
}

// name<->DocProp maps, previously hand-written as SeqStrNum literals with the
// per-entry number encoded by hand. That is error-prone: the number must be
// zigzag-LEB128 (varIntCString), and several maps used raw bytes instead, so
// every lookup was wrong. Generate them here so the encoding is always correct.
// Each entry is [format-specific name, DocProp enum member].
type PropEntry = [string, string];

// DocProp -> PDF /Info key; shared by EngineMupdf's pdfPropNames and PdfCreator.
const pdfInfoNames: PropEntry[] = [
    ["Title", "Title"],
    ["Author", "Author"],
    ["Subject", "Subject"],
    ["Copyright", "Copyright"],
    ["CreationDate", "CreationDate"],
    ["ModDate", "ModificationDate"],
    ["Creator", "CreatorApp"],
    ["Producer", "PdfProducer"],
];

type PropMapTarget = { file: string; tag: string; varName: string; entries: PropEntry[] };

const docPropMaps: PropMapTarget[] = [
    {
        file: "src/EbookDoc.cpp",
        tag: "docprop-epub",
        varName: "epubPropsMap",
        entries: [
            ["dc:title", "Title"],
            ["dc:creator", "Author"],
            ["dc:date", "CreationDate"],
            ["dcterms:modified", "ModificationDate"],
            ["dc:description", "Subject"],
            ["dc:rights", "Copyright"],
        ],
    },
    { file: "src/PdfCreator.cpp", tag: "docprop-pdfcreator", varName: "pdfCreatorPropsMap", entries: pdfInfoNames },
    {
        file: "src/EngineMupdf.cpp",
        tag: "docprop-mupdf",
        varName: "mupdfPropsMap",
        // keys mirror mupdf's FZ_META_INFO_* ("info:Title" etc.)
        entries: [
            ["info:Title", "Title"],
            ["info:Author", "Author"],
            ["info:Subject", "Subject"],
            ["info:Producer", "PdfProducer"],
            ["info:Creator", "CreatorApp"],
            ["info:CreationDate", "CreationDate"],
            ["info:ModDate", "ModificationDate"],
        ],
    },
    { file: "src/EngineMupdf.cpp", tag: "docprop-pdf-info", varName: "pdfPropNames", entries: pdfInfoNames },
];

// parse `enum class DocProp : u8 { None = 0, Title = 1, ... }` -> { Title: 1, ... }
function parseDocPropValues(rootDir: string): Record<string, number> {
    const src = readFileSync(join(rootDir, "src", "DocProperties.h"), "utf-8");
    const m = src.match(/enum class DocProp[^{]*\{([^}]*)\}/);
    if (!m) {
        throw new Error("DocProp enum not found in src/DocProperties.h");
    }
    const vals: Record<string, number> = {};
    for (const line of m[1].split("\n")) {
        const mm = line.match(/\b(\w+)\s*=\s*(\d+)/);
        if (mm) {
            vals[mm[1]] = parseInt(mm[2], 10);
        }
    }
    return vals;
}

function generateSeqStrNumPropMap(varName: string, entries: PropEntry[], vals: Record<string, number>): string {
    const lines: string[] = ["// clang-format off", `static SeqStrNum ${varName} =`];
    for (const [name, prop] of entries) {
        const val = vals[prop];
        if (val === undefined) {
            throw new Error(`unknown DocProp '${prop}' for ${varName}`);
        }
        lines.push(`    "${escapeCString(name)}\\0" ${varIntCString(val)}`);
    }
    lines.push('    "\\0";', "// clang-format on");
    return lines.join("\n");
}

// decode a generated map back (matching Str.cpp VarIntDecode) and assert the
// first, middle and last entries round-trip - catches any encoding mistake at
// generation time.
function verifyPropMap(t: PropMapTarget, vals: Record<string, number>): void {
    const gen = generateSeqStrNumPropMap(t.varName, t.entries, vals);
    // pull the "\xNN" byte groups back out, in entry order
    const byteGroups = [...gen.matchAll(/\\0" "((?:\\x[0-9a-f]{2})+)"/g)].map((m) =>
        [...m[1].matchAll(/\\x([0-9a-f]{2})/g)].map((b) => parseInt(b[1], 16)),
    );
    const decode = (bytes: number[]): number => {
        let n = 0n;
        let shift = 0n;
        for (const b of bytes) {
            n |= BigInt(b & 0x7f) << shift;
            if (!(b & 0x80)) break;
            shift += 7n;
        }
        return Number((n >> 1n) ^ -(n & 1n));
    };
    const idxs = [0, Math.floor(t.entries.length / 2), t.entries.length - 1];
    for (const i of idxs) {
        const want = vals[t.entries[i][1]];
        const got = decode(byteGroups[i]);
        if (got !== want) {
            throw new Error(`${t.varName}[${i}] (${t.entries[i][0]}): encoded ${got}, expected ${want}`);
        }
    }
}

export function genDocPropMaps(rootDir: string) {
    const vals = parseDocPropValues(rootDir);
    // group targets by file (EngineMupdf.cpp has two sections)
    const byFile = new Map<string, PropMapTarget[]>();
    for (const t of docPropMaps) {
        verifyPropMap(t, vals);
        const list = byFile.get(t.file) ?? [];
        list.push(t);
        byFile.set(t.file, list);
    }
    for (const [file, targets] of byFile) {
        const p = join(rootDir, file);
        let content = readFileSync(p, "utf-8");
        for (const t of targets) {
            content = replaceBetweenMarkers(
                content,
                `// @gen-start ${t.tag}`,
                `// @gen-end ${t.tag}`,
                generateSeqStrNumPropMap(t.varName, t.entries, vals),
            );
        }
        writeFileSync(p, content, "utf-8");
        console.log(`Generated DocProp map(s) in ${file}: ${targets.map((t) => t.varName).join(", ")}`);
    }
}

export async function main() {
    const timeStart = performance.now();
    const rootDir = join(import.meta.dir, "..");

    genFlags();
    genCommands();
    genVirtKeys(rootDir);
    genDocPropMaps(rootDir);
    await genSettings({ formatOutput: false });

    await clangFormatFiles(rootDir, generatedCppFiles);

    const elapsed = ((performance.now() - timeStart) / 1000).toFixed(1);
    console.log(`gen-code finished in ${elapsed}s`);
}

if (import.meta.main) {
    await main();
}