// Upload ext/mupdf/resources/fonts to R2 and write src/shared/mupdf/fonts_map.c.
//
//   bun cmd/upload-fonts.ts
//
// Each font file is stored as <name>-<sha1 suffix><ext> under
// assets/sumatrapdf/fonts and served at
// https://files.sumatrapdfreader.org/assets/sumatrapdf/fonts/<that name>.
// The suffix is the shortest of 4, 6 or 8 sha1 hex chars that doesn't collide
// in this set, same shape as the doc images (name-423d.png). An object that
// is already there is left in place. The map is font file name (what
// noto_sumatra.c asks the loader for) to that URL.
//
// Credentials: ../secrets/sumatrapdf.env (R2_ACCESS, R2_SECRET) or the same
// variables in the environment. -map-only writes the map and does not upload.

import { createHash, createHmac } from "node:crypto";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, extname, join, relative, resolve } from "node:path";
import { clangFormatFiles } from "./util";

const root = resolve(import.meta.dir, "..");
const fontsDir = join(root, "ext/mupdf/resources/fonts");
const mapPath = join(root, "src/shared/mupdf/fonts_map.c");
const publicBase = "https://files.sumatrapdfreader.org/assets/sumatrapdf/fonts";
const keyPrefix = "assets/sumatrapdf/fonts";
const fontExts = new Set([".ttf", ".otf", ".ttc", ".otc", ".cff"]);
const skipDirs = new Set(["input", "sources"]);
const suffixLens = [4, 6, 8];
const emptyHash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";

const endpoint = "71694ef61795ecbe1bc331d217dbd7a7.r2.cloudflarestorage.com";
const bucket = "files";
const region = "auto";

type FontFile = {
  name: string;
  path: string;
  bytes: Buffer;
  sha1: string;
};

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (e.isDirectory()) {
      if (skipDirs.has(e.name)) continue;
      out.push(...walk(join(dir, e.name)));
      continue;
    }
    if (fontExts.has(extname(e.name).toLowerCase())) out.push(join(dir, e.name));
  }
  return out;
}

function collectFonts(): FontFile[] {
  const files = walk(fontsDir);
  const seen = new Map<string, string>();
  const fonts: FontFile[] = [];
  for (const path of files) {
    const name = basename(path);
    const prev = seen.get(name);
    if (prev) throw new Error(`two fonts named ${name}: ${prev} and ${path}`);
    seen.set(name, path);
    const bytes = readFileSync(path);
    if (bytes.length === 0) throw new Error(`empty font: ${path}`);
    fonts.push({ name, path, bytes, sha1: createHash("sha1").update(bytes).digest("hex") });
  }
  fonts.sort((a, b) => a.name.localeCompare(b.name));
  return fonts;
}

function remoteNames(fonts: FontFile[], n: number): Map<string, string> {
  const names = new Map<string, string>();
  for (const f of fonts) {
    const ext = extname(f.name);
    const base = basename(f.name, ext);
    const remote = `${base}-${f.sha1.slice(0, n)}${ext}`;
    if ([...names.values()].includes(remote)) throw new Error(`suffix collision: ${remote}`);
    names.set(f.name, remote);
  }
  return names;
}

function pickNames(fonts: FontFile[]): { n: number; names: Map<string, string> } {
  let last = "";
  for (const n of suffixLens) {
    try {
      return { n, names: remoteNames(fonts, n) };
    } catch (e) {
      last = e instanceof Error ? e.message : String(e);
    }
  }
  throw new Error(last);
}

function cString(s: string): string {
  return s.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

function writeMap(fonts: FontFile[], names: Map<string, string>): void {
  const rows = fonts.map((f) => {
    const url = `${publicBase}/${names.get(f.name)}`;
    return `    {"${cString(f.name)}", "${cString(url)}"},`;
  });
  const text = `// Generated by cmd/upload-fonts.ts. Do not edit.
// Font file name (what the built-in font loader asks for) => public URL.

#include "noto_sumatra.h"

#include <stdlib.h>
#include <string.h>

typedef struct {
    const char* name;
    const char* url;
} SumatraFontUrl;

static const SumatraFontUrl kFontUrls[] = {
${rows.join("\n")}
};

static int CmpFontUrl(const void* key, const void* elem) {
    return strcmp((const char*)key, ((const SumatraFontUrl*)elem)->name);
}

const char* sumatra_lookup_font_url(const char* name) {
    const SumatraFontUrl* e;
    if (!name) {
        return NULL;
    }
    e = (const SumatraFontUrl*)bsearch(name, kFontUrls, sizeof(kFontUrls) / sizeof(kFontUrls[0]), sizeof(kFontUrls[0]),
                                        CmpFontUrl);
    return e ? e->url : NULL;
}
`;
  writeFileSync(mapPath, text.replaceAll("\r\n", "\n"));
}

function loadSecrets(): { access: string; secret: string } {
  const paths = [
    resolve(root, "..", "secrets", "sumatrapdf.env"),
    resolve(root, "..", "hack", "secrets", "sumatrapdf.env"),
  ];
  const m = new Map<string, string>();
  for (const path of paths) {
    if (!existsSync(path)) continue;
    for (const line of readFileSync(path, "utf8").split("\n")) {
      const eq = line.indexOf("=");
      if (eq > 0) m.set(line.slice(0, eq).trim(), line.slice(eq + 1).trim());
    }
    break;
  }
  const access = m.get("R2_ACCESS") || process.env["R2_ACCESS"] || "";
  const secret = m.get("R2_SECRET") || process.env["R2_SECRET"] || "";
  return { access, secret };
}

function hmacSha256(key: Buffer | string, data: string): Buffer {
  return createHmac("sha256", key).update(data).digest();
}

function sha256Hex(data: Buffer | Uint8Array | string): string {
  return createHash("sha256").update(data).digest("hex");
}

function contentType(name: string): string {
  switch (extname(name).toLowerCase()) {
    case ".ttf":
      return "font/ttf";
    case ".otf":
      return "font/otf";
    case ".ttc":
    case ".otc":
      return "font/collection";
    case ".cff":
      return "font/cff";
    default:
      return "application/octet-stream";
  }
}

async function s3Request(
  access: string,
  secret: string,
  method: "HEAD" | "PUT",
  key: string,
  body: Buffer | null,
  extra: Record<string, string>,
): Promise<Response> {
  const now = new Date();
  const dateStamp = now.toISOString().slice(0, 10).replace(/-/g, "");
  const amzDate = dateStamp + "T" + now.toISOString().slice(11, 19).replace(/:/g, "") + "Z";
  const payloadHash = body ? sha256Hex(body) : emptyHash;
  const headers: Record<string, string> = {
    host: endpoint,
    "x-amz-content-sha256": payloadHash,
    "x-amz-date": amzDate,
    ...extra,
  };
  if (body) headers["content-length"] = String(body.length);
  const signedHeaderKeys = Object.keys(headers).sort();
  const signedHeaders = signedHeaderKeys.join(";");
  const canonicalHeaders = signedHeaderKeys.map((k) => `${k}:${headers[k]}\n`).join("");
  const canonicalUri = `/${bucket}/${key}`;
  const canonicalRequest = [method, canonicalUri, "", canonicalHeaders, signedHeaders, payloadHash].join("\n");
  const credentialScope = `${dateStamp}/${region}/s3/aws4_request`;
  const stringToSign = ["AWS4-HMAC-SHA256", amzDate, credentialScope, sha256Hex(canonicalRequest)].join("\n");
  let signingKey: Buffer = hmacSha256("AWS4" + secret, dateStamp);
  signingKey = hmacSha256(signingKey, region);
  signingKey = hmacSha256(signingKey, "s3");
  signingKey = hmacSha256(signingKey, "aws4_request");
  const signature = hmacSha256(signingKey, stringToSign).toString("hex");
  const authorization = `AWS4-HMAC-SHA256 Credential=${access}/${credentialScope}, SignedHeaders=${signedHeaders}, Signature=${signature}`;
  return fetch(`https://${endpoint}${canonicalUri}`, {
    method,
    headers: { ...headers, Authorization: authorization },
    body: body ? new Uint8Array(body) : undefined,
  });
}

async function uploadOne(
  access: string,
  secret: string,
  key: string,
  bytes: Buffer,
  type: string,
): Promise<"skip" | "put"> {
  const head = await s3Request(access, secret, "HEAD", key, null, {});
  await head.arrayBuffer();
  if (head.status === 200) return "skip";
  if (head.status !== 404) {
    const text = await head.text();
    throw new Error(`HEAD ${key} failed: ${head.status}\n${text}`);
  }
  const put = await s3Request(access, secret, "PUT", key, bytes, {
    "cache-control": "public, max-age=31536000, immutable",
    "content-type": type,
  });
  if (!put.ok) {
    const text = await put.text();
    throw new Error(`PUT ${key} failed: ${put.status}\n${text}`);
  }
  return "put";
}

async function main(): Promise<void> {
  const mapOnly = process.argv.includes("-map-only");
  if (process.argv.includes("-h") || process.argv.includes("-help")) {
    console.log("usage: bun cmd/upload-fonts.ts [-map-only]");
    return;
  }
  const fonts = collectFonts();
  const { n, names } = pickNames(fonts);
  writeMap(fonts, names);
  await clangFormatFiles(root, [relative(root, mapPath)]);
  console.log(`wrote ${relative(root, mapPath)} (${fonts.length} fonts, ${n} hex sha1)`);
  if (mapOnly) return;

  const { access, secret } = loadSecrets();
  if (access.length < 8 || secret.length < 8) {
    throw new Error("R2_ACCESS / R2_SECRET not set; map was written, nothing uploaded");
  }
  let uploaded = 0;
  let skipped = 0;
  for (const f of fonts) {
    const remote = names.get(f.name)!;
    const key = `${keyPrefix}/${remote}`;
    const result = await uploadOne(access, secret, key, f.bytes, contentType(remote));
    if (result === "skip") {
      skipped++;
      console.log(`exists ${key}`);
    } else {
      uploaded++;
      console.log(`uploaded ${key} (${f.bytes.length} bytes)`);
    }
  }
  console.log(`uploaded ${uploaded}, already there ${skipped}`);
}

await main();
