g_langs = [
  ["el", "Greek (Ελληνικά)"],
  ["en", "English"],
  ["cn", "Chinese Simplified (简体中文)"],
  ["af", "Afrikaans"],
  ["ca", "Catalan (Català)"],
  ["am", "Armenian (Հայերեն)"],
  ["it", "Italian (Italiano)"],
  ["vn", "Vietnamese (Việt Nam)"],
  ["cz", "Czech (Čeština)"],
  ["cy", "Welsh (Cymraeg)"],
  ["ar", "Arabic (الْعَرَبيّة)"],
  ["sr-rs", "Serbian (Cyrillic)"],
  ["ga", "Irish (Gaeilge)"],
  ["eu", "Basque (Euskara)"],
  ["et", "Estonian (Eesti)"],
  ["gl", "Galician (Galego)"],
  ["id", "Indonesian (Bahasa Indonesia)"],
  ["es", "Spanish (Español)"],
  ["ru", "Russian (Русский)"],
  ["nl", "Dutch (Nederlands)"],
  ["nn", "Norwegian Neo-Norwegian (Norsk nynorsk)"],
  ["no", "Norwegian (Norsk)"],
  ["tw", "Chinese Traditional (繁體中文)"],
  ["tr", "Turkish (Türkçe)"],
  ["tl", "Tagalog (Tagalog)"],
  ["ja", "Japanese (日本語)"],
  ["lt", "Lithuanian (Lietuvių)"],
  ["pa", "Punjabi (ਪੰਜਾਬੀ)"],
  ["th", "Thai (ภาษาไทย)"],
  ["fy-nl", "Frisian (Frysk)"],
  ["ro", "Romanian (Română)"],
  ["pl", "Polish (Polski)"],
  ["ta", "Tamil (தமிழ்)"],
  ["fr", "French (Français)"],
  ["bg", "Bulgarian (Български)"],
  ["dk", "Danish (Dansk)"],
  ["ca-xv", "Catalan-Valencian (Català-Valencià)"],
  ["hr", "Croatian (Hrvatski)"],
  ["bn", "Bengali (বাংলা)"],
  ["de", "German (Deutsch)"],
  ["hu", "Hungarian (Magyar)"],
  ["fa", "Persian (فارسی)"],
  ["hi", "Hindi (हिंदी)"],
  ["br", "Portuguese - Brazil (Português)"],
  ["bs", "Bosnian (Bosanski)"],
  ["fi", "Finnish (Suomi)"],
  ["by", "Belarusian (Беларуская)"],
  ["sp-rs", "Serbian (Latin)"],
  ["he", "Hebrew (עברית)"],
  ["ka", "Georgian (ქართული)"],
  ["pt", "Portuguese - Portugal (Português)"],
  ["uz", "Uzbek (O'zbek)"],
  ["mm", "Burmese (ဗမာ စာ)"],
  ["ml", "Malayalam (മലയാളം)"],
  ["sq", "Albanian (Shqip)"],
  ["sv", "Swedish (Svenska)"],
  ["mk", "Macedonian (македонски)"],
  ["sk", "Slovak (Slovenčina)"],
  ["kr", "Korean (한국어)"],
  ["si", "Sinhala (සිංහල)"],
  ["kw", "Cornish (Kernewek)"],
  ["sn", "Shona (Shona)"],
  ["uk", "Ukrainian (Українська)"],
  ["sl", "Slovenian (Slovenščina)"],
  ["my", "Malaysian (Bahasa Melayu)"],
]

