.TH jbig2dec 1 "2023 May 19" "Version 0.20" "jbig2dec Manual"

.SH NAME
jbig2dec \- File format converter specialized in JBIG2 decoding

.SH SYNOPSIS
.B jbig2dec
.RI [ options ]
.I file.jbig2
.br
.B jbig2dec
.RI [ options ]
.I global-stream page-stream

.SH DESCRIPTION
The
.B jbig2dec
command converts JBIG2 files to png or pbm files.

When passed a single
.I file
argument it is interpreted as a JBIG2 file stream, with either
sequential or random-access organization.

When passed two stream arguments, they are interpreted as the
global and page-specific portions of an embedded organization,
as used in PDF. If a particular page references no global
segment stream, /dev/null can be passed for the
.I global-stream
argument to request the embedded parser.

.SH OPTIONS
The options are as follows:
.TP
.BR -e ", " --embedded
Expect embedded bit stream without file header.
.TP
.BI -o " file" ", --output" " file"
Store the decoded output in
.IR file .
Defaults to the input with a different extension.
Set to \fI-\fR for standard output.
.TP
.BI -t " type" ", --format" " type"
Force a particular output file format. Supported are \fIpng\fR and
\fIpbm\fR.
.TP
.BR -d ", " --dump
Print the structure of the JBIG2 file rather than explicitly decoding it.
.TP
.BR -m ", " --hash
Print a hash of the decoded document.
.TP
.BR -q ", " --quiet
Suppress warnings and other diagnostic output.
.TP
.BR -v ", " --verbose
Report additional information about the decoding process.
Pass just \fB-v\fR for information about the file as it's being decoded.
This is the same as \fB--verbose=2\fR.
Pass \fB--verbose=3\fR or higher for debugging information.
.TP
.BR -V ", " --version
Show program version information.
.TP
.BR -h ", " --help
Show usage summary.

.SH REPORTING BUGS
Report bugs at https://bugs.ghostscript.com

Contact the developers on Discord: https://discord.gg/taPnFQp5gb
or via the mailing list <gs-devel@ghostscript.com>.

.SH AUTHOR
This manpage was initially written by Sebastian Rasmussen
<sebras@gmail.com> for jbig2dec and the Debian Project.
