s/fz_obj/pdf_obj/g
s/pdf_resolve_indirect/pdf_resolve_indirect_imp/g
s/fz_resolve_indirect/pdf_resolve_indirect/g
s/fz_new_null/pdf_new_null/g
s/fz_new_bool/pdf_new_bool/g
s/fz_new_int/pdf_new_int/g
s/fz_new_real/pdf_new_real/g
s/fz_new_string/pdf_new_string/g
s/fz_new_indirect/pdf_new_indirect/g
s/fz_new_array/pdf_new_array/g
s/fz_new_dict/pdf_new_dict/g
s/fz_copy_array/pdf_copy_array/g
s/fz_copy_dict/pdf_copy_dict/g
s/fz_keep_obj/pdf_keep_obj/g
s/fz_drop_obj/pdf_drop_obj/g
s/fz_is_null/pdf_is_null/g
s/fz_is_bool/pdf_is_bool/g
s/fz_is_int/pdf_is_int/g
s/fz_is_real/pdf_is_real/g
s/fz_is_name/pdf_is_name/g
s/fz_is_string/pdf_is_string/g
s/fz_is_array/pdf_is_array/g
s/fz_is_dict/pdf_is_dict/g
s/fz_is_indirect/pdf_is_indirect/g
s/fz_objcmp/pdf_objcmp/g
s/fz_dict_marked/pdf_dict_marked/g
s/fz_dict_mark/pdf_dict_mark/g
s/fz_dict_unmark/pdf_dict_unmark/g
s/fz_to_bool/pdf_to_bool/g
s/fz_to_int/pdf_to_int/g
s/fz_to_real/pdf_to_real/g
s/fz_to_name/pdf_to_name/g
s/fz_to_str_buf/pdf_to_str_buf/g
s/fz_to_dict/pdf_to_dict/g
s/fz_to_str_len/pdf_to_str_len/g
s/fz_to_num/pdf_to_num/g
s/fz_to_gen/pdf_to_gen/g
s/fz_array_len/pdf_array_len/g
s/fz_array_get/pdf_array_get/g
s/fz_array_put/pdf_array_put/g
s/fz_array_push/pdf_array_push/g
s/fz_array_insert/pdf_array_insert/g
s/fz_array_contains/pdf_array_contains/g
s/fz_dict_len/pdf_dict_len/g
s/fz_dict_get_val/pdf_dict_get_val/g
s/fz_dict_get_key/pdf_dict_get_key/g
s/fz_dict_get/pdf_dict_get/g
s/fz_dict_gets/pdf_dict_gets/g
s/fz_dict_getsa/pdf_dict_getsa/g
s/fz_dict_put/fz_dict_put/g
s/fz_dict_puts/pdf_dict_puts/g
s/fz_dict_del/pdf_dict_del/g
s/fz_dict_dels/pdf_dict_dels/g
s/fz_sort_dict/pdf_sort_dict/g
s/fz_fprint_obj/pdf_fprint_obj/g
s/fz_debug_obj/pdf_debug_obj/g
s/fz_debug_ref/pdf_debug_ref/g
s/fz_set_str_len/pdf_set_str_len/g
s/fz_get_indirect_document/pdf_get_indirect_document/g
s/FZ_NULL/PDF_NULL/g
s/FZ_BOOL/PDF_BOOL/g
s/FZ_INT/PDF_INT/g
s/FZ_REAL/PDF_REAL/g
s/FZ_STRING/PDF_STRING/g
s/FZ_NAME/PDF_NAME/g
s/FZ_ARRAY/PDF_ARRAY/g
s/FZ_DICT/PDF_DICT/g
s/FZ_INDIRECT/PDF_INDIRECT/g
s/fz_objkindstr/pdf_objkindstr/g
s/fz_array_grow/pdf_array_grow/g
s/fz_dict_grow/pdf_dict_grow/g
s/fz_dict_finds/pdf_dict_finds/g
s/fz_free_array/pdf_free_array/g
s/fz_free_dict/pdf_free_dict/g
s/fz_sprint_obj/pdf_sprint_obj/g
