// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define tabFileMenu 2 
#define IDM_OPEN 400 
#define IDM_OPEN_SmallImages_RESID 60001
#define IDM_CLOSE 401 
#define IDM_SAVEAS 402 
#define IDM_SAVEAS_SmallImages_RESID 60002
#define IDM_Print 403 
#define IDM_Print_SmallImages_RESID 60003
#define IDM_EXIT 405 
#define IDM_EXIT_SmallImages_RESID 60004
#define IDM_SAVEAS_BOOKMARK 407 
#define IDM_SEND_BY_EMAIL 408 
#define IDM_SEND_BY_EMAIL_SmallImages_RESID 60005
#define IDM_PROPERTIES 409 
#define IDM_PROPERTIES_SmallImages_RESID 60006
#define IDM_ABOUT 551 
#define IDM_ABOUT_SmallImages_RESID 60007
#define IDM_ABOUT_LargeImages_RESID 60008
#define cmdMRUList 3 
#define tabStart 4 
#define tabMore 5 
#define grpView 6 
#define IDM_VIEW_SINGLE_PAGE 410 
#define IDM_VIEW_SINGLE_PAGE_SmallImages_RESID 60009
#define IDM_VIEW_FACING 411 
#define IDM_VIEW_FACING_SmallImages_RESID 60010
#define IDM_VIEW_BOOK 412 
#define IDM_VIEW_BOOK_SmallImages_RESID 60011
#define IDM_VIEW_CONTINUOUS 413 
#define IDM_VIEW_CONTINUOUS_SmallImages_RESID 60012
#define grpView2 7 
#define IDM_VIEW_ROTATE_LEFT 415 
#define IDM_VIEW_ROTATE_LEFT_SmallImages_RESID 60013
#define IDM_VIEW_ROTATE_RIGHT 416 
#define IDM_VIEW_ROTATE_RIGHT_SmallImages_RESID 60014
#define IDM_VIEW_PRESENTATION_MODE 418 
#define IDM_VIEW_PRESENTATION_MODE_SmallImages_RESID 60015
#define IDM_VIEW_FULLSCREEN 421 
#define IDM_VIEW_FULLSCREEN_SmallImages_RESID 60016
#define IDM_VIEW_BOOKMARKS 417 
#define IDM_VIEW_BOOKMARKS_SmallImages_RESID 60017
#define IDM_FAV_TOGGLE 562 
#define IDM_FAV_TOGGLE_SmallImages_RESID 60018
#define grpEdit 8 
#define IDM_SELECT_ALL 422 
#define IDM_SELECT_ALL_SmallImages_RESID 60019
#define IDM_COPY_SELECTION 420 
#define IDM_COPY_SELECTION_SmallImages_RESID 60020
#define grpFind 9 
#define IDM_FIND_FIRST 435 
#define IDM_FIND_FIRST_SmallImages_RESID 60021
#define grpNav 10 
#define IDM_GOTO_NEXT_PAGE 430 
#define IDM_GOTO_NEXT_PAGE_SmallImages_RESID 60022
#define IDM_GOTO_PREV_PAGE 431 
#define IDM_GOTO_PREV_PAGE_SmallImages_RESID 60023
#define IDM_GOTO_FIRST_PAGE 432 
#define IDM_GOTO_FIRST_PAGE_SmallImages_RESID 60024
#define IDM_GOTO_LAST_PAGE 433 
#define IDM_GOTO_LAST_PAGE_SmallImages_RESID 60025
#define IDM_GOTO_PAGE 434 
#define IDM_GOTO_PAGE_SmallImages_RESID 60026
#define IDM_GOTO_NAV_BACK 558 
#define IDM_GOTO_NAV_BACK_SmallImages_RESID 60027
#define IDM_GOTO_NAV_FORWARD 559 
#define IDM_GOTO_NAV_FORWARD_SmallImages_RESID 60028
#define grpZoom 11 
#define IDM_ZOOM_FIT_PAGE 440 
#define IDM_ZOOM_FIT_PAGE_SmallImages_RESID 60029
#define IDM_ZOOM_ACTUAL_SIZE 441 
#define IDM_ZOOM_ACTUAL_SIZE_SmallImages_RESID 60030
#define IDM_ZOOM_FIT_WIDTH 442 
#define IDM_ZOOM_FIT_WIDTH_SmallImages_RESID 60031
#define IDM_ZOOM_FIT_CONTENT 456 
#define IDM_ZOOM_FIT_CONTENT_SmallImages_RESID 60032
#define IDM_ZOOM_CUSTOM 457 
#define grpOptions 12 
#define IDM_CHANGE_LANGUAGE 553 
#define IDM_CHANGE_LANGUAGE_SmallImages_RESID 60033
#define IDM_SETTINGS 552 
#define IDM_SETTINGS_SmallImages_RESID 60034
#define IDM_MANUAL 555 
#define IDM_CHECK_UPDATE 554 
#define grpDebug 13 
#define IDM_DEBUG_SHOW_LINKS 590 
#define IDM_DEBUG_GDI_RENDERER 591 
#define tabQuickAccess 14 
