//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SumatraPDF.rc
//
#define IDI_SUMATRAPDF                  1
#define IDS_APP_TITLE                   100
#define IDD_DIALOG_GOTO_PAGE            129
#define IDD_DIALOG_GET_PASSWORD         130
#define IDD_DIALOG_PDF_ASSOCIATE        131
#define IDC_CURSORDRAG                  132
#define IDD_DIALOG_INVERSESEARCH        133
#define IDD_DIALOG_CHANGE_LANGUAGE      134
#define IDR_MAINFRAME                   200
#define IDD_XPDFWIN_DIALOG              300
#define IDD_ABOUTBOX                    301
#define IDM_OPEN                        400
#define IDM_CLOSE                       401
#define IDM_SAVEAS                      402
#define IDM_PRINT                       403
#define IDM_MAKE_DEFAULT_READER         404
#define IDM_EXIT                        405
#define IDM_VIEW_SINGLE_PAGE            410
#define IDM_VIEW_FACING                 411
#define IDM_VIEW_CONTINUOUS             412
#define IDM_VIEW_CONTINUOUS_FACING      413
#define IDM_VIEW_ROTATE_LEFT            414
#define IDM_VIEW_ROTATE_RIGHT           415
#define IDM_VIEW_BOOKMARKS              417
#define IDM_VIEW_FULLSCREEN             418
#define IDM_VIEW_SHOW_HIDE_TOOLBAR      419
#define IDM_VIEW_USE_FITZ               420
#define IDM_GOTO_NEXT_PAGE              430
#define IDM_GOTO_PREV_PAGE              431
#define IDM_GOTO_FIRST_PAGE             432
#define IDM_GOTO_LAST_PAGE              433
#define IDM_GOTO_PAGE                   434
#define IDM_FIND_FIRST                  435
#define IDM_FIND_NEXT                   436
#define IDM_FIND_PREV                   437
#define IDM_FIND_MATCH                  438
#define IDM_ZOOM_FIT_PAGE               440
#define IDM_ZOOM_ACTUAL_SIZE            441
#define IDM_ZOOM_FIT_WIDTH              442
#define IDM_ZOOM_6400                   443
#define IDM_ZOOM_3200                   444
#define IDM_ZOOM_1600                   445
#define IDM_ZOOM_800                    446
#define IDM_ZOOM_400                    447
#define IDM_ZOOM_200                    448
#define IDM_ZOOM_150                    449
#define IDM_ZOOM_125                    450
#define IDM_ZOOM_100                    451
#define IDM_ZOOM_50                     452
#define IDM_ZOOM_25                     453
#define IDM_ZOOM_12_5                   454
#define IDM_ZOOM_8_33                   455
#define IDM_CONTRIBUTE_TRANSLATION      460
#define IDM_LANG_EN                     461
#define IDM_LANG_FR                     462
#define IDM_LANG_PL                     463
#define IDM_LANG_DE                     464
#define IDM_LANG_TR                     465
#define IDM_LANG_BY                     466
#define IDM_LANG_JA                     467
#define IDM_LANG_HU                     468
#define IDM_LANG_FA                     469
#define IDM_LANG_DK                     470
#define IDM_LANG_IT                     471
#define IDM_LANG_NL                     472
#define IDM_LANG_TA                     473
#define IDM_LANG_ES                     474
#define IDM_LANG_HR                     475
#define IDM_LANG_RU                     476
#define IDM_LANG_AR                     477
#define IDM_LANG_CN                     478
#define IDM_LANG_SV                     479
#define IDM_LANG_CZ                     480
#define IDM_LANG_GR                     481
#define IDM_LANG_TH                     482
#define IDM_LANG_PT                     483
#define IDM_LANG_BR                     484
#define IDM_LANG_NO                     485
#define IDM_LANG_SK                     486
#define IDM_LANG_VN                     487
#define IDM_LANG_LT                     488
#define IDM_LANG_MY                     489
#define IDM_LANG_FI                     490
#define IDM_LANG_CA                     491
#define IDM_LANG_SI                     492
#define IDM_LANG_TW                     493
#define IDM_LANG_ML                     494
#define IDM_LANG_HE                     495
#define IDM_LANG_SP_RS                  496
#define IDM_LANG_ID                     497
#define IDM_LANG_MK                     498
#define IDM_LANG_RO                     499
#define IDM_LANG_SR_RS                  500
#define IDM_LANG_KR                     501
#define IDM_LANG_BN                     502
#define IDM_LANG_GL                     503
#define IDM_LANG_BG                     504
#define IDM_LANG_UK                     505
#define IDM_LANG_EU                     506
#define IDM_VISIT_WEBSITE               550
#define IDM_ABOUT                       551
#define IDM_SET_INVERSESEARCH           552
#define IDM_CHOOSE_LANGUAGE             553
#define IDC_SUMATRAPDF                  600
#define IDI_SMALL                       601
#define IDC_GOTO_PAGE_EDIT              1000
#define IDC_GOTO_PAGE_GO                1001
#define IDC_BUTTON2                     1002
#define IDC_GOTOPAGE_CANCEL             1002
#define IDC_GOTO_PAGE_CANCEL            1002
#define IDC_GOTO_PAGE_LABEL_OF          1003
#define IDC_DIALOG_GET_PASSWORD_EDIT    1004
#define IDC_GET_PASSWORD_EDIT           1004
#define IDC_GET_PASSWORD_LABEL          1005
#define IDC_TOOLBAR                     1006
#define IDC_CMDLINE                     1006
#define IDC_REBAR                       1007
#define IDC_DONT_ASK_ME_AGAIN           1008
#define IDC_PDF_TOC_TREE                1009
#define IDC_CHOOSE_LANG_LANG_LIST       1010
#define IDB_TOOLBAR                     2000
#define IDB_TOOLBAR_DISABLED            2001
#define IDB_SILK_OPEN                   2002
#define IDB_SILK_NEXT                   2003
#define IDB_SILK_PREV                   2004
#define IDB_SILK_ZOOM_IN                2005
#define IDB_SILK_ZOOM_OUT               2006
#define IDB_CLOSE_TOC                   2007
#define IDB_FIND_NEXT                   2008
#define IDB_FIND_PREV                   2009
#define IDB_FIND_MATCH                  2010
#define IDT_FILE_NEW                    3000
#define IDT_FILE_OPEN                   3001
#define IDT_FILE_METAPATH               3002
#define IDT_FILE_SAVE                   3003
#define IDT_EDIT_UNDO                   3004
#define IDT_EDIT_REDO                   3005
#define IDT_EDIT_CUT                    3006
#define IDT_EDIT_COPY                   3007
#define IDT_EDIT_PASTE                  3008
#define IDT_EDIT_FIND                   3009
#define IDT_EDIT_REPLACE                3010
#define IDT_VIEW_WORDWRAP               3011
#define IDT_VIEW_ZOOMIN                 3012
#define IDT_VIEW_ZOOMOUT                3013
#define IDT_VIEW_SCHEME                 3014
#define IDT_VIEW_SCHEMECONFIG           3015
#define IDT_FILE_EXIT                   3016
#define IDT_FILE_SAVEAS                 3017
#define IDT_FILE_SAVECOPY               3018
#define IDT_EDIT_COPYALL                3019
#define IDT_EDIT_CLEAR                  3020
#define IDT_EDIT_FINDNEXT               3021
#define IDT_EDIT_FINDPREV               3022
#define IDT_FILE_PRINT                  3023
#define IDT_FILE_OPENFAV                3024
#define IDT_FILE_ADDTOFAV               3025
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
