//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SumatraPDF.rc
//
#define IDI_SUMATRAPDF                  1
#define IDI_PDFDOC                      2
#define IDI_RAMICRO                     3
#define IDD_DIALOG_GOTO_PAGE            129
#define IDD_DIALOG_GET_PASSWORD         130
#define IDD_DIALOG_PDF_ASSOCIATE        131
#define IDC_CURSORDRAG                  132
#define IDD_DIALOG_CHANGE_LANGUAGE      134
#define IDD_DIALOG_NEW_VERSION          135
#define IDD_DIALOG_SETTINGS             136
#define IDD_DIALOG_FIND                 137 
#define IDD_DIALOG_CUSTOM_ZOOM          138
#define IDD_PROPSHEET_PRINT_ADVANCED    139
#define IDD_DIALOG_FAV_ADD              140
#define IDM_OPEN                        400
#define IDM_CLOSE                       401
#define IDM_SAVEAS                      402
#define IDM_PRINT                       403
#define IDM_SHOW_IN_FOLDER              404
#define IDM_EXIT                        405
#define IDM_REFRESH                     406
#define IDM_SAVEAS_BOOKMARK             407
#define IDM_SEND_BY_EMAIL               408
#define IDM_PROPERTIES                  409
#define IDM_VIEW_SINGLE_PAGE            410
#define IDM_VIEW_FACING                 411
#define IDM_VIEW_BOOK                   412
#define IDM_VIEW_CONTINUOUS             413
#define IDM_VIEW_MANGA_MODE             414
#define IDM_VIEW_ROTATE_LEFT            415
#define IDM_VIEW_ROTATE_RIGHT           416
#define IDM_VIEW_BOOKMARKS              417
#define IDM_VIEW_PRESENTATION_MODE      418
#define IDM_VIEW_SHOW_HIDE_TOOLBAR      419
#define IDM_COPY_SELECTION              420
#define IDM_VIEW_FULLSCREEN             421
#define IDM_SELECT_ALL                  422
#define IDM_VIEW_SHOW_HIDE_MENUBAR      423
#define IDM_NEW_WINDOW                  424
#define IDM_DUPLICATE_IN_NEW_WINDOW     425
#define IDM_COPY_IMAGE                  427
#define IDM_COPY_LINK_TARGET            428
#define IDM_COPY_COMMENT                429
#define IDM_GOTO_NEXT_PAGE              430
#define IDM_GOTO_PREV_PAGE              431
#define IDM_GOTO_FIRST_PAGE             432
#define IDM_GOTO_LAST_PAGE              433
#define IDM_GOTO_PAGE                   434
#define IDM_FIND_FIRST                  435
#define IDM_FIND_NEXT                   436
#define IDM_FIND_PREV                   437
#define IDM_FIND_MATCH                  438
#define IDM_SAVE_ANNOTATIONS_SMX        439
#define IDM_ZOOM_FIT_PAGE               440
#define IDM_ZOOM_ACTUAL_SIZE            441
#define IDM_ZOOM_FIT_WIDTH              442
#define IDM_ZOOM_6400                   443
#define IDM_ZOOM_3200                   444
#define IDM_ZOOM_1600                   445
#define IDM_ZOOM_800                    446
#define IDM_ZOOM_400                    447
#define IDM_ZOOM_200                    448
#define IDM_ZOOM_150                    449
#define IDM_ZOOM_125                    450
#define IDM_ZOOM_100                    451
#define IDM_ZOOM_50                     452
#define IDM_ZOOM_25                     453
#define IDM_ZOOM_12_5                   454
#define IDM_ZOOM_8_33                   455
#define IDM_ZOOM_FIT_CONTENT            456
#define IDM_ZOOM_CUSTOM                 457
#define IDM_CONTRIBUTE_TRANSLATION      460
#define IDM_VIEW_WITH_ACROBAT           470
#define IDM_VIEW_WITH_FOXIT             471
#define IDM_VIEW_WITH_PDF_XCHANGE       472
#define IDM_VIEW_WITH_XPS_VIEWER        473
#define IDM_VIEW_WITH_HTML_HELP         474
#define IDM_OPEN_SELECTED_DOCUMENT      480
#define IDM_PIN_SELECTED_DOCUMENT       481
#define IDM_FORGET_SELECTED_DOCUMENT    482
#define IDM_OPEN_WITH_EXTERNAL_FIRST    500
#define IDM_OPEN_WITH_EXTERNAL_LAST     509
#define IDM_FILE_HISTORY_FIRST          510
#define IDM_FILE_HISTORY_LAST           519

#define IDM_EXPAND_ALL                  525
#define IDM_COLLAPSE_ALL                526
#define IDM_EXPORT_BOOKMARKS            527
#define IDM_NEW_BOOKMARKS               528
#define IDM_SEPARATOR                   530

#define IDM_VISIT_WEBSITE               550
#define IDM_ABOUT                       551
#define IDM_OPTIONS                     552
#define IDM_CHANGE_LANGUAGE             553
#define IDM_CHECK_UPDATE                554
#define IDM_MANUAL                      555
#define IDM_MOVE_FRAME_FOCUS            557
#define IDM_GOTO_NAV_BACK               558
#define IDM_GOTO_NAV_FORWARD            559
#define IDM_FAV_ADD                     560
#define IDM_FAV_DEL                     561
#define IDM_FAV_TOGGLE                  562
#define IDM_FAV_SHOW                    563
#define IDM_FAV_HIDE                    564
#define IDM_RENAME_FILE                 580
#define IDM_FIND_NEXT_SEL               581
#define IDM_FIND_PREV_SEL               582
#define IDM_DEBUG_SHOW_LINKS            585
#define IDM_DEBUG_CRASH_ME              586
#define IDM_LOAD_MOBI_SAMPLE            587
#define IDM_DEBUG_EBOOK_UI              588
#define IDM_DEBUG_MUI                   589
#define IDM_DEBUG_ANNOTATION            590
#define IDM_DEBUG_DOWNLOAD_SYMBOLS      591
#define IDM_ADVANCED_OPTIONS            596
#define IDM_FAV_FIRST                   600
#define IDM_FAV_LAST                    800
#define IDM_CHANGE_THEME_FIRST          900
#define IDM_CHANGE_THEME_LAST           919
#define IDC_GOTO_PAGE_EDIT              1000
#define IDC_GOTO_PAGE_GO                1001
#define IDC_BUTTON2                     1002
#define IDC_GOTOPAGE_CANCEL             1003
#define IDC_GOTO_PAGE_CANCEL            1004
#define IDC_GOTO_PAGE_LABEL_OF          1005
#define IDC_DIALOG_GET_PASSWORD_EDIT    1006
#define IDC_GET_PASSWORD_EDIT           1007
#define IDC_GET_PASSWORD_LABEL          1008
#define IDC_REMEMBER_PASSWORD           1009
#define IDC_TOOLBAR                     1010
#define IDC_REBAR                       1011
#define IDC_EDIT1                       1012
#define IDC_FAV_NAME_EDIT               1013
#define IDC_DONT_ASK_ME_AGAIN           1014
#define IDC_ADD_PAGE_STATIC             1015
#define IDC_CHANGE_LANG_LANG_LIST       1017
#define IDC_YOU_HAVE                    1018
#define IDC_NEW_AVAILABLE               1019
#define IDC_SKIP_THIS_VERSION           1020
#define IDC_SECTION_VIEW                1021
#define IDC_DEFAULT_LAYOUT_LABEL        1022
#define IDC_DEFAULT_LAYOUT              1023
#define IDC_DEFAULT_ZOOM_LABEL          1024
#define IDC_DEFAULT_ZOOM                1025
#define IDC_DEFAULT_SHOW_TOC            1026
#define IDC_REMEMBER_STATE_PER_DOCUMENT 1027
#define IDC_SECTION_ADVANCED            1028
#define IDC_CHECK_FOR_UPDATES           1029
#define IDC_SET_DEFAULT_READER          1030
#define IDC_REMEMBER_OPENED_FILES       1031
#define IDC_FIND_EDIT                   1032
#define IDC_MATCH_CASE                  1033
#define IDC_FIND_NEXT_HINT              1034
#define IDC_SECTION_INVERSESEARCH       1040
#define IDC_CMDLINE_LABEL               1041
#define IDC_CMDLINE                     1042
#define IDC_USE_TABS                    1045
#define IDC_SECTION_PRINT_RANGE         1050
#define IDC_PRINT_RANGE_ALL             1051
#define IDC_PRINT_RANGE_EVEN            1052
#define IDC_PRINT_RANGE_ODD             1053
#define IDC_SECTION_PRINT_SCALE         1060
#define IDC_PRINT_SCALE_SHRINK          1061
#define IDC_PRINT_SCALE_FIT             1062
#define IDC_PRINT_SCALE_NONE            1063
#define IDC_SECTION_PRINT_COMPATIBILITY 1070
#define IDC_TOC_BOX                     1100
#define IDC_TOC_LABEL_WITH_CLOSE        1101
#define IDC_FAV_BOX                     1105
#define IDC_FAV_LABEL_WITH_CLOSE        1106
#define IDC_FAV_TREE                    1107
#define IDC_TABBAR                      1110
#define IDB_TOOLBAR                     2000
#define IDB_RELOADING_CUE               2010
// TODO: which of these are (still) needed?
#define IDT_FILE_NEW                    3000
#define IDT_FILE_OPEN                   3001
#define IDT_FILE_METAPATH               3002
#define IDT_FILE_SAVE                   3003
#define IDT_EDIT_UNDO                   3004
#define IDT_EDIT_REDO                   3005
#define IDT_EDIT_CUT                    3006
#define IDT_EDIT_COPY                   3007
#define IDT_EDIT_PASTE                  3008
#define IDT_EDIT_FIND                   3009
#define IDT_EDIT_REPLACE                3010
#define IDT_VIEW_WORDWRAP               3011
#define IDT_VIEW_ZOOMIN                 3012
#define IDT_VIEW_ZOOMOUT                3013
#define IDT_VIEW_SCHEME                 3014
#define IDT_VIEW_SCHEMECONFIG           3015
#define IDT_FILE_EXIT                   3016
#define IDT_FILE_SAVEAS                 3017
#define IDT_FILE_SAVECOPY               3018
#define IDT_EDIT_COPYALL                3019
#define IDT_EDIT_CLEAR                  3020
#define IDT_EDIT_FINDNEXT               3021
#define IDT_EDIT_FINDPREV               3022
#define IDT_FILE_PRINT                  3023
#define IDT_FILE_OPENFAV                3024
#define IDT_FILE_ADDTOFAV               3025
#define IDT_VIEW_FIT_WIDTH              3026
#define IDT_VIEW_FIT_PAGE               3027

#define IDD_PUBLIC_APP_KEY              3060
#define IDD_RAMICRO_SPLASH              3061

#define IDC_SUMATRAPDF                  4000
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
