//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SumatraPDF.rc
//
#define IDI_SUMATRAPDF 1

#define IDC_CURSORDRAG 132
#define IDD_PROPSHEET_PRINT_ADVANCED 139

#define IDC_MENUBAR 1016
#define IDC_MENUBAR_REBAR 1018
#define IDC_SECTION_PRINT_RANGE 1050
#define IDC_PRINT_RANGE_ALL 1051
#define IDC_PRINT_RANGE_EVEN 1052
#define IDC_PRINT_RANGE_ODD 1053
#define IDC_SECTION_PRINT_SCALE 1060
#define IDC_PRINT_SCALE_SHRINK 1061
#define IDC_PRINT_SCALE_FIT 1062
#define IDC_PRINT_SCALE_NONE 1063
#define IDC_PRINT_SCALE_STRETCH 1064
#define IDC_PRINT_CENTER_HORIZONTALLY 1065
#define IDC_PRINT_PAPER_SOURCE_BY_SIZE 1066
#define IDC_PRINT_PER_PAGE_PAPER_SIZE 1067
#define IDC_PRINT_ROTATE_LABEL 1068
#define IDC_PRINT_ROTATE 1069
#define IDC_SECTION_PRINT_COMPATIBILITY 1070
#define IDB_RELOADING_CUE 2010

#define IDC_STATIC (-1)

#define IDR_DLL_PAK 1
// translations.txt + marked.min.js + mermaid.min.js + in-app manual (.work/embedded.dat)
#define IDR_EMBEDDED_PAK 2

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC 1
#define _APS_NEXT_RESOURCE_VALUE 144
#define _APS_NEXT_COMMAND_VALUE 32771
#define _APS_NEXT_CONTROL_VALUE 1085
#define _APS_NEXT_SYMED_VALUE 110
#endif
#endif
