/* Generated by scripts\update_translations.py
   DO NOT EDIT MANUALLY */
#ifndef Translations_txt_h
#define Translations_txt_h

#define LANGS_COUNT   60
#define STRINGS_COUNT 187

typedef struct LangDef {
    const char *_langName;
    const char *_langMenuTitle;
    LANGID _langId;
} LangDef;

extern LangDef g_langs[LANGS_COUNT];
extern const char *g_transLangs[LANGS_COUNT];
extern const char *g_transTranslations[LANGS_COUNT * STRINGS_COUNT];

#endif
