.TH MUPDF 1 "March 15, 2010"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
mupdf \- MuPDF is a lightweight PDF viewer written in portable C
.SH SYNOPSIS
.B mupdf
.RI [ options ] " PDFfile"
.SH DESCRIPTION
This manual page briefly describes the
.B mupdf
command.
.PP
.SH OPTIONS
A description of each of the supported options is included below.
.TP
.B \-p password
Uses the given password to open an encrypted PDF file.
The password is tried both as user and owner password.
.TP
.B \-r resolution
Changes the initial zoom level, specified as the resolution in dpi.
The default value is 72.
.SH MOUSE AND KEY BINDINGS
In addition to the key bindings described below, the mouse can also be
used. Clicking the left mouse button follows links within the PDF while
dragging with the left mouse button pans the page. Dragging with the right
mouse button selects an area and copies the enclosed text to the clipboard
buffer. Using the scroll-wheel while pressing Control zooms in/out, if
Shift is pressed on the other hand then the page is panned.
.TP
.B PAGE NAVIGATION
These commands relate to the actual page number in the PDF file, not to
numbers given by any kind of page label.
.TP
.B f, space
Go to the next page without paning to top of page. If a number has been
entered, go that number of pages forward instead of just one page.
.TP
.B b, backspace
Go to the previous page without paning to top of page. If a number has been
entered, go that number of pages backwards instead of just one page.
.TP
.B g, return
Go to the page number specified. If no number has been entered, go to the
first page.
.TP
.B G
Go to the last page.
.TP
.B t
Tag the viewed page and record it in the history. When clicking links
within a PDF file to follow the link pages are automatically tagged.
.TP
.B m
Return to the previously tagged page in the history.
.TP
.B p
Go to the previous page and pan to bottom of page. If a number has been
entered, go that number of pages backwards instead of just one page.
.TP
.B n
Go to the next page and pan to top of page. If a number has been entered,
go that number of pages forward instead of just one page.
.TP
.B B
Go ten pages backwards and pan to top of page.
.TP
.B F
Go ten pages forward and pan to top of page.
.TP
.B PAN PAGE
.TP
.B w
Shrinkwrap window frame to page size.
.TP
.B d
Pan the shown page down 1/10th of its height.
.TP
.B u
Pan the shown page up 1/10th of its height.
.TP
.B ,
Pan the shown page right 1/10th of its width.
.TP
.B .
Pan the shown page left 1/10th of its width.
.TP
.B 0\-9
Entered numbers are used by some commands.
.TP
.B ZOOM AND ROTATE PAGE
.TP
.B \+, \=
Zoom in.
.TP
.B \-
Zoom out.
.TP
.B <
Rotate page counter-clockwise or left by 90\(de.
.TP
.B >
Rotate page clockwise or right by 90\(de.
.TP
.B a
Rotate page counter-clockwise or left by 15\(de.
.TP
.B s
Rotate page clockwise or right by 15\(de.
.TP
.B FILE HANDLING
.TP
.B r
Reload the file and display the same page, if still present.
.SH SEE ALSO
.BR pdfclean (1),
.BR pdfdraw (1),
.BR pdfshow (1).
.SH AUTHOR
MuPDF was written by Tor Andersson <tor@ghostscript.com>.
MuPDF is Copyright 2006-2010 Artifex Software, Inc.
.PP
This manual page was written by Sebastian Rasmussen <sebras@hotmail.com>.
