name: Build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [build-pre-rel]
permissions:
  contents: read
jobs:
  build:
    name: Build
    #runs-on: SumatraBuilder
    runs-on: windows-2025-vs2026
    steps:
      - name: Check out source code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0
          persist-credentials: false

      - name: Install bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - name: Build
        env:
          R2_SECRET: ${{ secrets.R2_SECRET }}
          R2_ACCESS: ${{ secrets.R2_ACCESS }}
          BB_SECRET: ${{ secrets.BB_SECRET }}
          BB_ACCESS: ${{ secrets.BB_ACCESS }}
        run: bun .\cmd\build.ts -ci
